hashicorp/terraform-cdk

- README.md
Adds link to the install guide and quick start tutorial.
> Link to Learn tutorial from README

- README.md
- examples/typescript-azure/.gitignore
- examples/typescript-azure/Readme.md
- examples/typescript-azure/cdktf.json
- examples/typescript-azure/help
- examples/typescript-azure/main.ts
- examples/typescript-azure/package.json
- examples/typescript-azure/tsconfig.json
An AzureRm provider example adapted from aws and google samples.
> Add Azure Example

- README.md
> Readme: fix link to cdktf/

- README.md
- examples/python-kubernetes/.gitignore
- examples/python-kubernetes/Pipfile
- examples/python-kubernetes/Pipfile.lock
- examples/python-kubernetes/README.md
- examples/python-kubernetes/cdktf.json
- examples/python-kubernetes/help
- examples/python-kubernetes/main.py
Inspired by #185, a Kubernetes example in Python based on the config from the [HashiCorp Kubernetes Learn guide](https://learn.hashicorp.com/terraform/kubernetes/deploy-nginx-kubernetes).
> Add Kubernetes Python example

- packages/cdktf-cli/bin/cmds/ui/deploy.tsx
- packages/cdktf-cli/bin/cmds/ui/destroy.tsx
> Change input for cdktf deploy and destroy to match Terraform

- CHANGELOG.md
- package.json
> Prepare 0.0.14 release

- packages/cdktf-cli/lib/get/generator/resource-parser.ts
Fixes https://github.com/hashicorp/terraform-cdk/issues/299
> Fix Naming Collision with Config interfaces

- examples/typescript/google-cloudrun/.gitignore
- examples/typescript/google-cloudrun/README.md
- examples/typescript/google-cloudrun/cdktf.json
- examples/typescript/google-cloudrun/help
- examples/typescript/google-cloudrun/main.ts
- examples/typescript/google-cloudrun/package.json
- examples/typescript/google-cloudrun/tsconfig.json
Add one typescript **gcp** example to demonstrating below CDK for Terraform features:
- gcp CloudRun
> FEATURE:  Add typescript example gcp cloudrun

- .github/workflows/build.yml
- .gitignore
- package.json
- packages/cdktf-cli/bin/cmds/ui/models/terraform.ts
- test/run-against-dist.bat
- test/test-init-with-colors/test.js
- test/test-typescript-deploy/test.js
Aiming to fix https://github.com/hashicorp/terraform-cdk/issues/201
Planning to convert most test scripts to JS and then run on a GitHub Windows runner.
> Windows integration tests

- packages/cdktf-cli/templates/typescript/.hooks.sscaff.js
> use remote backend class for typescript template

- packages/cdktf-cli/bin/cmds/ui/models/terraform.ts
- packages/cdktf-cli/lib/util.ts
This PR helps with metrics for the project during the experimental period.
Helps with #325
> adding cdktf version to the terraform user agent

- packages/cdktf-cli/lib/get/generator/emitter/resource-emitter.ts
- packages/cdktf-cli/test/get/generator/__snapshots__/complex-computed-types.test.js.snap
- packages/cdktf-cli/test/get/generator/__snapshots__/complex-computed-types.test.ts.snap
- packages/cdktf-cli/test/get/generator/__snapshots__/description-escaping.test.ts.snap
- packages/cdktf-cli/test/get/generator/__snapshots__/provider.test.ts.snap
- packages/cdktf-cli/test/get/generator/__snapshots__/resource-types.test.ts.snap
- packages/cdktf-cli/test/get/generator/__snapshots__/types.test.ts.snap
- packages/cdktf/lib/terraform-output.ts
- packages/cdktf/test/helper/provider.ts
- packages/cdktf/test/helper/resource.ts
In the recent Jsii release https://github.com/aws/jsii/releases/tag/v1.11.0 a detection for
changing visibility when overriding was added https://github.com/aws/jsii/pull/1876 and prevents
it from building.
> Don't change visibility for "synthesizeAttributes"

- README.md
update README.md to refer to google-cloudrun example 😊 😊 😊
> update README.md to refer to google-cloudrun example

- .github/workflows/build.yml
- examples/python/aws-eks/cdktf.json
- examples/python/aws/cdktf.json
- examples/python/docker/cdktf.json
- examples/python/kubernetes/cdktf.json
- package.json
- packages/cdktf-cli/templates/python/.hooks.sscaff.js
- packages/cdktf-cli/templates/python/Pipfile
- packages/cdktf-cli/templates/python/cdktf.json
- test/test-all.bat
- test/test-python-app/cdktf.json
- test/test-python-app/test.js
- test/test-python-third-party-provider/cdktf.json
- tools/collect-dist.bat
Aiming to fix #194 , #267, #268 and anything else that comes up while getting python working on Windows.
> Windows Python fixes

- .github/workflows/release.yml
- README.md
- docs/getting-started/python.md
This is for https://github.com/hashicorp/terraform-cdk/issues/65. Raised a PR on homebrew https://github.com/Homebrew/homebrew-core/pull/60113 for the same.
Also added a release_homebrew workflow, which should kick-off if the commit message has 'Bump version' in it, needs a committer token to automatically create a PR on homebrew after a release.
> Adding Homebrew package

- examples/typescript/azure-app-service/.gitignore
- examples/typescript/azure-app-service/README.md
- examples/typescript/azure-app-service/cdktf.json
- examples/typescript/azure-app-service/help
- examples/typescript/azure-app-service/main.ts
- examples/typescript/azure-app-service/package.json
- examples/typescript/azure-app-service/tsconfig.json
Add one typescript azure  example to demonstrating below CDK for Terraform features:
Azure App Service
> Add typescript example  Azure App Service 😊

- examples/python/azure/Pipfile
- examples/python/azure/Pipfile.lock
- examples/python/azure/README.md
- examples/python/azure/cdktf.json
- examples/python/azure/help
- examples/python/azure/main.py
- examples/python/azure/package.json
Add a cdktf python Azure example, thank you!
> Add a cdktf python Azure example

- README.md
- docs/working-with-cdk-for-terraform/terraform-locals.md
- packages/cdktf/lib/index.ts
- packages/cdktf/lib/terraform-local.ts
- packages/cdktf/test/__snapshots__/local.test.js.snap
- packages/cdktf/test/local.test.ts
Closes #281 
Very simple terraform local which is just a bit more than an escape hatch at this point. We'll probably expand a bit down the road, but a local is still likely to be a bit of a wrapper. That said, it is part of hcl, so seems like something worth having for completeness.
I'll fill in tests/documentation if this seems worthwhile to others.
> Simple Terraform Locals

- .github/workflows/examples.yml
- packages/cdktf-cli/lib/get/generator/provider-schema.ts
PR to fix issue https://github.com/hashicorp/terraform-cdk/issues/358
> allow to use TERRAFORM_BINARY_NAME env to set terraform binary

- README.md
- docs/working-with-cdk-for-terraform/terraform-variables.md
- packages/cdktf/lib/index.ts
- packages/cdktf/lib/terraform-variable.ts
- packages/cdktf/test/__snapshots__/variable.test.js.snap
- packages/cdktf/test/variable.test.ts
Adds support for defining Terraform Variables #249
> Terraform Variables

- .devcontainer.json
This follows the example of the AWS CDK [config](https://github.com/aws/aws-cdk/blob/af2e8fff6cdef7ef1c0bda35873f782837307dd6/.devcontainer.json). Fixes #381
> Preconfigure Github Codespaces

- .gitignore
- .npmignore
Ignore `terraform-cdk.github-issues` for https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-github-issue-notebooks
> Ignore terraform-cdk.github-issues

- packages/cdktf/package.json
- yarn.lock
Fixes #394 
Updates jsii to get fix for https://github.com/aws/jsii/issues/2137.
> Update jsii with python docs fix

- examples/python/aws/README.md
> Fix small typo

- Dockerfile
Ensure compatibility with [Terraform 0.14](https://github.com/hashicorp/terraform/blob/v0.14.0/CHANGELOG.md)
> Build Docker Image with Terraform 0.14

- packages/cdktf-cli/bin/cmds/init.ts
> Use correct pre-release version in cdktf-cli

- docs/cli-commands.md
Fixes https://github.com/hashicorp/terraform-cdk/issues/426
> Add docs for `CI` env

- packages/cdktf-cli/templates/java/cdktf.json
- test/test-java-app/cdktf.json
- test/test-java-app/expected/cdk.tf.json
This got missed somewhere along the line.
> Include feature flags in java template and test

- packages/cdktf-cli/test/get/generator/__snapshots__/types.test.ts.snap
- packages/cdktf-cli/test/get/generator/fixtures/incompatible-attribute-names.test.fixture.json
Was about to fix it and realized this is already there. So, here's just an addition to the snapshot test for this.
> Add test-case for equals -> equalTo

- examples/csharp/azure/Main.cs
- examples/java/azure/src/main/java/com/mycompany/app/Main.java
> Azure provider requires at least 1 feature

- .github/workflows/docker.yml
It get a failure email every time I update my master branch, and I do some amount of action testing.
> Don't run docker build on forks

- packages/cdktf-cli/templates/csharp/.hooks.sscaff.js
- packages/cdktf-cli/templates/java/.hooks.sscaff.js
- packages/cdktf-cli/templates/python-pip/.hooks.sscaff.js
- packages/cdktf-cli/templates/python/.hooks.sscaff.js
Fixes #500
Would be nice to come up with some test for this.
> Quote cdktf path in init templates

- CHANGELOG.md
Add dates of previous releases to CHANGELOG.md
> add dates to CHANGELOG.md

- packages/cdktf-cli/lib/get/generator/provider-schema.ts
- packages/cdktf-cli/lib/get/generator/resource-parser.ts
- packages/cdktf-cli/test/get/generator/__snapshots__/types.test.ts.snap
- packages/cdktf-cli/test/get/generator/fixtures/primitive-dynamic.test.fixture.json
- packages/cdktf-cli/test/get/generator/types.test.ts
> Support for dynamic attribute type

- packages/cdktf-cli/package.json
- yarn.lock
Fixes #501 (or at least a portion of it).
> Update jsii-srcmak to remove symlink

- Dockerfile
Once this is merged, there will be a follow up to clean up the
unused versions
> Add new Terraform versions

- packages/@cdktf/hcl2json/README.md
A bit more context for the `hcl2json` package.
> Add Readme for hcl2json package

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/feature-request.md
"new" label will help identify untriaged issues
> Add "new" label to issue templates

- docs/getting-started/csharp.md
> Set correct filename for Main

- CONTRIBUTING.md
While setting up the project I found these dependencies to the development machine to exist :)
> Add prerequisites to contributing docs

- packages/cdktf-cli/lib/get/generator/resource-parser.ts
- packages/cdktf-cli/test/get/provider.test.ts
> Fix elasticsearch index resource

- test/typescript/multiple-stacks/test.ts
Related to #689. I don't know why that branch was green on the PR but not after being merged.. I thought integration tests would run when submitting PRs 🤔
> fix integration test if no stack was supplied to command

- packages/cdktf-cli/bin/cmds/ui/terraform-context.tsx
Update resource regexp to match terraform spec
> Update resource regexp to match terraform spec

- docs/getting-started/csharp.md
- docs/getting-started/java.md
They were already mentioned in the section above this one.
> docs: remove redundant commands

- test/go/synth-app/cdktf.json
- test/go/synth-app/go.mod.append
- test/go/synth-app/main.go
…to use generated as output directory and remove obsolete unused file
> fix(test): update go integration test

- .github/workflows/build.yml
- .github/workflows/examples.yml
- Dockerfile
- packages/cdktf-cli/test/get/__snapshots__/read-schema.test.ts.snap
- packages/cdktf-cli/test/get/read-schema.test.ts
Follow up for https://github.com/hashicorp/terraform-cdk/pull/719
> chore(tests): Adapt workflows to new terraform versions of 0.14 and 0.15

- packages/cdktf/lib/terraform-asset.ts
This should improve the editor experience
> chore(docs): add jsdoc comments

- README.md
- docs/getting-started/go.md
- docs/getting-started/python.md
- docs/getting-started/typescript.md
- docs/working-with-cdk-for-terraform/app-stacks-concept.md
- docs/working-with-cdk-for-terraform/terraform-assets.md
This adds links to Learn tutorials from the CDKTF documentation.
> chore(docs): Add callouts to Learn tutorials

- examples/python/google/cloud-function/.gitignore
- examples/python/google/cloud-function/Pipfile
- examples/python/google/cloud-function/Pipfile.lock
- examples/python/google/cloud-function/README.md
- examples/python/google/cloud-function/cdktf.json
- examples/python/google/cloud-function/cloud_function_stack.py
- examples/python/google/cloud-function/function/main.py
- examples/python/google/cloud-function/help
- examples/python/google/cloud-function/main.py
- examples/python/google/cloud-function/package.json
- Used Terraform Asset for uploading the cloud function source code to bucket.
- Added package.json
> chore(docs): python example for gcp cloud function

- README.md
I hope this helps a bit to clarify that we support all providers and modules
> refactor(docs): clarify that we support all providers and modules

- packages/cdktf-cli/templates/typescript/tsconfig.json
> fix(cli): dont compile cdktf output directory

- packages/cdktf-cli/bin/cmds/init.ts
.. to adhere to new naming introduced by multiple stacks feature
> fix(cli): update hint for tfstate file

- BUGPROCESS.md
Proposed bug and enhancement request triage process
> chore(docs): Create BUGPROCESS.md 

- packages/@cdktf/hcl2cdk/lib/generation.ts
- packages/@cdktf/hcl2cdk/test/__snapshots__/hcl2cdk.test.ts.snap
- packages/@cdktf/hcl2cdk/test/hcl2cdk.test.ts
> fix(hcl2cdk): camelCase backend properties

- docs/working-with-cdk-for-terraform/terraform-cloud.md
> feat(docs): document how to connect CDKTF to Terraform Cloud

- docs/working-with-cdk-for-terraform/terraform-variables.md
- packages/@cdktf/hcl2cdk/lib/index.ts
- packages/@cdktf/hcl2cdk/test/__snapshots__/hcl2cdk.test.ts.snap
To test get a snippet with a terraform variable
> feat(hcl2cdk): inform about recommended variable usage

- docs/working-with-cdk-for-terraform/terraform-cloud.md
- packages/@cdktf/hcl2cdk/lib/index.ts
- packages/@cdktf/hcl2cdk/test/__snapshots__/hcl2cdk.test.ts.snap
- packages/@cdktf/hcl2cdk/test/hcl2cdk.test.ts
> fix(hcl2cdk):  aliased provider missed in graph

- packages/cdktf/lib/tokens/private/encoding.ts
- packages/cdktf/lib/tokens/private/resolve.ts
- packages/cdktf/test/__snapshots__/resource.test.js.snap
- packages/cdktf/test/helper/resource.ts
- packages/cdktf/test/resource.test.ts
> fix(lib): synthesise numbers correctly

- packages/cdktf-cli/bin/cmds/ui/deploy.tsx
- packages/cdktf-cli/test/ui/deploy.test.tsx
> fix(cli): Don't print sensitive outputs when running deploy

- test/test-helper.ts
- test/typescript/modules/test.ts
- test/typescript/multiple-stacks/test.ts
- test/typescript/terraform-cloud/test.ts
It seems like we fail ungracefully if there is a network error and that on CI network errors only happen on windows
> fix(tests): disable terraform cloud test for now

- packages/cdktf-cli/bin/cmds/deploy.ts
- packages/cdktf-cli/bin/cmds/destroy.ts
- packages/cdktf-cli/bin/cmds/diff.ts
- packages/cdktf-cli/bin/cmds/get.ts
- packages/cdktf-cli/bin/cmds/helper/check-environment.ts
- packages/cdktf-cli/bin/cmds/init.ts
- packages/cdktf-cli/bin/cmds/list.ts
- packages/cdktf-cli/bin/cmds/synth.ts
- packages/cdktf-cli/package.json
> feat(cli): detect and validate used node & go version

- docs/working-with-cdk-for-terraform/testing.md
We will add this later on, once #1006 is done we can revert this PR
> chore(docs): remove custom adapter section for now

- packages/cdktf-cli/lib/checkpoint.ts
> fix(cli): replaceAll not available in node v14

- packages/cdktf-cli/lib/util.ts
> fix(cli): fix import path for Manifest (was relative)

- .github/workflows/release.yml
- .github/workflows/release_next.yml
Provide outputs for dynamic matrix
Follow up for https://github.com/hashicorp/terraform-cdk/pull/1043
> chore(tests): Fix release pipeline

- test/csharp/synth-app/test.ts
- test/go/synth-app/test.ts
- test/java/synth-app/test.ts
- test/jest.config.js
- test/jest.setup.js
- test/package.json
- test/python/asset/test.ts
- test/python/multiple-stacks/test.ts
- test/python/synth-app/test.ts
- test/python/terraform-functions/test.ts
- test/python/third-party-provider/test.ts
- test/typescript/asset/test.ts
- test/typescript/diff-deploy-destroy/test.ts
- test/typescript/feature-flags/test.ts
- test/typescript/init-remote-template/test.ts
- test/typescript/init-with-colors/test.ts
- test/typescript/modules/test.ts
- test/typescript/multiple-stacks/test.ts
- test/typescript/providers/test.ts
- test/typescript/synth-app-error/test.ts
- test/typescript/synth-app/test.ts
- test/typescript/synth-error-annotations/test.ts
- test/typescript/terraform-cloud/test.ts
- test/typescript/watch/test.ts
- test/yarn.lock
chore(tests): Upgrade to jest 0.27 for integration tests and retry failed tests once
> chore(tests): Upgrade to jest 0.27 for integration tests and retry failed tests once

- website/docs/cdktf/concepts/fundamentals/cdktf-json.md
- website/docs/cdktf/create-and-deploy/project-setup.html.md
- website/docs/cdktf/stacks.html.md
- website/layouts/cdktf.erb
Hi @skorfmann! 
So, I was reviewing your project setup PR, and I wanted to 1) address your comments and 2) provide feedback. And, it became such that I think it would have been absolutely awful for you to review all of that through the github UI as comments. So instead, I made a branch from your branch where I made some edits (described below). I thought you could review and we could either merge this into your branch and then merge your branch into `terraform-io-docs` OR merge this branch directly into 'terraform-io-docs' and close your initial PR. I hope this is okay, but please let me know if you want me to handle this differently in the future.
In this PR I:
- Moved the cdktf.json page to be underneath the Create and Deploy section, rather than under fundamentals. Thank you so much …
> Feedback and edits to project setup PR :-)

- .github/workflows/release.yml
The code needs to be checked out for the next step to work
> fix(lib): Fix release pipeline

- .github/workflows/release.yml
> chore(lib): Fix release

- website/docs/cdktf/cli-reference/configuration.html.md
Closes https://github.com/hashicorp/terraform-cdk/issues/998 
This PR adds a link to the cdktf.json documentation.
> chore(docs): Update cli configuration doc

- website/docs/cdktf/concepts/aspects.html.md
- website/layouts/cdktf.erb
This adds the aspects docs to the website
> chore(docs): copy over aspects

- examples/python/aws-eks/main.py
- examples/python/aws/main.py
- examples/python/azure/cdktf.json
- examples/python/azure/main.py
- examples/python/google/cloud-function/main.py
- examples/python/kubernetes/main.py
- examples/python/ucloud/main.py
Fix python build (azure) which was using python 2.7 for some reason
> fix(examples): Make sure we're using pipenv

- examples/typescript/azure-service-bus-queue-trigger/package.json
- package.json
- packages/@cdktf/hcl2cdk/lib/expressions.ts
- packages/@cdktf/hcl2cdk/package.json
- packages/@cdktf/hcl2json/package.json
- packages/@cdktf/provider-generator/lib/index.ts
- packages/@cdktf/provider-generator/package.json
- packages/cdktf-cli/package.json
- test/package.json
- test/yarn.lock
- yarn.lock
Doing a yarn upgrade as a batch PR to have a good starting point for dependabot
> chore(deps): yarn upgrade

- packages/@cdktf/provider-generator/lib/get/__tests__/generator/__snapshots__/complex-computed-types.test.ts.snap
- packages/@cdktf/provider-generator/lib/get/__tests__/generator/__snapshots__/provider.test.ts.snap
- packages/@cdktf/provider-generator/lib/get/__tests__/generator/__snapshots__/resource-types.test.ts.snap
- packages/@cdktf/provider-generator/lib/get/__tests__/generator/__snapshots__/types.test.ts.snap
- packages/@cdktf/provider-generator/lib/get/generator/emitter/attributes-emitter.ts
Testing if this switch is strictly required
> refactor(provider-generator): remove unneccessary special case

- website/docs/cdktf/concepts/providers-and-resources.html.md
I always have to look up how this works, figured we should have at least a sentence to this topic
> chore(docs): document list escape hatches

- website/docs/cdktf/concepts/providers-and-resources.html.md
- website/docs/cdktf/concepts/stacks.html.md
- website/layouts/cdktf.erb
Small fixes to recent docs update - links and sidebar menu.
> chore(docs): link and layout fixes

- website/docs/cdktf/concepts/functions.html.md
- website/docs/cdktf/concepts/modules.html.md
- website/docs/cdktf/concepts/variables-and-outputs.html.md
more broken anchor links from some PRs that came in for the new release :-)
> chore(docs): Fix broken anchor links

- packages/cdktf/lib/terraform-functions.ts
We had a typo here from copy and paste
> fix(lib): fix documentation link for lookup

- docs/working-with-cdk-for-terraform/cdktf-json.md
- examples/python/docker/cdktf.json
- examples/typescript/docker/cdktf.json
- packages/cdktf/test/helper/provider.ts
> chore: update all references to the Docker Terraform provider to kreuzwerker/docker

- packages/cdktf/lib/terraform-functions.ts
- packages/cdktf/test/functions.test.ts
> fix(lib): Fix incorrect parseInt casing

- packages/@cdktf/provider-generator/lib/config.test.ts
- packages/@cdktf/provider-generator/lib/config.ts
> fix(provider-generator): Fix private registry module generation

- packages/cdktf-cli/bin/cmds/ui/models/terraform-cloud.ts
> fix(cli): only log if logs are sent

- docs/README.md
Adds a short README to the /docs folder to point people the the new home for docs on terraform.io
> chore(docs): Adds a REAMDE to docs folder

- packages/@cdktf/provider-generator/lib/__tests__/__snapshots__/edge-provider-schema.test.ts.snap
- packages/@cdktf/provider-generator/lib/get/__tests__/generator/__snapshots__/complex-computed-types.test.ts.snap
- packages/@cdktf/provider-generator/lib/get/__tests__/generator/__snapshots__/resource-types.test.ts.snap
- packages/@cdktf/provider-generator/lib/get/__tests__/generator/__snapshots__/types.test.ts.snap
- packages/@cdktf/provider-generator/lib/get/generator/emitter/struct-emitter.ts
- test/typescript/edge/main.ts
- test/typescript/edge/test.ts
> fix(provider-generator): Fix false block attributes

- examples/typescript/aws-cloudfront-proxy/package.json
- examples/typescript/aws-multiple-stacks/package.json
- examples/typescript/aws-prebuilt/package.json
- examples/typescript/azure-app-service/package.json
- examples/typescript/azure-service-bus-queue-trigger/package.json
- examples/typescript/azure/package.json
- examples/typescript/backends/azurerm/package.json
- examples/typescript/backends/gcs/package.json
- examples/typescript/backends/remote/package.json
- examples/typescript/backends/s3/package.json
- examples/typescript/docker/package.json
- examples/typescript/google-cloudrun/package.json
- examples/typescript/google/package.json
- examples/typescript/kubernetes/package.json
- examples/typescript/ucloud/package.json
- examples/typescript/vault/package.json
- packages/cdktf-cli/package.json
- packages/cdktf/package.json
- yarn.lock
This fixes a CI issue with CSharp integration tests
> chore: update constructs to 10.0.20

- .github/dependabot.yml
- .github/workflows/yarn-upgrade.yml
> chore: replace dependabot with a weekly running script

- packages/cdktf-cli/bin/cmds/ui/models/terraform-cli.ts
- packages/cdktf/lib/backends/local-backend.ts
- test/csharp/synth-app/Main.cs
- test/csharp/synth-app/__snapshots__/test.ts.snap
- test/go/synth-app/__snapshots__/test.ts.snap
- test/go/synth-app/main.go
- test/java/synth-app/Main.java
- test/java/synth-app/__snapshots__/test.ts.snap
- test/python/asset/__snapshots__/test.ts.snap
- test/python/asset/main.py
- test/python/multiple-stacks/__snapshots__/test.ts.snap
- test/python/multiple-stacks/main.py
- test/python/providers/__snapshots__/test.ts.snap
- test/python/providers/main.py
- test/python/synth-app/__snapshots__/test.ts.snap
- test/python/synth-app/main.py
- test/python/terraform-functions/__snapshots__/test.ts.snap
- test/python/terraform-functions/main.py
- test/typescript/asset/__snapshots__/test.ts.snap
- test/typescript/asset/main.ts
- test/typescript/feature-flags/__snapshots__/test.ts.snap
- test/typescript/feature-flags/main.ts
- test/typescript/modules/__snapshots__/test.ts.snap
- test/typescript/modules/main.ts
- test/typescript/multiple-stacks/__snapshots__/test.ts.snap
- test/typescript/multiple-stacks/main.ts
- test/typescript/synth-app/__snapshots__/test.ts.snap
- test/typescript/synth-app/main.ts
> fix(cli): remove deprecated -state option

- package.json
- packages/cdktf/lib/synthesize/synthesizer.ts
- packages/cdktf/lib/testing/index.ts
- packages/cdktf/package.json
- packages/cdktf/test/__snapshots__/data-source.test.ts.snap
- packages/cdktf/test/__snapshots__/local.test.ts.snap
- packages/cdktf/test/__snapshots__/output.test.ts.snap
- packages/cdktf/test/__snapshots__/provider.test.ts.snap
- packages/cdktf/test/__snapshots__/remote-state.test.ts.snap
- packages/cdktf/test/__snapshots__/resource.test.ts.snap
- packages/cdktf/test/__snapshots__/terraform-hcl-module.test.ts.snap
- packages/cdktf/test/__snapshots__/variable.test.ts.snap
- test/csharp/synth-app/__snapshots__/test.ts.snap
- test/go/synth-app/__snapshots__/test.ts.snap
- test/java/synth-app/__snapshots__/test.ts.snap
- test/python/asset/__snapshots__/test.ts.snap
- test/python/multiple-stacks/__snapshots__/test.ts.snap
- test/python/providers/__snapshots__/test.ts.snap
- test/python/synth-app/__snapshots__/test.ts.snap
- test/python/terraform-functions/__snapshots__/test.ts.snap
- test/typescript/asset/__snapshots__/test.ts.snap
- test/typescript/feature-flags/__snapshots__/test.ts.snap
- test/typescript/modules/__snapshots__/test.ts.snap
- test/typescript/multiple-stacks/__snapshots__/test.ts.snap
- test/typescript/synth-app/__snapshots__/test.ts.snap
- yarn.lock
Resolves #1384
Unfortunately it prints empty objects like this:
```
"a": {
}
```
It looks quite ugly, but that could be on purpose, as it might produce simpler diffs when properties are added to those objects later on 🤔
> feat(lib): produce stable `cdk.tf.json` output

- .github/workflows/project-board.yml
we were running into secondary rate limits
> chore: decrease update speed of the project board

- examples/typescript/azure-app-service/main.ts
Rewriting example code to Azure App Service.
Closes https://github.com/hashicorp/terraform-cdk/issues/1386
> chore: update example for azure app service

- website/docs/cdktf/release/upgrade-guide-v0-9.mdx
> (chore)docs: edit to upgrade guide

- website/data/cdktf-nav-data.json
adds 0.9 upgrade guide to side nav
> (chore)docs: add upgrade guide to nav

- website/docs/cdktf/concepts/modules.mdx
I didn't knew we support this, when I found out I thought a quick addition to the docs might be nice
> chore: document submodules

- packages/@cdktf/hcl2cdk/package.json
- packages/@cdktf/provider-generator/package.json
- packages/cdktf-cli/package.json
- packages/cdktf/package.json
- test/package.json
- yarn.lock
jsii v1.53.0 includes https://github.com/aws/jsii/pull/3362
> chore(deps): upgrade jsii (substantially improves cdktf get performance for Go)

- packages/@cdktf/hcl2cdk/.gitignore
- packages/@cdktf/hcl2cdk/lib/generation.ts
- packages/@cdktf/hcl2cdk/lib/index.ts
- packages/@cdktf/hcl2cdk/test/__snapshots__/hcl2cdk.test.ts.snap
- packages/@cdktf/hcl2cdk/test/hcl2cdk.test.ts
- packages/@cdktf/provider-generator/lib/get/generator/provider-schema.ts
- packages/cdktf-cli/bin/cmds/handlers.ts
> fix(hcl2cdk): handle no providers passed and add cdktf import for remote state data sources

- .github/workflows/timechart.yml
- .github/workflows/update-snapshots.yml
WyriHaximus/github-action-wait-for-status#81 includes a fix that leads to red runs currently
> chore: update timechart check

- CHANGELOG.md
- CONTRIBUTING.md
- docs/getting-started/csharp.md
- docs/getting-started/go.md
- docs/getting-started/java.md
- docs/getting-started/python.md
- docs/getting-started/typescript.md
- examples/typescript/aws-kubernetes/package.json
- examples/typescript/azure-app-service/package.json
- examples/typescript/azure-service-bus-queue-trigger/package.json
- examples/typescript/azure/package.json
- examples/typescript/backends/azurerm/package.json
- examples/typescript/backends/gcs/package.json
- examples/typescript/backends/remote/package.json
- examples/typescript/backends/s3/package.json
- examples/typescript/google-cloudrun/package.json
- examples/typescript/google/package.json
- examples/typescript/kubernetes/package.json
- examples/typescript/ucloud/package.json
- examples/typescript/vault/package.json
- packages/@cdktf/hcl2cdk/test/convertProject.test.ts
- packages/cdktf-cli/bin/cmds/helper/check-environment.ts
- packages/cdktf-cli/templates/typescript/package.json
> fix(cli): reflect correct node version requirement

- package.json
Forgot to update the version in the package.json
> chore: release 0.9.2

- packages/cdktf-cli/bin/cmds/convert.ts
- packages/cdktf-cli/bin/cmds/handlers.ts
- packages/cdktf-cli/test/cmds/convert.test.ts
> fix(cli): convert failed with a single provider passed

- CHANGELOG.md
- package.json
- fix(lib): check for null objects and don't try to reverse undefined or null [\#1592](https://github.com/hashicorp/terraform-cdk/pull/1592)
- chore(cli): fix typo in test assertion [\#1591](https://github.com/hashicorp/terraform-cdk/pull/1591)
> chore(release): 0.9.4

- website/vercel.json
Add Vercel config to silence the comments on PRs, which is what we do across our other product repositories.
> chore(docs): add vercel config

- packages/cdktf/lib/backends/gcs-backend.ts
> feat(lib): Support `impersonate_service_account` and `_delegate` on `gcs` backend

- packages/cdktf-cli/lib/index.ts
Previously we would print an inlined JSON when running against TFC with structured log output enabled
> fix(cli): parse JSON log lines if possible

- packages/cdktf-cli/bin/cmds/helper/terraform-cloud-client.ts
- packages/cdktf-cli/bin/cmds/helper/terraform-login.ts
> feat(cli): check whether an existing token is still valid when running login command

- test/typescript/watch/test.ts
It's currently flaking a lot, so we want to investigate it properly without blocking the current work
> chore: disable watch test

- website/data/cdktf-nav-data.json
Adds a link to the docs sidebar for the 0.10 Upgrade Guide.
> chore(docs): add sidebar link

- tools/update-github-project-board/index.ts
I added a new column since I didn't see a comminuty PR in the repository-manager repo earlier, you can see it live: https://github.com/orgs/hashicorp/projects/125/views/4
> chore: add extra column for PRs outside our main repo

- packages/@cdktf/hcl2cdk/test/__snapshots__/hcl2cdk.test.ts.snap
- packages/@cdktf/hcl2cdk/test/hcl2cdk.test.ts
This way we can limit the execution to a single test case more easily
> refactor(tests): move from table driven tests to functional way

- website/README.md
update **Modifying Sidebar Navigation** and **Deployment**
> chore: Update README.md

- website/docs/cdktf/concepts/aspects.mdx
A construct update and usage changes in map tokens caused this change
Closes #1685
> chore(docs): update aspect docs

- website/docs/cdktf/cli-reference/commands.mdx
> chore(docs): update convert docs

- packages/cdktf/lib/terraform-functions.ts
- packages/cdktf/test/__snapshots__/functions.test.ts.snap
- packages/cdktf/test/functions.test.ts
> fix(lib): contextualize error messages in terraform functions

- packages/@cdktf/hcl2cdk/test/__snapshots__/hcl2cdk.test.ts.snap
- packages/@cdktf/hcl2cdk/test/hcl2cdk.test.ts
- packages/cdktf/lib/util.ts
> fix(lib): override values containing intrinsic tokens caused an infinite loop

- packages/cdktf-cli/lib/init.ts
- packages/cdktf-cli/templates/csharp/cdktf.json
- packages/cdktf-cli/templates/go/cdktf.json
- packages/cdktf-cli/templates/java/cdktf.json
- packages/cdktf-cli/templates/python-pip/cdktf.json
- packages/cdktf-cli/templates/python/cdktf.json
- packages/cdktf-cli/templates/typescript/.hooks.sscaff.js
- packages/cdktf-cli/templates/typescript/cdktf.json
> fix(cli): fix templates to properly indent cdktf.json and add RemoteBackend in TS template

- .github/workflows/release.yml
- .github/workflows/release_next.yml
- packages/cdktf-cli/bin/cmds/helper/check-environment.ts
- packages/cdktf-cli/templates/go/.hooks.sscaff.js
- website/data/cdktf-nav-data.json
- website/docs/cdktf/create-and-deploy/environment-variables.mdx
This env var could be helpful in case of bugs in the version detection
> chore(cli): add environment variable to disable version checks

- CHANGELOG.md
- packages/cdktf-cli/lib/synth-stack.ts
- test/typescript/synth-app/__snapshots__/test.ts.snap
- test/typescript/synth-app/main.ts
- test/typescript/synth-app/test.ts
> feat(cli): filter TF_VAR_ environment variables during synth phase

- .github/workflows/release.yml
> feat(release): support running releases on backport-release branches besides only on main

- CHANGELOG.md
- packages/cdktf/lib/terraform-stack.ts
> fix(cli): throw an error if a stack contains a whitespace

- packages/cdktf-cli/lib/error-reporting.ts
Currently we send usage errors as well, like the version check of no cdktf.json file found
> chore(cli): filter usage errors from error reporting

- .github/workflows/integration.yml
- .github/workflows/provider-integration.yml
- packages/@cdktf/provider-generator/.gitignore
- test/.gitignore
- test/package.json
- test/provider-tests/README.md
- test/provider-tests/generate-provider-test.js
- test/provider-tests/providers.json
- test/provider-tests/template/cdktf.json
- test/provider-tests/template/main.ts
- test/provider-tests/template/test.js
- test/provider-tests/template/test.ts
- test/provider-tests/test-provider.bat
- test/provider-tests/test-provider.sh
- test/typescript/providers/main.ts
- test/typescript/providers/test.ts
- tools/build-provider-test-matrix.sh
- tools/build-test-matrix.sh
- yarn.lock
They are only triggered if something in the provider generator changes
> chore: split provider tests into one test per provider

- test/csharp/provider-add-command/test.ts
> chore(tests): Re-enable Windows Provider Add C# Test

- CONTRIBUTING.md
- found a "`" which wasn't closed in the contributing.md hence opened this PR
> fix: Small fix to the CONTRIBUTING.md

- packages/cdktf-cli/bin/cmds/synth.ts
> fix(cli): remove synth positional

- packages/cdktf-cli/bin/cdktf.ts
> fix(cli): don't go into error mode when accessing the completion script

- packages/cdktf-cli/lib/synth-stack.ts
> fix(cli): increase default max memory for node process when running app command for synth

- packages/cdktf-cli/lib/dependencies/dependency-manager.ts
- packages/cdktf-cli/test/lib/dependencies/dependency-manager.test.ts
> chore(cli): throw an error on provider add if no provider version is found

- website/docs/cdktf/api-reference/overview.mdx
A few tiny updates to the new API reference overview page :)
> chore(docs): Update overview.mdx

- CHANGELOG.md
- packages/cdktf/lib/terraform-functions.ts
- packages/cdktf/lib/tokens/resolvable.ts
- packages/cdktf/test/functions.test.ts
- test/python/terraform-functions/main.py
- tools/documentation-generation/package.json
- tools/documentation-generation/yarn.lock
- website/docs/cdktf/api-reference/csharp.mdx
- website/docs/cdktf/api-reference/go.mdx
- website/docs/cdktf/api-reference/java.mdx
- website/docs/cdktf/api-reference/python.mdx
- website/docs/cdktf/api-reference/typescript.mdx
- website/docs/cdktf/concepts/stacks.mdx
This gives us better bindings for the two use-cases and the result can be directly used
> fix(lib): split merge into merge maps and merge lists

- website/README.md
A couple of extras from the work we did on Plugin that I think are useful here as well :) Updating for extra clarity and consistency across products!
> chore(docs): Additional Docs README Updates

- website/data/cdktf-nav-data.json
- website/docs/cdktf/concepts/iterators.mdx
To be merged after https://github.com/hashicorp/terraform-cdk/pull/1830 has been merged and is about to be released.
Is the position in the sidebar (below functions) a good place? Feel free to move to a better fitting position.
> feat(docs): Add iterator docs page

- website/docs/cdktf/concepts/iterators.mdx
- feat(docs): add docs for block level iteration
> feat(docs): add docs for block level iteration

- website/docs/cdktf/concepts/resources.mdx
Oops! The main header should be H1, not H2 :)
> chore(docs): Update resources.mdx

- packages/cdktf-cli/lib/synth-stack.ts
Closes https://github.com/hashicorp/terraform-cdk/issues/2008
> fix: don't overwrite all `NODE_OPTIONS`

- packages/cdktf-cli/lib/cdktf-stack.ts
> fix(cli): run a speculative plan on diff

- packages/cdktf/lib/validations/validate-provider-presence.ts
- packages/cdktf/test/app.test.ts
- packages/cdktf/test/stack.test.ts
> fix(lib): Improve error message when provider constructs are missing

- CHANGELOG.md
- packages/@cdktf/provider-generator/lib/get/constructs-maker.ts
- packages/cdktf-cli/bin/cmds/get.ts
- packages/cdktf-cli/bin/cmds/handlers.ts
- packages/cdktf-cli/bin/cmds/ui/get.tsx
- website/docs/cdktf/cli-reference/commands.mdx
This should speed up cdktf get for all languages except TS 🎉
> feat(cli): support generating provider bindings in parallel

- cdk.tf/vercel.json
> **Warning**
> (currently uses a placeholder issue)
> chore: Add redirect to incoming github issue

- cdk.tf/vercel.json
In preparation for #2173, blocks #2181
> feat: add redirect link to pre-built providers json file

- packages/cdktf-cli/bin/cmds/ui/list.tsx
> fix(cli): dont wrap list terminal output

- packages/cdktf-cli/src/lib/dependencies/prebuilt-providers.ts
- packages/cdktf-cli/src/test/lib/cdktf-project.test.ts
- packages/cdktf-cli/src/test/lib/dependencies/prebuilt-providers.test.ts
Resolves #2173, ~~but depends on #2180~~
> chore(cli): change url to pre-built providers to one we control

- website/docs/cdktf/concepts/resources.mdx
Fixing a broken link - thank you!
> fix(docs): fix link

- .github/workflows/docker.yml
- .github/workflows/examples.yml
- .github/workflows/integration.yml
- .github/workflows/provider-integration.yml
- .github/workflows/release.yml
- .github/workflows/release_next.yml
- .github/workflows/unit.yml
- .github/workflows/update-snapshots.yml
- .github/workflows/website.yml
- .github/workflows/yarn-upgrade.yml
- tools/build-provider-test-matrix.sh
- tools/build-test-matrix.sh
- tools/build-unit-test-matrix.sh
Brought to you by the worst and dumbest code I have ever written :D https://github.com/DanielMSchmidt/github-action-output-migration-tool
> chore: migrate to new github output syntax

- packages/cdktf-cli/src/lib/models/terraform-cloud.ts
- packages/cdktf-cli/src/test/models/terraform-cloud.test.ts
Closes: https://github.com/hashicorp/terraform-cdk/issues/2233
> fix: Redact authorization header when error logging from TFC/TFE

- CHANGELOG.md
- package.json
- packages/cdktf-cli/src/lib/models/terraform-cloud.ts
- packages/cdktf-cli/src/test/models/terraform-cloud.test.ts
- test/typescript/feature-flags/__snapshots__/test.ts.snap
- fix: Redact authorization header when error logging from TFC/TFE [#2241](https://github.com/hashicorp/terraform-cdk/pull/2241)
> chore(release): Version 0.13.3

- website/docs/cdktf/concepts/modules.mdx
> fix(docs): fix module code example

- .github/CODEOWNERS
> chore: adding mgarrell777 to docs codeowners to be notified for docs changes

- packages/cdktf/lib/testing/__tests__/matchers.test.ts
- packages/cdktf/lib/testing/adapters/__tests__/jest.test.ts
- packages/cdktf/lib/testing/index.ts
- packages/cdktf/lib/testing/matchers.ts
- packages/cdktf/test/helper/provider.ts
- test/csharp/testing-matchers/TestProgram.cs
- test/go/testing-matchers/main_test.go
- test/java/testing-matchers/MainTest.java
- test/java/testing-matchers/test.ts
- test/python/testing-matchers/test.ts
- test/python/testing-matchers/test_assertions.py
- website/docs/cdktf/test/unit-tests.mdx
> feat(lib): Added testing matchers for Providers

- packages/@cdktf/provider-generator/lib/get/constructs-maker.ts
- packages/@cdktf/provider-generator/lib/util.ts
> fix(provider-generator): fix cross package import which breaks the cdktf-cli release bundle

- test/go/provider-add-command/test.ts
- test/go/provider-upgrade-command/test.ts
> chore(tests): enable go provider add tests

- .github/workflows/examples-pr.yml
- .github/workflows/examples.yml
- .github/workflows/integration-pr.yml
- .github/workflows/integration.yml
- .github/workflows/release.yml
- .github/workflows/release_next.yml
- .github/workflows/unit-@cdktf-hcl2cdk.yml
- .github/workflows/unit-@cdktf-hcl2json.yml
- .github/workflows/unit-@cdktf-provider-generator.yml
- .github/workflows/unit-all.yml
- .github/workflows/unit-cdktf-cli.yml
- .github/workflows/unit-cdktf.yml
- chore: offboard checks from PRs to main
- chore: fix typo
> chore: fix typo

- examples/csharp/documentation/FunctionStack.cs
- examples/csharp/documentation/Main.cs
- examples/csharp/documentation/MyTerraformStack.csproj
- website/docs/cdktf/concepts/functions.mdx
re: #1929
Please look at https://github.com/hashicorp/terraform-cdk/pull/2275 first :)
> chore(docs): translate functions examples to c#

- examples/csharp/documentation/DataSources.cs
- examples/csharp/documentation/Main.cs
- examples/csharp/documentation/RemoteStateDataSources.cs
- website/docs/cdktf/concepts/data-sources.mdx
re: #1929
Please look at https://github.com/hashicorp/terraform-cdk/pull/2275 first :)
> chore(docs): translate data-sources examples to c#

- examples/csharp/documentation/AspectsStack.cs
- examples/csharp/documentation/AspectsValidationStack.cs
- examples/csharp/documentation/Main.cs
- examples/csharp/documentation/MyTerraformStack.csproj
- website/docs/cdktf/concepts/aspects.mdx
> chore(docs): translate aspects example to c#

- website/docs/cdktf/concepts/remote-backends.mdx
The tiniest update to fix the note format. Currently, it doesn't render correctly on the doc site :)
> chore(docs): Update remote-backends.mdx

- packages/@cdktf/cli-core/src/lib/models/terraform-cloud.ts
Rebasing @daniel-laszlo PR (#2243)
> fix: Transition to planned state after cost estimation and policy checks with TFC/TFE

- examples/python/upcloud-server/.gitignore
- examples/python/upcloud-server/Pipfile
- examples/python/upcloud-server/Pipfile.lock
- examples/python/upcloud-server/README.md
- examples/python/upcloud-server/cdktf.json
- examples/python/upcloud-server/help
- examples/python/upcloud-server/main.py
- examples/python/upcloud-server/package.json
- feat(examples): add upcloud-server python example
- chore(examples): run prettier
supersedes #2239 as I can't push to that branch to rebase & fix lint 😇
> feat(examples): python upcloud server

- website/docs/cdktf/create-and-deploy/terraform-cloud.mdx
Relates to #2208
The ticket talks about a task-based guide, but the page already feels kind of task-related to me, what do you think?
> chore: add TFE information to TFC docs

- .github/workflows/release_next.yml
Fixes: https://github.com/hashicorp/terraform-cdk/actions/runs/3703069032
> fix: Allow git access for sentry cli in docker

- .github/workflows/gh-action-upgrade.yml
See saadmk11/github-actions-version-updater#49 for details
> chore: fix broken GHA version updater

- packages/cdktf-cli/src/bin/cmds/helper/terraform-cloud-client.ts
- packages/cdktf-cli/src/test/cmds/helper/terraform-cloud-client.test.ts
Fixes: https://github.com/hashicorp/terraform-cdk/issues/1893
> chore: Support custom endpoints

- packages/cdktf-cli/src/bin/cmds/handlers.ts
> fix(cli): remove newlines from tokens during terraform login

- packages/@cdktf/cli-core/src/lib/models/__tests__/deploy-machine.test.ts
- packages/@cdktf/cli-core/src/lib/models/deploy-machine.ts
> fix: detect destroys on windows / TF version

- website/docs/cdktf/cli-reference/commands.mdx
- website/docs/cdktf/concepts/variables-and-outputs.mdx
- chore: update help text
- chore: document -var flag
> chore: document variable flags

- CHANGELOG.md
- website/docs/cdktf/create-and-deploy/configuration-file.mdx
- website/docs/cdktf/release/upgrade-guide-v0-15.mdx
> chore: deprecate feature flags

- packages/@cdktf/provider-generator/lib/get/generator/emitter/attributes-emitter.ts
- packages/cdktf/lib/terraform-resource.ts
- test/provider-tests/providers.json
> fix(provider-generator): use class based map abstractions

- packages/cdktf/lib/backends/cloud-backend.ts
> fix(lib): don't use Fn.set on tagged cloud backend

- .github/workflows/release.yml
We were asked to leave a commit body: https://github.com/Homebrew/homebrew-core/pull/121397#issuecomment-1401919619
> chore: fill out homebrew pr body

- .github/workflows/gh-action-upgrade.yml
#2505 was well-intentioned but didn't work! Hopefully this does.
> chore: actually autoclose older GHA updater PRs

- packages/cdktf-cli/src/bin/cmds/__tests__/handlers-login.test.ts
- packages/cdktf-cli/src/bin/cmds/handlers.ts
fixes: https://github.com/hashicorp/terraform-cdk/issues/2538
> fix: cdktf login issues

- packages/cdktf-cli/src/bin/cmds/convert.ts
- packages/cdktf-cli/src/bin/cmds/handlers.ts
- packages/cdktf-cli/src/bin/cmds/helper/wrap-in-stack.ts
- packages/cdktf-cli/templates/convert/stack.cs
- packages/cdktf-cli/templates/convert/stack.java
- packages/cdktf-cli/templates/convert/stack.py
- packages/cdktf-cli/templates/convert/stack.ts
- website/docs/cdktf/cli-reference/commands.mdx
I wanted to have generated code that could be imported and run without any additional steps, so I created an extra flag for wrapping convert in a stack.
> feat: Add a wrap in stack optional param to cdktf convert

- website/docs/cdktf/concepts/cdktf-architecture.mdx
- website/docs/cdktf/concepts/resources.mdx
> fix(docs): fix links to examples page

- examples/csharp/documentation/ReferencesStack.cs
- examples/csharp/documentation/TerraformHclModuleStack.cs
- examples/go/documentation/modules.go
- examples/go/documentation/resources-references.go
- examples/go/documentation/resources.go
- examples/java/documentation/src/main/java/com/mycompany/app/modules/MainCreateModules.java
- examples/java/documentation/src/main/java/com/mycompany/app/resources/MainResources.java
- examples/python/documentation/modules.py
- examples/python/documentation/resources.py
- examples/typescript/documentation/modules.ts
- website/docs/cdktf/concepts/modules.mdx
- website/docs/cdktf/concepts/remote-backends.mdx
- website/docs/cdktf/concepts/resources.mdx
Addressing review feedback from @mutahhir in #2560 (which was raced by me merging on the first review 😄)
> fix(docs): Go post mortem review feedback

- examples/go/documentation/cdktf.json
- examples/go/documentation/iterators.go
- examples/go/documentation/main.go
- examples/go/documentation/myconstructs/docker-backend.go
- examples/go/documentation/myconstructs/vpc.go
- examples/go/documentation/stacks-cross-reference.go
- examples/go/documentation/stacks-dependencies.go
- examples/go/documentation/stacks-multiple.go
- examples/go/documentation/stacks-single.go
- examples/go/documentation/tokens.go
- website/docs/cdktf/concepts/iterators.mdx
- website/docs/cdktf/concepts/stacks.mdx
- website/docs/cdktf/concepts/tokens.mdx
> feat(docs): Translate more examples to Go

- packages/@cdktf/provider-generator/lib/get/generator/custom-defaults.ts
Fixes #2388 
Pulled in some other updates as well.
> fix(lib): Update special defaults

- packages/@cdktf/cli-core/src/lib/cdktf-stack.ts
- packages/@cdktf/cli-core/src/lib/terraform-provider-lock.ts
- packages/@cdktf/cli-core/src/test/lib/terraform-provider-lock.test.ts
Step 1 in trying to improve our `cdktf plan/apply/destroy` running `terraform init`. Will base other PRs on top of this one.
> chore: refactor 'needs upgrade'

- examples/csharp/documentation/ProviderClassesStack.cs
- examples/go/documentation/providers.go
- examples/java/documentation/src/main/java/com/mycompany/app/providers/MainImportClasses.java
- examples/python/documentation/providers.py
- examples/typescript/documentation/providers.ts
- website/docs/cdktf/concepts/providers.mdx
> fix(docs): remove exposed secrets in provider snippets

- .github/SUPPORT.md
Only just discovered these are a thing when looking for pull request template ideas. Figured this is a useful thing to add.
> chore: add SUPPORT.md

- examples/java/documentation/src/main/java/com/mycompany/app/stacks/MainStacks.java
- examples/python/documentation/stacks.py
- examples/typescript/documentation/stacks.ts
- website/docs/cdktf/concepts/stacks.mdx
> fix(docs): fix stack escape hatch override example for TS, Python, and Java

- examples/java/documentation/cdktf.json
- examples/java/documentation/src/main/java/com/mycompany/app/MainIterator.java
- website/docs/cdktf/concepts/iterators.mdx
> fix(docs): source java iterator snippets from examples

- packages/cdktf/lib/backends/artifactory-backend.ts
- packages/cdktf/lib/backends/azurerm-backend.ts
- packages/cdktf/lib/backends/cloud-backend.ts
- packages/cdktf/lib/backends/consul-backend.ts
- packages/cdktf/lib/backends/cos-backend.ts
- packages/cdktf/lib/backends/etcd-backend.ts
- packages/cdktf/lib/backends/etcdv3-backend.ts
- packages/cdktf/lib/backends/gcs-backend.ts
- packages/cdktf/lib/backends/http-backend.ts
- packages/cdktf/lib/backends/local-backend.ts
- packages/cdktf/lib/backends/s3-backend.ts
- packages/cdktf/lib/terraform-iterator.ts
- packages/cdktf/lib/terraform-provisioner.ts
- packages/cdktf/lib/terraform-variable.ts
- packages/cdktf/lib/tfExpression.ts
- website/docs/cdktf/api-reference/csharp.mdx
- website/docs/cdktf/api-reference/go.mdx
- website/docs/cdktf/api-reference/java.mdx
- website/docs/cdktf/api-reference/python.mdx
- website/docs/cdktf/api-reference/typescript.mdx
- fix(lib): Update old terraform.io links
- chore(docs): update API docs
> fix(lib): Update old terraform.io links

- packages/@cdktf/provider-generator/package.json
- yarn.lock
Fixes CI issues
I somehow missed this, and this was causing all the weirdness. I am still seeing some issues from Java, but I'll investigate that after this merge.
> chore: update jsii-srcmak in provider-generator

- packages/@cdktf/cli-core/src/lib/models/deploy-machine.ts
> fix(cli): remove extra quotes

- examples/csharp/documentation/CrossStackReferenceStack.cs
- examples/csharp/documentation/MyTerraformStack.csproj
- examples/java/documentation/src/main/java/com/mycompany/app/stacks/MainStacks.java
- packages/cdktf/package.json
- tools/build-example.js
- yarn.lock
> chore: Reduce warnings to get to the bottom of documentation issues

- website/docs/cdktf/release/upgrade-guide-v0-15.mdx
> fix(docs): fix typo in upgrade-guide-v0-15.mdx

- packages/@cdktf/hcl2json/lib/index.ts
- packages/@cdktf/hcl2json/lib/syntax-tree.ts
This adds a better, more complete types for the Terraform Expression AST.
> chore: Add tree traversal, and better types for terraform expression AST

- examples/java/gradle-shared-module/package.json
#2759 was created to track re-enabling this at some point in the future.
> chore(examples): Disable Java Gradle example

- examples/java/gradle-shared-module/package.json
- packages/@cdktf/hcl2cdk/lib/__tests__/expressions.test.ts
- packages/@cdktf/hcl2cdk/lib/expressions.ts
- packages/@cdktf/hcl2cdk/lib/function-bindings/functions.ts
- packages/@cdktf/hcl2cdk/lib/generation.ts
- packages/@cdktf/hcl2cdk/lib/index.ts
- packages/@cdktf/hcl2cdk/lib/types.ts
- packages/@cdktf/hcl2cdk/test/__snapshots__/iteration.test.ts.snap
- packages/@cdktf/hcl2cdk/test/__snapshots__/references.test.ts.snap
- packages/@cdktf/hcl2cdk/test/__snapshots__/resource-meta-properties.test.ts.snap
- packages/@cdktf/hcl2cdk/test/__snapshots__/resources.test.ts.snap
- packages/@cdktf/hcl2cdk/test/__snapshots__/typeCoercion.test.ts.snap
- packages/@cdktf/hcl2cdk/test/expressionToTs.test.ts
- packages/@cdktf/hcl2cdk/test/findExpressionType.test.ts
- packages/@cdktf/hcl2cdk/test/helpers/convert.ts
- packages/@cdktf/hcl2cdk/test/iteration.test.ts
- packages/@cdktf/hcl2cdk/test/references.test.ts
- packages/cdktf/lib/index.ts
- packages/cdktf/lib/terraform-count.ts
- packages/cdktf/lib/terraform-data-source.ts
- packages/cdktf/lib/terraform-resource.ts
- packages/cdktf/test/iterator.test.ts
Due to the recent TF expression AST work, we have had to re-adapt the recent iterator work from https://github.com/hashicorp/terraform-cdk/pull/2732 to work with the new AST conversion.
> chore: Make iterators working again with convert

- .github/workflows/release.yml
Fixes https://github.com/hashicorp/terraform-cdk/actions/runs/4686510942/jobs/8304683229
> chore: add chown to release process

- packages/@cdktf/cli-core/src/lib/dependencies/dependency-manager.ts
- packages/@cdktf/cli-core/src/test/lib/dependencies/dependency-manager.test.ts
- packages/cdktf-cli/src/bin/cmds/helper/init.ts
- fix(cli): fix version constraint for Terraform provider including space
- test(cli): add test for spaces in rendered provider constraints
Resolves #1883
> fix(cli): fix version constraint for Terraform provider including space

- examples/csharp/documentation/IteratorStack.cs
- examples/go/documentation/iterators.go
- examples/java/documentation/src/main/java/com/mycompany/app/MainIterator.java
- examples/python/documentation/iterators.py
- examples/typescript/documentation/iterators-count.ts
- examples/typescript/documentation/main.ts
- website/docs/cdktf/concepts/iterators.mdx
- website/docs/cdktf/concepts/providers.mdx
> feat(docs): Add example for TerraformCount to iterators.mdx

- packages/@cdktf/cli-core/src/lib/cdktf-project.ts
- packages/@cdktf/cli-core/src/lib/cdktf-stack.ts
- packages/@cdktf/cli-core/src/lib/dependencies/package-manager.ts
- packages/@cdktf/cli-core/src/lib/init.ts
- packages/@cdktf/cli-core/src/lib/local-provider-constraints.ts
- packages/@cdktf/cli-core/src/lib/local-provider-versions.ts
- packages/@cdktf/cli-core/src/lib/watch.ts
- packages/@cdktf/commons/src/errors.ts
- packages/@cdktf/commons/src/terraform.ts
- packages/cdktf-cli/src/bin/cmds/handlers.ts
- packages/cdktf-cli/src/bin/cmds/helper/init.ts
> fix(cli): run terraform init in serial so no text file is busy in the cache

- examples/go/google-cloudrun/main_test.go
- packages/@cdktf/cli-core/templates/go/main_test.go
- packages/cdktf-cli/templates/go/main_test.go
- website/docs/cdktf/test/unit-tests.mdx
> fix(cli): fix template for Go unit tests

- website/docs/cdktf/develop-custom-constructs/publishing-and-distribution.mdx
Fixes a typo in the "Publishing and Distribution" document.
> fix: website typo

- package.json
- packages/cdktf/lib/app.ts
- packages/cdktf/lib/tfExpression.ts
- packages/cdktf/lib/validations/index.ts
- packages/cdktf/lib/validations/validate-backends.ts
- packages/cdktf/package.json
- packages/cdktf/test/app.test.ts
- tools/documentation-generation/yarn.lock
- website/docs/cdktf/api-reference/csharp.mdx
- website/docs/cdktf/api-reference/go.mdx
- website/docs/cdktf/api-reference/java.mdx
- website/docs/cdktf/api-reference/python.mdx
- website/docs/cdktf/api-reference/typescript.mdx
depends on #2591
- fix(lib): fix cause for circular dependency in tests when importing app
- feat(lib): Add validation for accidental backend reuse
> feat(lib): Add validation against accidental backend reuse

- examples/csharp/documentation/package.json
- examples/go/documentation/package.json
- examples/java/documentation/package.json
- examples/python/documentation/package.json
- examples/typescript/documentation/package.json
- packages/cdktf-cli/package.json
- packages/cdktf-cli/src/bin/cmds/get.ts
- packages/cdktf-cli/src/bin/cmds/handlers.ts
- packages/cdktf-cli/src/bin/cmds/helper/performance.ts
- tools/build-example.js
- yarn.lock
These commands take often some time and space, the flag will help us measure improvements
> feat(cli): add flag to display memory / time used for get and synth

- .github/workflows/pr-labels.yml
It did not help us in the way we thought it would, the comments are annoying, let's get rid of it.
> chore: remove PR sizing

- packages/cdktf/lib/terraform-resource.ts
This was solved in #2375 already
Closes #2532
> chore: remove legacy comment

- CHANGELOG.md
- package.json
- website/docs/cdktf/api-reference/csharp.mdx
- website/docs/cdktf/api-reference/go.mdx
- website/docs/cdktf/api-reference/java.mdx
- website/docs/cdktf/api-reference/python.mdx
- website/docs/cdktf/api-reference/typescript.mdx
- website/docs/cdktf/release/upgrade-guide-v0-17.mdx
- feat(provider-generator): allow removing big, cost intensive structures [\#2932](https://github.com/hashicorp/terraform-cdk/pull/2932)
- feat(cli): add flag to display memory / time used for get and synth [\#2914](https://github.com/hashicorp/terraform-cdk/pull/2914)
- feat(cli): Improve telemetry reporting [\#2840](https://github.com/hashicorp/terraform-cdk/pull/2840)
- feat: make testing more resilient towards usage with app.synth [\#2762](https://github.com/hashicorp/terraform-cdk/pull/2762)
- feat(provider-generator): Add docstring to main class generated for modules [\#2589](https://github.com/hashicorp/terraform-cdk/pull/2589)
- fix(cli): exit ink app when done synthesizing [\#2933](https://github.com/hashicorp/terraform-cdk/pull/2933)
- fix(lib): Support Computed …
> chore: release 0.17

- test/typescript/init-from-tf/__snapshots__/test.ts.snap
> fix(tests): update integration test snapshot

- packages/cdktf-cli/src/test/cmds/init.test.ts
I missed adding a regression test for the issue fixed in #2977. This PR adds that.
> chore: Add regression test for input on init

- examples/README.md
> chore: fix link to examples

- packages/@cdktf/cli-core/src/lib/get.ts
- packages/@cdktf/provider-generator/lib/get/constructs-maker.ts
- packages/cdktf-cli/src/bin/cmds/ui/get.tsx
I was tracing some possible error (which turned out to not exist) and improved these types along the way.
> chore: clean up code a bit

- packages/@cdktf/hcl2cdk/test/__snapshots__/tfExpressions.test.ts.snap
- packages/@cdktf/hcl2cdk/test/tfExpressions.test.ts
- packages/@cdktf/hcl2json/lib/bridge.ts
- packages/@cdktf/hcl2json/lib/util.ts
wrapping single quoted strings is required
Resolves #2913
> fix: fix single quote escaping

- .github/workflows/cdktf-provider-docs-rollout.yml
- .github/workflows/registry-docs-pr-based.yml
Latest run: https://github.com/hashicorp/terraform-cdk/actions/runs/5688936110
> chore: add workflow to rollout provider documentation

- examples/typescript/aws-cloudfront-proxy/main.ts
- examples/typescript/aws-kubernetes/main.ts
- examples/typescript/aws-prebuilt/main.ts
- examples/typescript/azure-service-bus-queue-trigger/main.ts
- examples/typescript/azure-service-bus-queue-trigger/package.json
- yarn.lock
Related to this comment: https://github.com/hashicorp/terraform-cdk/pull/2857\#issuecomment-1667561648
> chore(examples): update TS examples to use explicit imports

- test/java/edge/test.ts
The goal of this PR is to get the java/edge tests green
> chore: fix assertion of java tests

- .github/workflows/integration.yml
> chore: Disable windows integration tests temporarily

- packages/@cdktf/cli-core/src/lib/cdktf-stack.ts
Fixes #3120 
Updates spelling for a typo, which is quite prevalent
> chore(cli): fixes typo (#3120)

- packages/@cdktf/cli-core/templates/typescript/help
> fix(cli): fix help template spelling

- packages/@cdktf/cli-core/package.json
- test/package.json
- test/yarn.lock
- yarn.lock
> chore: upgrade node-pty dependency to add support for Node.js 20

- CHANGELOG.md
- test/java/edge/cdktf.json
- test/java/no-color-command-option-test/cdktf.json
- test/java/provider-add-command/cdktf.json
- test/java/provider-list-command/cdktf.json
- test/java/provider-upgrade-command/cdktf.json
- test/java/synth-app/cdktf.json
- test/java/testing-matchers/cdktf.json
they need codeMakerOutputs as well
> chore: fix java integration tests

- packages/@cdktf/cli-core/package.json
- packages/@cdktf/hcl2cdk/package.json
- packages/cdktf-cli/package.json
- yarn.lock
> chore: update zod

- .github/workflows/pr-depcheck.yml
- packages/@cdktf/commons/package.json
- yarn.lock
Splitting up  #3202 to integrate it step by step
> chore: dependency check commons package

- .github/workflows/examples-pr.yml
- .github/workflows/pr-integration.yml
- .github/workflows/pr-provider-integration.yml
- .github/workflows/pr-unit.yml
Part of the Merge queue running the required checks, Github UI is still not picking up the results job so try 2
> fix: Use unique names to see if Github filters can pick it up

- website/docs/cdktf/concepts/stacks.mdx
> chore: remove reference to mergeLists

- packages/cdktf-cli/src/bin/cmds/helper/init.ts
Follow up on #3207 where prettier was missing :) 
Closes #3207
Fixes #2982
> fix(cli): error message for non-existent tf cloud orgs

- examples/typescript/aws-move/main.ts
- packages/cdktf/lib/index.ts
- packages/cdktf/lib/synthesize/synthesizer.ts
- packages/cdktf/lib/terraform-resource.ts
- packages/cdktf/lib/terraform-stack.ts
- packages/cdktf/lib/upgrade-id-aspect.ts
- packages/cdktf/test/resource.test.ts
- website/docs/cdktf/examples-and-guides/refactoring.mdx
- website/docs/cdktf/release/upgrade-guide-v0-17.mdx
For patch of move workflow: https://github.com/hashicorp/terraform-cdk/pull/3231
> feat(lib): move workflow patch

- CHANGELOG.md
- package.json
- feat(lib): add move workflows for specifying ids directly [\#3231](https://github.com/hashicorp/terraform-cdk/pull/3231)
> chore: release 0.19.2

- packages/@cdktf/provider-schema/src/__tests__/__snapshots__/provider-schema.test.ts.snap
- packages/@cdktf/provider-schema/src/__tests__/provider-schema.test.ts
> chore(tests): re-enable provider schema tests

- packages/cdktf/lib/complex-computed-list.ts
- packages/cdktf/test/iterator.test.ts
- test/typescript/iterators/main.ts
- website/docs/cdktf/api-reference/csharp.mdx
- website/docs/cdktf/api-reference/go.mdx
- website/docs/cdktf/api-reference/java.mdx
- website/docs/cdktf/api-reference/python.mdx
- website/docs/cdktf/api-reference/typescript.mdx
This allows easier access to iterating over a list type property.
Close #1869
> feat(lib): add `.allWithMapKey` iterator to lists

- examples/go/documentation/remote-backend.go
- examples/go/documentation/remote-state.go
- packages/cdktf/lib/backends/azurerm-backend.ts
- packages/cdktf/lib/backends/cloud-backend.ts
- packages/cdktf/lib/backends/cos-backend.ts
- packages/cdktf/lib/backends/gcs-backend.ts
- packages/cdktf/lib/backends/http-backend.ts
- packages/cdktf/lib/backends/oss-backend.ts
- packages/cdktf/lib/backends/pg-backend.ts
- packages/cdktf/lib/backends/s3-backend.ts
- website/docs/cdktf/api-reference/csharp.mdx
- website/docs/cdktf/api-reference/go.mdx
- website/docs/cdktf/api-reference/java.mdx
- website/docs/cdktf/api-reference/python.mdx
- website/docs/cdktf/api-reference/typescript.mdx
- website/docs/cdktf/concepts/remote-backends.mdx
- website/docs/cdktf/concepts/variables-and-outputs.mdx
Updating all backend options the the latest and greatest. This includes the project option in the cloud block, which we treat as a backend. 
Closes #3349 
Closes #2705
Closes #2704 
Closes #2703
> feat(lib): update backend options

- examples/python/documentation/aspects.py
- website/docs/cdktf/concepts/aspects.mdx
> chore: fix aspects documentation

- .github/workflows/release.yml
- .github/workflows/release_next.yml
jsii-release is the old, deprecated name
> chore: use publib for releases

- test/python/provider-add-command/test.ts
- test/python/provider-upgrade-command/test.ts
- test/test-helper.ts
Installing packages requires a non-root environment
> chore: run python tests in virtual env

- .github/workflows/release.yml
- .github/workflows/release_next.yml
Also GH Action does not work with source, you need to use the . syntax
> chore: activate virtual env in same shell

- .github/workflows/release_next.yml
> chore: set include-system-site-packages=true for python release

- examples/csharp/documentation/IteratorStack.cs
- examples/go/documentation/iterators.go
- examples/java/documentation/src/main/java/com/mycompany/app/MainIterator2.java
- examples/python/documentation/iterators.py
- examples/typescript/documentation/iterators.ts
- website/docs/cdktf/concepts/iterators.mdx
> fix(docs): fix complex iterator example

- packages/cdktf/lib/terraform-provisioner.ts
- packages/cdktf/test/__snapshots__/terraform-provisioner.test.ts.snap
- packages/cdktf/test/terraform-provisioner.test.ts
- website/docs/cdktf/concepts/iterators.mdx
> fix(lib): support dot-seperated nested accessors

- examples/csharp/documentation/CrossStackReferenceStack.cs
- examples/csharp/documentation/Main.cs
- examples/csharp/documentation/StackDependenciesStack.cs
- examples/python/documentation/stacks.py
- examples/typescript/documentation/stacks.ts
- tools/documentation-generation/yarn.lock
- website/docs/cdktf/concepts/stacks.mdx
Fixes #2579
We try to ensure that all the code that goes into our documentation is synthesizable. However, we found some areas where we weren't doing that, and this PR addresses some of those areas.
> chore(docs): update stacks documentation

- packages/cdktf/lib/hcl/render.ts
- packages/cdktf/test/helper/resource.ts
- packages/cdktf/test/json-to-hcl.test.ts
> fix: hcl rendering nested maps

- examples/csharp/documentation/IteratorStack.cs
- examples/go/documentation/iterators.go
- examples/java/documentation/src/main/java/com/mycompany/app/MainIterator2.java
- examples/python/documentation/iterators.py
- examples/typescript/documentation/iterators.ts
- tools/documentation-generation/yarn.lock
- website/docs/cdktf/concepts/iterators.mdx
> chore: fix typo in aws certifacate iterator key

- packages/cdktf/lib/errors.ts
- packages/cdktf/lib/terraform-module.ts
- packages/cdktf/test/__snapshots__/terraform-module.test.ts.snap
- packages/cdktf/test/app.test.ts
- packages/cdktf/test/resource.test.ts
- packages/cdktf/test/stack.test.ts
- packages/cdktf/test/terraform-module.test.ts
- packages/cdktf/test/validations.test.ts
- website/docs/cdktf/api-reference/csharp.mdx
- website/docs/cdktf/api-reference/go.mdx
- website/docs/cdktf/api-reference/java.mdx
- website/docs/cdktf/api-reference/python.mdx
- website/docs/cdktf/api-reference/typescript.mdx
- yarn.lock
> feat: add validation to TerraformModule

- packages/cdktf/lib/hcl/render.ts
- packages/cdktf/test/helper/module.ts
- packages/cdktf/test/json-to-hcl.test.ts
> fix: Empty string, booleans, and zero numbers in hcl rendering

- packages/@cdktf/hcl2cdk/README.md
- packages/@cdktf/hcl2json/README.md
- packages/@cdktf/provider-generator/README.md
Fixes # 
`yarn install` is for installing existing packages, `yarn add` is for adding a new package.
> chore(hcl2cdk): fix yarn command in Readme.md

- .github/workflows/registry-docs-pr-based.yml
> chore: increase time the docs conversion might take

- .github/workflows/registry-docs-pr-based.yml
> chore: update version of docs conversion tool

- package.json
> chore: release 0.20.11

- Dockerfile
Pulling this out of the WIP PR: https://github.com/hashicorp/terraform-cdk/pull/3819 because I want to be able to run a later version of Node to proceed with building the other PR.
> chore: Update docker container with latest version of node and JSII

- website/docs/cdktf/concepts/remote-backends.mdx
We had already updated the Remote backends documentation to use the Cloud backend, but overlooked the paragraphs following the updated example code. This PR updates that to be more accurate.
> chore(docs): Update example for remote backend to show cloud backend

- package.json
- packages/@cdktf/cli-core/package.json
- yarn.lock
Upgrading latest version of @cdktf/node-pty-prebuilt-multiarch
> chore: Upgrade node-pty-prebuilt to support Node LTS

- Dockerfile
In preparation for updating the minimum version of Node supported by CDKTF to Node 20, this PR updates the base docker image to the one with Node 20 support
> chore: Upgrade base image for docker image used in building CDKTF
