hashicorp/terraform-cdk

examples/typescript-google/.gitignore, examples/typescript-google/Readme.md, examples/typescript-google/cdktf.json, examples/typescript-google/help, examples/typescript-google/main.ts, examples/typescript-google/package.json, examples/typescript-google/tsconfig.json, yarn.lock
This adds an example for the Google Cloud based on the [Hashicorp Learn](https://learn.hashicorp.com/terraform/gcp/build) guide.
Fixes https://github.com/hashicorp/terraform-cdk/issues/175
=> Add Google Cloud Example

packages/cdktf-cli/templates/typescript/.hooks.sscaff.js
Since setting envs differs on Windows, the way is was set before wasn't compatible. 
To prevent platform dependent issues we should have Windows based builds. That's tracked in #201 
Related #194  #198
=> Fix cdktf init on Windows

test/test-terraform-cloud/test.sh
The `terraform cloud integration test` requires a Github Actions secret to be set. This won't be set for external Pull Requests due to security concerns and it doesn't look like there's a way to enable them even manually on a per build basis. 
Therefore, this PR will make the Terraform Cloud integration skip if the `TERRAFORM_CLOUD_TOKEN` is not set. It's not ideal, and should be considered a temporary "fix", until we've settled on a proper solution for this.
Relates to #200
=> Don't run Terraform Cloud integration test on external PRs

packages/cdktf/lib/complex-computed-list.ts, packages/cdktf/lib/terraform-data-source.ts, packages/cdktf/lib/terraform-resource.ts, packages/cdktf/test/__snapshots__/data-source.test.js.snap, packages/cdktf/test/__snapshots__/resource.test.js.snap, packages/cdktf/test/data-source.test.ts, packages/cdktf/test/helper/data-source.ts, packages/cdktf/test/helper/resource.ts, packages/cdktf/test/resource.test.ts
Interpolation of `ComplexComputedList` for `TerraformDataSource`s should starts with `data.` prefix.
=> Fix interpolation bug in complex computed list of data sources

packages/cdktf/lib/terraform-element.ts, test/test-providers/main.ts
The `consul` provider has an attribute called `node`, which conflicts with the function in `TerraformElement`.
This introduces a more specific name `constructNode` to avoid conflicts like this.
Fixes #125
=> Avoid conflicts with resource attributes called "node"

packages/cdktf-cli/lib/get/base.ts, packages/cdktf-cli/templates/python/{{}}.gitignore
Running `pylint main.py` warns:
```
main.py:4:0: E0611: No name 'aws' in module 'imports' (no-name-in-module)
```
This change gets rid of that warning.
=> Python: setup imports dir as a package

CONTRIBUTING.md, package.json, packages/cdktf-cli/package.json, packages/cdktf/package.json
As pointed out in https://github.com/hashicorp/terraform-cdk/issues/265 the current contribution guide is very basic. This PR improves this guide and adds a `yarn watch` command to build `cdktf` and `cdktf-cli` packages:
=> Improve contribution guide and global watch

CHANGELOG.md, package.json
Quickly tested current pre release manually as well.
See Changelog for details.
=> Prepare Release 0.13

Dockerfile
There should be a way to easily track latest for a certain version. However, here's a manual bump.
=> Use current version of Terraform 0.13

packages/cdktf-cli/bin/cmds/helper/constructs-maker.ts, packages/cdktf-cli/lib/get/base.ts, test/test-python-third-party-provider/cdktf.json, test/test-python-third-party-provider/expected/cdk.tf.json, test/test-python-third-party-provider/main.py, test/test-python-third-party-provider/test.sh
When generating non HashiCorp maintained provider bindings (e.g. Docker) for Python, the generated package was broken. It didn't contain any type informations, since the path where those classes were actually generated and looked up wasn't matching. 
This fixes the naming and adds an integration test. 
Closes https://github.com/hashicorp/terraform-cdk/issues/307 
Related to https://github.com/hashicorp/terraform-cdk/issues/303
=> Fix Naming of Generated Package Paths for Python 

packages/cdktf-cli/lib/get/generator/provider-generator.ts, packages/cdktf-cli/test/get/generator/empty-provider-resources.test.ts, packages/cdktf-cli/test/get/generator/fixtures/empty-provider-resources.test.fixture.json, test/test-providers/cdktf.json, test/test-providers/main.ts
The external provider doesn't have any resources, only data sources. This makes sure the provider generates the classes and compiles.
=> Fix external provider

CHANGELOG.md, package.json
Since #309 fixed a Python bug and we don't provide pre-release versions in Python (see #293), let's do another release.
=> Prepare release 0.0.15

packages/cdktf/lib/terraform-provider.ts, packages/cdktf/test/helper/provider.ts
Match override behavior of generated provider schema
I'm not sure yet how this passed tests in #276, but this should fix the integration tests.
It is quite strange to me that terraform provider schema include `alias` when it is really more of a meta argument. If anyone from the terraform team could provide more context, that could make me more confident that this is the correct approach.
=> Fix TerraformProvider alias definition

packages/cdktf-cli/bin/cmds/ui/models/terraform.ts
This skips all interactive inputs and fails immediately if there's data missing
See https://learn.hashicorp.com/tutorials/terraform/automate-terraform#terraform-init-input-false-2
Fixes #250
=> Terraform in automation mode

.github/workflows/examples.yml, packages/cdktf/lib/terraform-data-source.ts, packages/cdktf/lib/terraform-element.ts, packages/cdktf/lib/terraform-module.ts, packages/cdktf/lib/terraform-resource.ts, test/test-providers/cdktf.json
There's a function in the Oracle provider which is named `nodeMetadata`. This conflicts
with function in cdktf base classes.
Hence, this PR aligins the naming with the change from `node` to `constructNode` (see #230)
Fixes #290
=> Oracle Provider Compatibility

CHANGELOG.md, package.json
**Fixed bugs:**
- Fix Orcacle Provider [\#341](https://github.com/hashicorp/terraform-cdk/issues/341)
- Run Terraform commands with `input=false` flag [\#343](https://github.com/hashicorp/terraform-cdk/issues/343)
- Use default provider caching of Terraform, rather than creating error prone symlinks [\#344](https://github.com/hashicorp/terraform-cdk/issues/344)
**Implemented enhancements:**
- Streamline CLI workflows for prebuilt providers [\#331](https://github.com/hashicorp/terraform-cdk/issues/331)
- CLI installable via Homebrew [\#342](https://github.com/hashicorp/terraform-cdk/issues/342)
=> Release 0.0.17

examples/python/kubernetes/main.py, packages/cdktf-cli/lib/get/generator/emitter/attributes-emitter.ts, packages/cdktf-cli/lib/get/generator/models/attribute-model.ts, packages/cdktf-cli/lib/get/generator/models/attribute-type-model.ts, packages/cdktf-cli/lib/get/generator/models/scope.ts, packages/cdktf-cli/lib/get/generator/models/struct.ts, packages/cdktf-cli/lib/get/generator/resource-parser.ts, packages/cdktf-cli/test/get/generator/__snapshots__/complex-computed-types.test.ts.snap, packages/cdktf-cli/test/get/generator/__snapshots__/description-escaping.test.ts.snap, packages/cdktf-cli/test/get/generator/__snapshots__/provider.test.ts.snap, packages/cdktf-cli/test/get/generator/__snapshots__/resource-types.test.ts.snap, packages/cdktf-cli/test/get/generator/__snapshots__/types.test.ts.snap, test/test-python-third-party-provider/expected/cdk.tf.json
Fixes #188 Also eliminates #214 
- Switch to always return attribute readers.
- Opted to not expose any set value publicly since there isn't a good indication of when it will work in local code.
- Changed behavior of attribute lookup of unknown type so that it has a chance of working correctly once synthesized.
- Use explicit required value from schema rather than assuming inverse of optional.
This ended being a lot more complicated than I expected: partially because providers and resources/data sources shared the same code, but mostly because of the complexities (and inconsistencies) of schema definition.
I'm pretty sure I fixed a couple bugs, but I'm not confident that I didn't introduce new ones, so I want to do some more testing before switching from draft.
=> Maintain dependencies between required construct properties

docs/getting-started/typescript.md, packages/cdktf-cli/templates/typescript-minimal/help, packages/cdktf-cli/templates/typescript/help, packages/cdktf-cli/templates/typescript/package.json
Since yarn isn't required for regular usage, this changes the Typescript template to use NPM.
=> Default to NPM in templates

examples/typescript/aws-cloudfront-proxy/main.ts
AcmCertificate DNS validation must use the DVO's resource_record_name
=> Fixes CloudFront Proxy Example

docs/working-with-cdk-for-terraform/using-providers-and-modules.md, packages/cdktf/lib/index.ts, packages/cdktf/lib/terraform-hcl-module.ts, packages/cdktf/lib/terraform-module.ts, packages/cdktf/test/__snapshots__/terraform-hcl-module.test.js.snap, packages/cdktf/test/terraform-hcl-module.test.ts
Helps with #16 
This is meant to be something a bit nicer than escape hatches for referencing non-registry modules. Eventually this may be come obsolete if code generation supports non-registry modules, but that seems like a ways off yet.
I didn't add the new Terraform 0.13 meta arguments. I think that's better suited for a follow up especially since there is a bunch of overlap between different types.
=> Terraform hcl module

Dockerfile
The jsii/superchain image sets `MAVEN_OPTS` with a max heap size that is too small for generating some of the larger providers. I've worked around it in #360, but for https://github.com/terraform-cdk-providers/cdktf-provider-project/pull/14 it will be easier to just have the value increased.
=> Increase Maven max memory

packages/cdktf/package.json
These silences the current warnings we have:
```
lib/app.ts:5:14 - message TS9999: JSII: Ignoring VariableDeclaration node (it cannot be represented in the jsii type model)
5 export const CONTEXT_ENV = 'CDKTF_CONTEXT_JSON';
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
lib/terraform-variable.ts:50:14 - warning TS9999: JSII: 'default' is a reserved word in C#, Java. Using this name may cause problems when generating language bindings. Consider using a different name.
50     readonly default?: any;
~~~~~~~
lib/backends/etcdv3-backend.ts:27:14 - warning TS9999: JSII: 'lock' is a reserved word in C#. Using this name may cause problems when generating language bindings. Consider using a different name.
27     readonly lock?: boolean;
~~~~
lib/backends/consul-backend.ts:30:14 - warning TS9999: JSII: …
```
=> Silence jsii warnings for reserved words

.github/workflows/release.yml, package.json, tools/release-github-maven.sh
Fixes #404 
This matches the behavior of jsii-release which will hopefully support GitHub packages in the future.
Duplicate testing: https://github.com/jsteinich/terraform-cdk/runs/1217459704?check_suite_focus=true
New version testing: https://github.com/jsteinich/terraform-cdk/runs/1217491032?check_suite_focus=true
=> Ignore GitHub Maven duplicate publish failure

Dockerfile
CHANGELOG: no impact
Dockerhub is going to rate limit unauthenticated pulls on November 1st. IPs from CI machines will be near their limit all the time. We're moving projects to use a public un-rate-limited Mirror of these images instead. Let me know if you have any q's, otherwise feel free to merge when you can!
=> Use docker mirror

.github/workflows/release_next.yml
With the upgrade of jsii to 1.14 a [new version mapping](https://github.com/aws/jsii/commit/1338fc2492295f683381d00a04fb88517f3c4d55#diff-7829468e86c1cc5d5133195b5cb48e1ff6c75e3e9203777f6b2e379d9e4882b3) for pre releases got introduced.
This broke our current schema based on git shas. 
This PR switches to `GITHUB_RUN_NUMBER`, which is an incrementing number and stable for retries of the same workflow run (see https://docs.github.com/en/free-pro-team@latest/actions/reference/environment-variables)
=> Fix pre release

CHANGELOG.md, package.json
This prepares for the `0.0.18` release. Huge thanks to @jsteinich for lots of contributions in this release! 🚀
**Fixed bugs:**
- Update jsii with python docs fix [\#418](https://github.com/hashicorp/terraform-cdk/issues/418)
- Maintain dependencies between required construct properties [\#310](https://github.com/hashicorp/terraform-cdk/issues/310)
**Implemented enhancements:**
- Java support [\#360](https://github.com/hashicorp/terraform-cdk/issues/360)
- Simple Terraform Locals [\#357](https://github.com/hashicorp/terraform-cdk/issues/357)
- allow to use TERRAFORM_BINARY_NAME env to set terraform binary [\#366](https://github.com/hashicorp/terraform-cdk/issues/366)
- Default to NPM in templates [\#359](https://github.com/hashicorp/terraform-cdk/issues/359)
- Terraform version check …
=> Prepare Release 0.0.18

packages/cdktf-cli/lib/get/generator/models/attribute-model.ts
Fixes #393 
This just adds to the existing renaming block in order to handle the `equals` attribute used by `aws_guardduty_filter`.
Long term this will hopefully be handled in jsii, but that is proving to be a bigger project than expected, so work around to unblock aws provider v3.
=> Remap 'equals' to 'equalTo' to work around jsii limitation

packages/cdktf/lib/complex-computed-list.ts, packages/cdktf/test/__snapshots__/data-source.test.js.snap, packages/cdktf/test/data-source.test.ts, packages/cdktf/test/helper/data-source.ts
Fixes #372 
Use same pattern as `ComplexComputeList` interpolation for `StringMap`, `NumberMap`, and `BooleanMap`.
=> Fix complex map attribute data source reference

packages/cdktf-cli/lib/get/generator/emitter/attributes-emitter.ts, packages/cdktf-cli/lib/get/generator/emitter/resource-emitter.ts, packages/cdktf-cli/lib/get/generator/emitter/struct-emitter.ts, packages/cdktf-cli/test/get/generator/__snapshots__/types.test.ts.snap, packages/cdktf-cli/test/get/generator/fixtures/name-conflict.test.fixture.json, packages/cdktf-cli/test/get/generator/types.test.ts
Fixes #427 
Very rarely, the generated names for resetting optional values and accessing the input value for required or optional values conflicts with other values.
I checked nearly 400 providers and found only 3 instances of conflict with `reset` and 1 with `input`. As such, I choose to only diverge from convention when necessary rather than changing the naming overall.
`XInput` -> `XTfInput` and `resetX` -> `resetTfX`
=> Alter reset and input names when they conflict

packages/cdktf/lib/terraform-stack.ts, packages/cdktf/test/remote-state.test.ts, packages/cdktf/test/variable.test.ts
Fixes #433.
Fixes #437.
Fixes #256.
Need to resolve tokens before converting to terraform json to prevent the Intrinsic's creation stack from being included. This matches the behavior of the AWS CDK.
I also updated a couple tests to check this behavior and to match the documentation for the associated features.
=> Make sure tokens resolved before converting to json

packages/cdktf/lib/index.ts, packages/cdktf/lib/terraform-data-source.ts, packages/cdktf/lib/terraform-dependable.ts, packages/cdktf/lib/terraform-module.ts, packages/cdktf/lib/terraform-output.ts, packages/cdktf/lib/terraform-resource.ts, packages/cdktf/test/__snapshots__/data-source.test.js.snap, packages/cdktf/test/__snapshots__/resource.test.js.snap, packages/cdktf/test/__snapshots__/terraform-hcl-module.test.js.snap, packages/cdktf/test/data-source.test.ts, packages/cdktf/test/helper/data-source.ts, packages/cdktf/test/helper/resource.ts, packages/cdktf/test/resource.test.ts, packages/cdktf/test/terraform-hcl-module.test.ts
Fixes #369 
Allows for depends on to specify resources, data sources, or modules.
Modules allowed to depend on the same.
Module dependencies were added in Terraform 0.13. We could add an error if running below that, but seems fine to just let Terraform fail.
=> Depends on expansion

.github/workflows/release_next.yml
With https://github.com/hashicorp/terraform-cdk/pull/421 we should be able to do pre-releases to PyPi now. 
Fixes https://github.com/hashicorp/terraform-cdk/issues/293
/cc @cmclaughlin @jsteinich
=> PyPi Pre-Releases

.github/workflows/release.yml, .github/workflows/release_next.yml
Closes #450 
While not an actual snapshot (or even using standard naming), this does match with other languages and should work with cdktf-cli@next without requiring extra builds or code changes.
Also a bit of cleanup on actual release that was missed when switching to jsii-release.
=> GitHub maven prerelease

CHANGELOG.md, package.json
**Fixed bugs:**
- Depends on expansion [\#442](https://github.com/hashicorp/terraform-cdk/issues/442)
- Make sure tokens resolved before converting to json [\#439](https://github.com/hashicorp/terraform-cdk/issues/439)
- Alter reset and input names when they conflict [\#429](https://github.com/hashicorp/terraform-cdk/issues/429)
- Fix complex map attribute data source reference [\#441](https://github.com/hashicorp/terraform-cdk/issues/441)
- Remap 'equals' to 'equalTo' to work around jsii limitation [\#428](https://github.com/hashicorp/terraform-cdk/issues/428)
- Generated custom mappings [\#395](https://github.com/hashicorp/terraform-cdk/issues/395)
=> Bugfix Release 0.19

.devcontainer.json, .github/workflows/build.yml, .github/workflows/docker.yml, .github/workflows/examples.yml, .github/workflows/release.yml, .github/workflows/release_next.yml
Avoid pulling from Docker Hub directly und use the Hashicorp proxy hashicorp.jfrog.io/docker/hashicorp/jsii-terraform
=> Use docker proxy for builds

README.md
MD012/no-multiple-blanks: Multiple consecutive blank lines [15, 1]
MD032/blanks-around-lists: Lists should be surrounded by blank lines [32, 1]
MD012/no-multiple-blanks: Multiple consecutive blank lines [117, 1]
=> Fix common Markdown formatting errors

packages/cdktf-cli/package.json, packages/cdktf/package.json, yarn.lock
Going to upgrade packages which were reported by dependabot.
=> Upgrade node-notifier to fix vulnerable version CVE-2020-7789

packages/cdktf-cli/templates/csharp/.hooks.sscaff.js, packages/cdktf-cli/templates/csharp/help, test/test-csharp-app/test.js
This avoids init behaviour as seen here (which is due to the requirement of having to authenticate for the Github Package registry):
This PR makes sure the `init` isn't erroring out and provides guidance to the user how to authenticate to the Github Package registry. We can revert back to the original behaviour once we got the official nuget.org registry distribution.
Note: We'll do a follow up for the Java template which has similar issues.
=> Improve C# init behaviour for Github Package Registry

packages/cdktf/lib/terraform-module.ts, packages/cdktf/test/__snapshots__/terraform-hcl-module.test.js.snap
Fixes #507 
I went with just changing the casing rather than using `keysToSnakeCase` because I think more explicit control is less likely to lead to issues and since `this.synthesizeAttributes` can have user values.
=> Correct depends on casing for modules

packages/cdktf/lib/terraform-hcl-module.ts, packages/cdktf/test/__snapshots__/terraform-hcl-module.test.js.snap, packages/cdktf/test/terraform-hcl-module.test.ts
Changing output reference to use tokens similar to data sources, variables, etc., since the cast from any was causing exceptions at runtime for non-string types.
=> TerraformHclModule outputs need to use tokens

package.json, packages/cdktf/package.json
Allows packaging for single language targets from project root directory. In particular useful when working with examples which are referencing these packages.
=> Easy package tasks for individual language targets

.github/workflows/docker.yml, .github/workflows/release_next.yml, CONTRIBUTING.md, docs/working-with-cdk-for-terraform/feature-flags.md
The actual renaming can be done via the [Github UI](https://github.com/github/renaming#renaming-existing-branches).
This PR reflects the changed name in workflows and documenation and should be merged after the renaming was done.
=> Rename default branch to main

.github/workflows/release.yml, .github/workflows/release_next.yml, README.md, docs/getting-started/csharp.md, examples/csharp/aws/Main.cs, examples/csharp/aws/MyTerraformStack.csproj, examples/csharp/azure/Main.cs, examples/csharp/azure/MyTerraformStack.csproj, examples/csharp/google/Main.cs, examples/csharp/google/MyTerraformStack.csproj, package.json, packages/cdktf-cli/bin/cmds/init.ts, packages/cdktf-cli/templates/csharp/.hooks.sscaff.js, packages/cdktf-cli/templates/csharp/Main.cs, packages/cdktf-cli/templates/csharp/MyTerraformStack.csproj, packages/cdktf-cli/templates/csharp/help, packages/cdktf/package.json, test/test-csharp-app/Main.cs, test/test-csharp-app/test.js
This adds a Github Action workflow for releasing `cdktf` to the Nuget.org registry.
As part of this, I renamed the package from `HashiCorp.Cdktf`, which is consistent with the official company name. This is a breaking change for future packages. However since we're switching the registry anyway and the dotnet usage of `cdktf` doesn't seem to be widespread so far, I think it's ok to do it without prior warning. 
Closes #524
=> Add Release Workflow for Nuget.org

packages/cdktf-cli/templates/python-pip/.hooks.sscaff.js
Discovered that the python pip template didn't work on windows. Applied similar changes to regular python template.
=> python pip template adjustments for windows

packages/cdktf-cli/templates/python-pip/.hooks.sscaff.js
Accidentally broke it when trying to fix for Windows.
Also adding some improvements.
- Don't require admin for install
- Explicitly use pip3 in case user has pip pointing to a different version. Fixes #532 
`pip` ends up just being an alias to `pip2` or `pip3` (unless you have python 1). Since we require python 3, pip3 will be installed.
=> Python-pip template fix/improvements

.github/workflows/build.yml, .github/workflows/docker.yml, .github/workflows/examples.yml, .github/workflows/release.yml, .github/workflows/release_next.yml
Since Markdown files and everything in [./docs](/docs) is unrelated to Github Actions we can safely skip running Actions if the diff contains only changes to these files. The [paths-ignore](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestpaths) config in Github Actions is doing the heavy lifting here.
=> Don't run Github Actions for doc changes

packages/cdktf-cli/bin/cmds/ui/terraform-context.tsx
Fix typo in `executorForStack`
=> Fix typo in execTerraformSynth

package.json, packages/cdktf-cli/lib/checkpoint.ts, packages/cdktf-cli/lib/util.ts, packages/cdktf-cli/package.json, packages/cdktf-cli/test/checkpoint.test.ts, yarn.lock
This PR adds proper error handling for the request object plus a timeout of 1s. This will silently ignore errors when Checkpoint isn't reachable for some reason.
Furthermore, this cleans up a bit of obsolete code and reorganizes deps / devDeps.
Fixes: https://github.com/hashicorp/terraform-cdk/issues/351
Related to: https://github.com/hashicorp/terraform-cdk/issues/544
=> Checkpoint Error Handling / Timeout

.github/workflows/release.yml, .github/workflows/release_next.yml
This PR switches the release process from Github Packages to Maven Central. 
Fixes: #523
=> Publish to Maven Central

README.md
It wasn't really obvious that we're supporting the entire ecosystem of modules and providers of Terraform. I've seen feedback on various channels about this, e.g.  https://github.com/hashicorp/terraform-cdk/issues/531#issuecomment-770290934 
This PR makes this a bit more clear early on in the Readme. It could use an image to make this even more obvious (something like the image in https://cdk.tf/launch tailored to cdktf only).
=> Emphasize that we support all modules and providers of Terraform

README.md
It picks up the pre-release version rather than the `0.1.0`. I think that's something to address in general (see https://github.com/hashicorp/terraform-cdk/issues/561).
=> Add Maven Central Badge to Readme

.devcontainer.json, .github/workflows/build.yml, .github/workflows/examples.yml, .github/workflows/release.yml, .github/workflows/release_next.yml, Dockerfile
This removes all references to `hashicorp.jfrog.io` which has been replaced with a self-hosted registry, `docker.mirror.hashicorp.services`
=> Remove jfrog references

packages/cdktf-cli/lib/get/base.ts
Fixes #588 
`null` is not allowed to be a namespace in java or c#, so replace it.
=> Rename null provider for java & c#

.github/workflows/build.yml, .github/workflows/examples.yml, Dockerfile, packages/cdktf-cli/bin/cmds/terraform-check.ts
This drops tests against `0.12` in favour of testing against the upcoming `0.15` version. That means with this PR being merged we're testing against `0.13`, `0.14`, and `0.15-beta`.
This depends https://github.com/hashicorp/terraform-cdk/pull/591 and will help https://github.com/hashicorp/terraform-cdk/pull/584 being merged. There are some provider schema differences with the change from `0.12` to `0.13` which don't seem worthwhile working around (I think it's purely testing related, functionality wise it's not an issue). 
I think it generally makes sense for now to track the current and prior major release of Terraform core - plus upcoming versions.
=> Update Terraform versions which are tested against

examples/python/aws-eks/Pipfile, examples/python/aws-eks/Pipfile.lock, examples/python/aws-eks/main.py
The following changes were broken on the example:
- Inside the imports folder, with the same cdktf.json, the subfolders created were: aws, vpc and eks instead of terraform_aws_modules.vpc and terraform_aws_modules.eks
- The constructor of the Eks and Vpc objects had their names updated from TerraformAwsModulesEksAws 
and TerraformAwsModulesVpcAws respectively
- The Eks constructor has the cluster_version parameter as obrigatory
=> Fixing aws eks example

packages/cdktf-cli/lib/get/generator/models/attribute-model.ts, packages/cdktf-cli/test/get/generator/__snapshots__/description-escaping.test.ts.snap, packages/cdktf-cli/test/get/generator/description-escaping.test.ts, packages/cdktf-cli/test/get/generator/fixtures/markdown-description-with-code-blocks.test.fixture.json
That popped up in the google-beta provider which transforms markdown fenced
code blocks from the actual markdown docs to the provider schema (``` => ''')
see
- https://raw.githubusercontent.com/hashicorp/terraform-provider-google-beta/4094e3bdd530ca853a046a6d938807f8a131c7c7/website/docs/r/iam_workload_identity_pool_provider.html.markdown
- https://github.com/hashicorp/terraform-provider-google-beta/blob/4094e3bdd530ca853a046a6d938807f8a131c7c7/google-beta/resource_iam_beta_workload_identity_pool_provider.go
Fixes https://github.com/hashicorp/terraform-cdk/issues/602
Relates to https://github.com/aws/jsii/issues/2727
=> Handle malformed code blocks in provider schema descriptions

packages/cdktf-cli/bin/cmds/ui/terraform-context.tsx
Fixes #582 
Currently any warning that is emitted by terraform during deployment or destruction will be interpreted as a resource which will cause a crash.
The check is added is certainly simplistic, but I'm not sure of a better way to definitely determine if an output line is referring to a resource.
=> Don't treat warning lines as resources

CHANGELOG.md, package.json
**Fixed Bugs**
- Allow for module without outputs [\#599](https://github.com/hashicorp/terraform-cdk/pull/599)
- Fix Python template [\#604](https://github.com/hashicorp/terraform-cdk/pull/604)
- Don't treat warning lines as resources [\#585](https://github.com/hashicorp/terraform-cdk/pull/585)
- Handle malformed code blocks in provider schema descriptions [\#605](https://github.com/hashicorp/terraform-cdk/pull/605)
=> Prepare release 0.2.1

packages/cdktf-cli/bin/cmds/ui/terraform-context.tsx
According to Terraform docs hyphens are allowed in resource ids https://www.terraform.io/docs/language/syntax/configuration.html#identifiers
Current version doesn't display apply status for 80% of resources in my deployment because of this bug.
=> Add hyphens to resource id regexp in output parser

packages/cdktf-cli/bin/cmds/ui/terraform-context.tsx
Still creating... and Still destroying... were not handled. If resource took long enough time to create or destroy it went from "Creating" state to "Waiting" state.
Probably cause of https://github.com/hashicorp/terraform-cdk/issues/403
=> Add missing handling for resource status lines

packages/cdktf-cli/bin/cmds/helper/terraform-cloud-client.ts, packages/cdktf-cli/bin/cmds/init.ts
In relation to #400 this prints the error messages returned by the Terraform Cloud API.
=> Improve error handling if Terraform Cloud workspace exists already

packages/cdktf-cli/templates/typescript/help
`-a` option does not exist and `-s` would be obsolete nowadays.
=> fix typescript help template typo

packages/cdktf-cli/bin/cmds/helper/synth-stack.ts, packages/cdktf-cli/lib/util.ts, packages/cdktf-cli/package.json, test/test-helper.ts, test/typescript/synth-app-error/cdktf.json, test/typescript/synth-app-error/main.ts, test/typescript/synth-app-error/test.ts
Resolves #533 by printing a more fitting error message including the command that was used for synth and the output that command wrote to stderr.
Before this change:
After this change:
(`index.js` did not exist)
And without anything on stderr:
=> Improve error handling if synthesizing fails

.github/workflows/docker.yml
We depend on [jsii superchain ](https://github.com/aws/jsii/tree/main/superchain) as a base image for our [Dockerfile](https://github.com/hashicorp/terraform-cdk/blob/d9d65467ecfa7c74f4ce3b8a63fbeb4150918117/Dockerfile)
In order to keep up with the base image, this PR changes the [build action](https://github.com/docker/build-push-action) to always pull images when building.
=> Always attempt to pull a newer version of the base image

CHANGELOG.md, package.json
**Fixed Bugs**
- Resources containing hyphens in resource ids did not correctly display their apply status [\#614](https://github.com/hashicorp/terraform-cdk/pull/614)
- Add missing handling for resource status lines [\#619](https://github.com/hashicorp/terraform-cdk/pull/619)
- Print more descriptive error messages if requests to Terraform Cloud fail [\#623](https://github.com/hashicorp/terraform-cdk/pull/623), [\#626](https://github.com/hashicorp/terraform-cdk/pull/626), [\#488](https://github.com/hashicorp/terraform-cdk/issues/488), [\#400](https://github.com/hashicorp/terraform-cdk/issues/400)
=> Prepare release 0.2.2

packages/cdktf-cli/test/get/generator/module-generator.test.ts, packages/cdktf-cli/test/get/read-schema.test.ts, packages/cdktf/lib/complex-computed-list.ts
Resolves #634 which was caused by a Terraform data source which had an attribute containing a list of items which each have a key `index` which collided with its base class `ComplexComputedList`.
=> rename instance variable to a more specific name to avoid name collisions

packages/cdktf-cli/bin/cmds/ui/models/terraform-cloud.ts, packages/cdktf-cli/package.json, yarn.lock
=> wait for ConfigurationVersion to be ready when using Terraform Cloud

test/csharp/synth-app/test.ts, test/java/synth-app/test.ts, test/jest.config.js, test/jest.setup.js, test/python/multiple-stacks/test.ts, test/python/synth-app/test.ts, test/python/third-party-provider/test.ts, test/typescript/feature-flags/test.ts, test/typescript/init-remote-template/test.ts, test/typescript/init-with-colors/test.ts, test/typescript/modules/test.ts, test/typescript/synth-app-error/test.ts, test/typescript/synth-app/test.ts, test/typescript/terraform-cloud/test.ts
Addressing integration test timeouts globally, so we don't have to think about this individually for each test.
=> Define global timeout for integration tests

README.md
fix(docs): remove readme not exist path
- Typescript
-  aws
=> fix(docs): rename `aws` to `aws-multiple-stacks` and add `aws-prebuilt` link

packages/cdktf-cli/templates/csharp/{{}}.gitignore, packages/cdktf-cli/templates/java/{{}}.gitignore, packages/cdktf-cli/templates/python-pip/{{}}.gitignore, packages/cdktf-cli/templates/python/{{}}.gitignore, packages/cdktf-cli/templates/typescript/{{}}.gitignore
I noticed that the `cdktf.log` was not yet ignored. I think it should be.
=> add cdktf.log to .gitignore of built-in templates

packages/cdktf-cli/bin/cdktf.ts, packages/cdktf-cli/bin/cmds/deploy.ts, packages/cdktf-cli/bin/cmds/diff.ts
Fixes #675,#573
I was unsuccessful in getting `yargs.showHelp` to show the commands, I feel like this iteration is a good step forward already :)
=> Return non-zero exit code on unknown command and allow terraform-like command names

packages/cdktf-cli/templates/csharp/{{}}.gitignore, packages/cdktf-cli/templates/java/{{}}.gitignore, packages/cdktf-cli/templates/python-pip/{{}}.gitignore, packages/cdktf-cli/templates/python/{{}}.gitignore, packages/cdktf-cli/templates/typescript/{{}}.gitignore
Previously the files were not successfully ignored
=> Stack: ignore state files

packages/cdktf-cli/templates/python-pip/.hooks.sscaff.js, packages/cdktf-cli/templates/python/.hooks.sscaff.js
Addresses issue #644 
Tested locally by initializing the python template project and successfully generating the cdk.tf.json output:
```
{
"//": {
"metadata": {
"version": "0.0.0",
"stackName": "python-example"
}
},
"terraform": {
"backend": {
"remote": {
"organization": "bradseiler-test",
"workspaces": {
"name": "python"
},
"hostname": "app.terraform.io"
}
}
}
}
```
=> chore(#644): Upgrade python templates to use RemoteBackend class

packages/cdktf-cli/bin/cdktf.ts, packages/cdktf-cli/bin/cmds/helper/terraform.ts, packages/cdktf-cli/bin/cmds/ui/models/terraform-cli.ts
An example error looks like this:
```
Error: ups I did it again
at Object.handler (/Users/danielschmidt/work/terraform-cdk/packages/cdktf-cli/bin/cmds/init.js:66:19)
at Object.runCommand (/Users/danielschmidt/work/terraform-cdk/packages/cdktf-cli/node_modules/yargs/lib/command.js:240:40)
at Object.parseArgs [as _parseArgs] (/Users/danielschmidt/work/terraform-cdk/packages/cdktf-cli/node_modules/yargs/yargs.js:1154:41)
at Object.get [as argv] (/Users/danielschmidt/work/terraform-cdk/packages/cdktf-cli/node_modules/yargs/yargs.js:1088:21)
at Object.<anonymous> (/Users/danielschmidt/work/terraform-cdk/packages/cdktf-cli/bin/cdktf.js:75:5)
at Module._compile (node:internal/modules/cjs/loader:1108:14)
at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
at Module.load …
```
=> Diagnostic: show version information on error

packages/cdktf/lib/terraform-element.ts, packages/cdktf/lib/terraform-stack.ts
Fixes #702 
This is technically a breaking change since public API is being changed, though likely low impact.
=> Rename stack property to avoid conflict

packages/cdktf-cli/lib/get/generator/models/resource-model.ts, packages/cdktf-cli/lib/get/generator/resource-parser.ts, packages/cdktf-cli/test/get/provider.test.ts
Fixes #568 
Fixes #703 
This just routes the config class through the existing duplicate name check. Using duplicated names is not a great user experience, but until #572 or similar is done, this is much better than failing to generate.
=> Check for duplicate config class names

packages/cdktf-cli/bin/cmds/ui/models/terraform-cloud.ts, test/typescript/terraform-cloud/__snapshots__/test.ts.snap, test/typescript/terraform-cloud/main.ts
This leaves us with predictable identifiers used
=> HCL output: use attribute name instead of id

packages/cdktf-cli/bin/cmds/ui/models/terraform-cloud.ts, packages/cdktf-cli/package.json, yarn.lock
- Throws prefixed errors in case of terraform cloud API errors so that there is more context
- Throws a new error when the plan errored
- Poll logs from terraform cloud to see updates inbetween
- Throws a new error when the workspace is locked
=> Update UI state on deploy / destroy

Dockerfile
This adds 0.15.4 Terraform version. A follow up PR will swap the actual versions used.
=> Add current Terraform version

packages/cdktf-cli/package.json, packages/cdktf/package.json
We previously had a switch statement which had a case like `case a,b:` which at first looked like handling both a and b but in JS/TS it doesn't. It resolves to just b. To catch something like this, we enable this eslint rule and disallow sequences anywhere.
This is how it is going to look with this commit
For reference, this is what that code meant to say
=> chore(cdktf-cli): enable eslint rule no-sequences

test/go/synth-app/cdktf.json
The tests `main.go` uses generated provider bindings that are within a namespace. And although Terraform defaults to `hashicorp` if no namespace is set, our code apparently doesn't do that yet.
I'm going to create a follow-up issue to address this.
=> fix(tests): adjust terraform provider name to match imports used in main.go

packages/cdktf-cli/bin/cmds/ui/terraform-context.tsx
`Plan:` was matched by accident. This changes the regex to require
something like `abc.foo` to match.
```
null_resource.test: Refreshing state... [id=2265159398281528182]
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
- destroy
Terraform will perform the following actions:
- resource "null_resource" "test" {
- id = "2265159398281528182" -> null
}
Plan: 0 to add, 0 to change, 1 to destroy.
null_resource.test: Destroying... [id=2265159398281528182]
null_resource.test: Destruction complete after 0s
Destroy complete! Resources: 1 destroyed.
```
```
null_resource.test: Refreshing state... [id=1540203300502369612]
null_resource.test: Destroying... [id=1540203300502369612]
null_resource.test: Destruction …
```
=> fix(cli): Adapt to changed output format in Terraform 0.15.4

packages/cdktf-cli/bin/cmds/ui/terraform-context.tsx
This reverts #736 and adds an explicit workaround for `Plan:`. Not ideal, but should for now.
This is related to #738
=> fix(cli): Workaround Terraform 0.15.4 output changes

.github/workflows/release.yml, .github/workflows/release_next.yml
Related Workflow failure: https://github.com/hashicorp/terraform-cdk/runs/2685171282?check_suite_focus=true
=> fix: fix github workflow for releasing cdktf go package

test/typescript/modules/__snapshots__/test.ts.snap, test/typescript/modules/test.ts
It skipped in both cases, but shouldn't.
=> fix(tests): fix onWindows helper skipping on windows

packages/cdktf-cli/bin/cmds/ui/terraform-context.tsx, test/jest.setup.js
I think this should have been the default case in the first place. This
surfaced due to output changes in 0.15.4 - similar to this #739 but now
for cdktf destroy.
In general I think we'll switch the entire output processing over
to this https://www.terraform.io/docs/internals/machine-readable-ui.html
Here's an example of the `terraform destroy` output with `0.15.4` - so there are lots of false positive matches for the resource regex. With the change in this PR, these false positives aren't actually processed anymore:
<details>
```
aws_iam_role.lambda-exec: Refreshing state... [id=learn-cdktf-lambda-hello-world]
aws_s3_bucket.bucket: Refreshing state... [id=learn-cdktf-lambda-hello-world20210604185509492100000001]
aws_iam_role_policy_attachment.lambda-managed-policy: Refreshing state... …
```
=> fix(cli): Make sure output parses only relevant parts 

packages/cdktf-cli/bin/cmds/init.ts, packages/cdktf-cli/lib/logging.ts
I have the `CDKTF_DISABLE_LOGGING=false` set, so every `cdktf init` fails because the first log line is written before the init command checks if the directory is empty
=> fix(cli): dont error on init when log has been written

CHANGELOG.md, package.json
**Fixed Bugs**
- Fix `cdktf destroy` - Make sure output parses only relevant parts [\#761](https://github.com/hashicorp/terraform-cdk/pull/761)
- Dont error on init when log has been written [\#759](https://github.com/hashicorp/terraform-cdk/pull/759)
=> fix(release): Release 0.4.1

packages/cdktf-cli/bin/cmds/ui/models/schema.ts, packages/cdktf-cli/bin/cmds/ui/terraform-context.tsx, packages/cdktf-cli/package.json, packages/cdktf-cli/tsconfig.json, yarn.lock
Alternative approach for #770, I think I like it better. I strongly typed every possible message mentioned in https://www.terraform.io/docs/internals/machine-readable-ui.html (thank you @jsteinich for pointing me to it).
=> fix(cli): parse JSON output

.github/workflows/timechart.yml
It's difficult to determine all jobs for a PR see https://docs.mergify.io/conditions/#about-status-checks 
Since we have this 'checkrun-timechart' job, which essentially knows all the statuses (see https://github.com/WyriHaximus/github-action-wait-for-status#output) we can leverage it to provide a global status to mergify.
=> chore(tests): Provide global PR workflow status

docs/getting-started/csharp.md, docs/getting-started/go.md, docs/getting-started/java.md, docs/getting-started/python.md, docs/getting-started/typescript.md
=> fix(docs): add mandatory cdktf get step

docs/full-guide/serverless-application-typescript.md
Adds a guide explaining the end to end serverless example.
[rendered version](https://github.com/hashicorp/terraform-cdk/blob/add-serverless-application-guide/docs/full-guide/serverless-application-typescript.md)
Repo with end to end serverless example: https://github.com/hashicorp/cdktf-integration-serverless-example (also linked in guide)
What do you think having this guide inside the newly created `docs/full-guide` directory? Happy to move it elsewhere if that seems off.
Resolves #733
=> chore(docs): Add serverless application guide

packages/cdktf-cli/bin/cmds/ui/models/terraform-cloud.ts, test/typescript/terraform-cloud/main.ts, test/typescript/terraform-cloud/test.ts
=> fix(cli): dont upload .terraform folders

BUGPROCESS.md, examples/typescript/google/cdktf.json, package.json, packages/cdktf-cli/bin/cmds/ui/app.tsx, packages/cdktf-cli/bin/cmds/ui/components/resource-name.tsx, packages/cdktf-cli/bin/cmds/ui/deploy.tsx, packages/cdktf-cli/bin/cmds/ui/destroy.tsx, packages/cdktf-cli/bin/cmds/ui/diff.tsx, packages/cdktf-cli/bin/cmds/ui/get.tsx, packages/cdktf-cli/bin/cmds/ui/list.tsx, packages/cdktf-cli/bin/cmds/ui/synth.tsx, packages/cdktf-cli/bin/cmds/ui/terraform-context.tsx, packages/cdktf-cli/package.json, yarn.lock
Noticed some code smells with React Hooks.  
E.g. `synth` function [being a hook](https://reactjs.org/docs/hooks-rules.html#only-call-hooks-from-react-functions), because it called an `useEffect` hook, but not prefixed with `use` ([docs](https://reactjs.org/docs/hooks-custom.html#extracting-a-custom-hook)).
=> chore(cli): lint tsx files and clean up React Hooks code

packages/cdktf-cli/lib/get/generator/custom-defaults.ts
Fixes #813 
This just adds in the reported missing defaults.
Would be nice if Terraform were modified to either not work this way when using json or to provide the information in the json schema.
=> fix(lib): Add in new optional AWS route attributes

packages/cdktf-cli/test/config.test.ts
Don't require the terraform-cdk to be checked out into a directory with exactly that name for this test case to succeed. Reported by @yufeiminds in https://github.com/hashicorp/terraform-cdk/pull/790\#issuecomment-879046497
=> fix(tests): make less assumptions about environment in config.test.ts

packages/cdktf-cli/bin/cmds/helper/synth-stack.ts, packages/cdktf-cli/bin/cmds/helper/terraform-login.ts, packages/cdktf-cli/bin/cmds/init.ts, packages/cdktf-cli/bin/cmds/login.ts, packages/cdktf-cli/lib/errors.ts, packages/cdktf-cli/lib/get/constructs-maker.ts, packages/cdktf-cli/lib/get/generator/module-generator.ts, packages/cdktf-cli/lib/get/generator/provider-generator.ts, packages/cdktf-cli/lib/get/generator/provider-schema.ts, packages/cdktf-cli/lib/get/generator/resource-parser.ts, packages/cdktf-cli/lib/util.ts, test/test-helper.ts, test/typescript/synth-app-error/test.ts
This PR helps us track errors to understand the problems of our user-base better. 
I added the Errors object in an adjecent effort of being deliberate about Error types
=> chore(cli): send telemetry on errors

Dockerfile
This is mainly to test whether everything would still build and compile with this version.
We require Nodejs version 12 in our installation instructions but currently use the default jsii/superchain Docker image for builds which contains Nodejs v10. Unfortunately there is no Docker container with Nodejs v12 readily available for the jsii/superchain image.
The reason for this test is that the graphql-server, which is used in #801, needs Nodejs v12.
=> chore(deps): use nodejs v14 version of aws jsii/superchain image

Dockerfile, test/test-helper.ts
node-gyp is used by node-pty which is going to be used to test the interactive cdktf watch command
=> chore(deps): add gcc and gcc-c++ to Dockerfile required for node-gyp

packages/cdktf-cli/bin/cdktf.ts, packages/cdktf-cli/bin/cmds/convert.ts, packages/cdktf-cli/bin/cmds/deploy.ts, packages/cdktf-cli/bin/cmds/destroy.ts, packages/cdktf-cli/bin/cmds/diff.ts, packages/cdktf-cli/bin/cmds/get.ts, packages/cdktf-cli/bin/cmds/helper/check-directory.ts, packages/cdktf-cli/bin/cmds/helper/render-ink.tsx, packages/cdktf-cli/bin/cmds/helper/terraform-check.ts, packages/cdktf-cli/bin/cmds/helper/version-check.ts, packages/cdktf-cli/bin/cmds/init.ts, packages/cdktf-cli/bin/cmds/list.ts, packages/cdktf-cli/bin/cmds/login.ts, packages/cdktf-cli/bin/cmds/synth.ts, packages/cdktf-cli/lib/checkpoint.ts, packages/cdktf-cli/lib/errors.ts, packages/cdktf-cli/lib/get/constructs-maker.ts
To test, please run any cfktf command that needs to run inside a cdktf project somewhere else
=> fix(cli): throw explicit error when commands are invoked outside of a cdktf project

packages/@cdktf/hcl2cdk/lib/index.ts, packages/@cdktf/hcl2cdk/test/convertProject.test.ts, packages/cdktf-cli/bin/cmds/helper/init.ts
Should fix running get if there are no modules and providers added to the cdktf.json
=> fix(hcl2cdk): only run get conditionally

packages/cdktf-cli/bin/cmds/helper/init.ts, packages/cdktf-cli/bin/cmds/helper/terraform-login.ts, packages/cdktf-cli/package.json, yarn.lock
=> fix(cli): polish user interaction by switching libraries

packages/@cdktf/hcl2cdk/lib/expressions.ts, packages/@cdktf/hcl2cdk/lib/generation.ts, packages/@cdktf/hcl2cdk/lib/index.ts, packages/@cdktf/hcl2cdk/lib/iteration.ts, packages/@cdktf/hcl2cdk/lib/types.ts, packages/@cdktf/hcl2cdk/lib/utils.ts, packages/@cdktf/hcl2cdk/package.json, packages/@cdktf/hcl2cdk/test/__snapshots__/hcl2cdk.test.ts.snap, packages/@cdktf/hcl2cdk/test/expressions.test.ts, packages/@cdktf/hcl2cdk/test/hcl2cdk.test.ts, yarn.lock
```hcl
variable "test" {
type = string
}
locals {
test = "${var.test} + 1"
}
output "test" {
value = "${local.test}"
}
```
```ts
import * as cdktf from "cdktf";
const test = new cdktf.TerraformVariable(this, "test", {});
const test = `\${${test.value}} + 1`;
new cdktf.TerraformOutput(this, "test", {
value: test,
});
```
```ts
import * as cdktf from "cdktf";
const testVar = new cdktf.TerraformVariable(this, "test", {});
const testLocal = `\${${testVar.value}} + 1`;
new cdktf.TerraformOutput(this, "test", {
value: testLocal,
});
```
=> fix(hcl2cdk): suffix variables and locals

docs/working-with-cdk-for-terraform/using-providers.md
Since this question came up in the cdk.dev slack channel, this adds it to the docs for future reference.
=> chore(docs): Brief reference for local provider usage

packages/cdktf/lib/util.ts, packages/cdktf/test/__snapshots__/output.test.js.snap, packages/cdktf/test/__snapshots__/provider.test.js.snap, packages/cdktf/test/__snapshots__/variable.test.js.snap, packages/cdktf/test/output.test.ts, packages/cdktf/test/provider.test.ts, packages/cdktf/test/variable.test.ts
previously they were treated like normal objects resulting in unresoluted tokens
Closes #898
=> fix(lib): keysToSnakeCase needs to ignore intrinsic tokens

packages/cdktf/lib/terraform-asset.ts, test/python/asset/__snapshots__/test.ts.snap, test/python/asset/main.py, test/typescript/asset/main.ts, test/typescript/asset/test.ts
=> feat(lib): make asset paths change if asset content changes

README.md, docs/getting-started/python.md
Link a first community maintained remote template for using Python with Python Poetry as a package manager. Related to #905
=> chore(docs): Link Python Poetry community template

packages/cdktf/lib/terraform-stack.ts, packages/cdktf/test/stack.test.ts
Relates to reported issue #944
=> feat(lib): Print a hint when the app has been passed to a backend instead of the stack

package.json, yarn.lock
This would have prevented #1033
It would've failed like this:
```
yarn run v1.22.10
$ eslint .
/Users/ansgar/projects/hashicorp/terraform-cdk/packages/cdktf-cli/lib/util.ts
7:37  error  Import for monorepo package 'cdktf' should be absolute  monorepo/no-relative-import
✖ 1 problem (1 error, 0 warnings)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
=> chore: lint monorepo for relative imports between packages

packages/@cdktf/hcl2cdk/lib/generation.ts, packages/@cdktf/hcl2cdk/lib/index.ts, packages/@cdktf/hcl2cdk/test/__snapshots__/hcl2cdk.test.ts.snap, packages/@cdktf/hcl2cdk/test/hcl2cdk.test.ts
=> fix(hcl2cdk): Correctly handle remote state

docs/working-with-cdk-for-terraform/testing.md, packages/cdktf/lib/testing/__tests__/matchers.test.ts, packages/cdktf/lib/testing/adapters/__tests__/jest.test.ts, packages/cdktf/lib/testing/adapters/jest.ts, packages/cdktf/lib/testing/matchers.ts
- Allows Jest users to write assertions using asymetric matchers (e.g. `expect.arrayContaining` or `expect.stringContaining`) making the assertions easier to write
- Adds more context to a failed test by showing the resources found of the given type
- Changes the semantic of `toHaveResourceWithProperties` and `toHaveDataSourceWithProperties` from object equality to deep equality
Closes #1047
=> feat(lib): use jest asymetric matchers & nicer error messages

packages/cdktf-cli/lib/checkpoint.ts
When running cdktf in a directory without a cdktf.json it would create one in an effort to create a project id, leaving stray files around when doing convert or init. This PR makes it only write to the cdktf.json if there was one detected
=> fix(cli): don't create config.json files if none was present before

packages/cdktf/lib/terraform-module.ts, packages/cdktf/test/__snapshots__/terraform-hcl-module.test.ts.snap, test/typescript/modules/__snapshots__/test.ts.snap
=> fix(lib): fix source path generated for local modules

packages/cdktf/lib/terraform-functions.ts
Hi Terraform Colleagues
Thanks a lot for your amazing work. Just found a little typo. Keep continue like this!
Regards
Geoffrey
=> fix(docs): typo in documentation

.github/.dependabot.yml
Dependabot created commits / PRs with a bad prefix (`build(deps)`). After this change it'll be `chore(deps)`.
=> chore: fix config for dependabot

packages/cdktf/lib/terraform-functions.ts, packages/cdktf/test/functions.test.ts
Passing undefined and null into arrays in terraform functions leads to errors / invalid terraform configuration. We strip them out for that reason
=> fix(lib): remove undefined and null values from terraform function lists

README.md
I think it's confusing to have a roadmap link that isn't a roadmap we maintain
=> chore(docs): remove roadmap link from README

website/docs/cdktf/examples.html.md
Am I missing any YouTube videos you all are aware of?
=> chore(docs): link docs to Pocket codebase, YouTube

.prettierignore
These prettier errors only surfaced locally only as in CI `prettier --check` is run before any build.
=> fix: ignore build output in prettier

packages/cdktf/lib/testing/index.ts
When using snapshot testing I was getting the following the error:
```
Cannot convert undefined or null to object
TypeError: Cannot convert undefined or null to object
```
Turns out this is caused by the following snippet of CDK code:
```
const securityGroup = new SecurityGroup(
scope,
'elasticache_security_group',
{
namePrefix: 'ACME',
description: 'Managed by Terraform',
vpcId:  '123',
ingress: [
{
fromPort: 12,
toPort: 12,
protocol: 'tcp',
},
],
tags: config.tags,
}
```
This should syntesize an ingress block to:
```
{
cidr_blocks: null,
description: null,
from_port: 11211,
ipv6_cidr_blocks: null,
prefix_list_ids: null,
protocol: 'tcp',
security_groups: null,
self: null,
to_port: 11211
}
```
The snapshot testing library however currently tries to remove metadata and does a typeof check …
=> fix(lib): check for null on removing metadata in testing framework

packages/cdktf-cli/lib/checkpoint.ts
=> fix(cli): create .cdktf folder if needed

packages/@cdktf/hcl2cdk/test/convertProject.test.ts, packages/cdktf-cli/package.json, test/run-against-dist, yarn.lock
This tries to fix the build & might fix installation of `cdktf-cli` when using yarn (`resolutions` is a yarn feature, the npm equivalent is not available yet).
=> fix(cli): directly depend on cli-spinners v2.6.0

CHANGELOG.md, package.json
**Breaking Changes**
If you use Terraform Modules you will need to adust their names. We changed the naming to be more intuitive, e.g. `TerraformAwsModulesVpcAws` is now `Vpc`. To migrate please run `cdktf get` with this version and change your imports to match the new abbreviated form.
**Fixed Bugs**
- fix(cli): directly depend on cli-spinners v2.6.0 [\#1116](https://github.com/hashicorp/terraform-cdk/pull/1116)
- fix(cli): create .cdktf folder if needed [\#1107](https://github.com/hashicorp/terraform-cdk/pull/1107)
- fix(lib): check for null on removing metadata in testing framework [\#1075](https://github.com/hashicorp/terraform-cdk/pull/1075)
- fix: ignore build output in prettier [\#1077](https://github.com/hashicorp/terraform-cdk/pull/1077)
**Chores**
- chore(deps): bump …
=> chore(release): Prepare release 0.6.4

website/docs/cdktf/concepts/stacks.html.md
This adds a link to the new [CDKTF applications](https://learn.hashicorp.com/tutorials/terraform/cdktf-applications?in=terraform/cdktf) tutorial.
=> feat(docs): add link to new deploy apps tutorial

docs/getting-started/typescript.md
Looks like `Instance` is no longer directly exported
https://github.com/hashicorp/terraform-cdk/blob/main/examples/typescript/aws-multiple-stacks/main.ts
=> fix: Fix EC2 Instance creation example

examples/java/aws/cdktf.json
allows our builds to work until #1260 is resolved
=> fix(examples): temporarily set fixed AWS provider version for Java

packages/@cdktf/provider-generator/lib/get/constructs-maker.ts
Azurerm provider generation for Go [fails](https://github.com/hashicorp/terraform-cdk/issues/1264) because the 'hard' limit is 10240 MB and azurerm provider needs ~13 GBs of memory to get generated.
⚠️ Note: This is just further delaying a fix of a workaround rather than a solution.
=> fix(lib): Increased --max-old-space-size value

packages/cdktf/lib/terraform-functions.ts, packages/cdktf/lib/tfExpression.ts, packages/cdktf/test/functions.test.ts, packages/cdktf/test/tfExpression.test.ts
Previously newlines were added to the synthesised JSON, which JSON only accepts if escaped
This PR also escapes ${} into $${}
Closes #1165
=> fix(lib): escape newlines in terraform functions

packages/cdktf/lib/index.ts, packages/cdktf/lib/terraform-addressable.ts, packages/cdktf/lib/terraform-dependable.ts, packages/cdktf/lib/terraform-local.ts, packages/cdktf/lib/terraform-output.ts, packages/cdktf/lib/terraform-remote-state.ts, packages/cdktf/lib/terraform-variable.ts, packages/cdktf/lib/tfExpression.ts, packages/cdktf/test/__snapshots__/output.test.ts.snap, packages/cdktf/test/output.test.ts, packages/cdktf/test/tfExpression.test.ts
Fixes #1088 
Terraform output values can be assigned any expression according to https://www.terraform.io/docs/language/values/outputs.html#declaring-an-output-value.
Since we have started having a type to represent expressions, I thought it would make sense to start using it. I added a few things in so that we wouldn't reduce what could be passed to an output. We don't yet have a complete list; however, we do have `any` which can help cover missing cases.
I also added in `ITerraformDependable` to just output values to cover outputting an entire resource or module. I assume data sources can also be used that way, but if not, we can easily narrow it. I'm not sure if these can be used in general expressions, but if so, can move to there.
Draft because no new tests yet.
=> feat(lib): Expand Output value types

website/docs/cdktf/examples.html.md, website/layouts/cdktf.erb
Per a conversation with @schersh, users have been asking for "How To" guides for CDKTF. We do have those on Learn, so our hypothesis is that it's not clear to some users what's available for them. This PR aims to address this issue by:
- Renaming "Examples" to "Examples and Guides". We think users may be looking for keywords like "How To" or "Guide", which are sections in other popular documentation sets. 
- Moving the Examples and Guides page up higher in the sidebar - it now sits underneath "Create and Deploy." This is one of the most-visited pages according to Google Analytics, so it's obviously information that users want and need. Moving it up in the hierarchy will hopefully help emphasize it a bit more.
- Listing out the available tutorials on Learn inside the Examples and Guides …
=> chore(docs): Move examples up in sidebar, list out tutorials

packages/@cdktf/provider-generator/lib/get/__tests__/generator/__snapshots__/complex-computed-types.test.ts.snap, packages/@cdktf/provider-generator/lib/get/__tests__/generator/__snapshots__/provider.test.ts.snap, packages/@cdktf/provider-generator/lib/get/__tests__/generator/__snapshots__/resource-types.test.ts.snap, packages/@cdktf/provider-generator/lib/get/__tests__/generator/__snapshots__/types.test.ts.snap, packages/@cdktf/provider-generator/lib/get/generator/emitter/attributes-emitter.ts, packages/@cdktf/provider-generator/lib/get/generator/models/attribute-model.ts, test/typescript/providers/main.ts
While this is true in general also on structs we can not implement it there without removing the ability to use setters since setter and getter types need to be the same. This is a short term fix to get ridof the regression we introduced.
Closes #1200
=> fix(provider-generator): attributes on resources should not be undefined

CONTRIBUTING.md
This will make doing follow-ups and grooming unclear tickets easier for us
=> chore(docs): document queries for issue grooming

packages/@cdktf/provider-generator/lib/get/__tests__/generator/__snapshots__/complex-computed-types.test.ts.snap, packages/@cdktf/provider-generator/lib/get/__tests__/generator/__snapshots__/resource-types.test.ts.snap, packages/@cdktf/provider-generator/lib/get/__tests__/generator/__snapshots__/types.test.ts.snap, packages/@cdktf/provider-generator/lib/get/generator/emitter/struct-emitter.ts, packages/cdktf/lib/util.ts, packages/cdktf/test/__snapshots__/output.test.ts.snap, test/typescript/synth-app/__snapshots__/test.ts.snap, test/typescript/synth-app/main.ts
Fixes #1182 
This is an alternative to #1322 that doesn't alter the output json in other ways.
I initially thought this approach would have many other side effects, but early testing hasn't revealed any (other than other things that were broken).
=> fix(lib): Keep specified empty objects

packages/cdktf-cli/bin/cmds/ui/models/terraform-cloud.ts
Got this error while trying it running against Terraform Cloud in remote execution mode
```
⠙ synthesizing...
(node:80284) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)
Running plan in the remote backend. To view this run in a browser, visit: https://a
pp.terraform.io/app/cdktf/workspaces/dschmidt-testing3/runs/run-w4enLFZttKxXrrrE
⠏ Deploying Stack: tmp.RpsjNA6F
Resources
~ NULL_RESOURCE        resource            null_resource.resource
Summary: 0 created, 0 updated, 0 destroyed.
/Users/danielschmidt/work/terraform-cdk/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
throw ex;
^ …
```
=> fix: data can be null in some cases as well

packages/cdktf/lib/tfExpression.ts, packages/cdktf/lib/tokens/token.ts, packages/cdktf/test/tfExpression.test.ts
Found this bug while iterating on cross stack references
=> fix(lib): inline references in strings should not destroy string itself

.github/workflows/release.yml
This should fix our release pipeline
=> chore: copy edge provider on release pipeline

examples/typescript/aws-cloudfront-proxy/package.json, examples/typescript/aws-multiple-stacks/package.json, examples/typescript/aws-prebuilt/package.json, examples/typescript/azure-app-service/package.json, examples/typescript/azure-service-bus-queue-trigger/package.json, examples/typescript/azure/package.json, examples/typescript/backends/azurerm/package.json, examples/typescript/backends/gcs/package.json, examples/typescript/backends/remote/package.json, examples/typescript/backends/s3/package.json, examples/typescript/docker/package.json, examples/typescript/google-cloudrun/package.json, examples/typescript/google/package.json, examples/typescript/kubernetes/package.json, examples/typescript/ucloud/package.json, examples/typescript/vault/package.json, packages/cdktf-cli/package.json, packages/cdktf/package.json, yarn.lock
This fixes a CI issue with CSharp integration tests
=> chore: update constructs to 10.0.12

packages/@cdktf/provider-generator/lib/get/__tests__/generator/__snapshots__/types.test.ts.snap, packages/@cdktf/provider-generator/lib/get/__tests__/generator/fixtures/incompatible-attribute-names.test.fixture.json, packages/@cdktf/provider-generator/lib/get/generator/models/attribute-model.ts
fixes #1420 (Okta Terraform provider)
=> fix(provider-generator): rename `system` attributes as they conflict in CSharp

.github/workflows/release_next.yml
Same as https://github.com/hashicorp/terraform-cdk/pull/1408 but for `Release@Next`
=> chore: fix edge provider tests in pre-release pipeline

Makefile, website/README.md
This PR adds a `Makefile` with the command `make website`, which allows the caller to preview the Terraform website with the changes in their local copy of this repo.
=> chore: add make website command to preview docs website

website/data/cdktf-nav-data.json
This PR copies the Terraform CDK specific navigation files from `terraform-website` to this repo. This enables docs authors to adjust sidebar navigation within the same PR as their docs changes.
=> chore: store website nav files (stable-website)

website/data/cdktf-nav-data.json
This PR copies the Terraform CDK specific navigation files from `terraform-website` to this repo. This enables docs authors to adjust sidebar navigation within the same PR as their docs changes.
=> chore: store website nav files (main)

website/docs/cdktf/concepts/variables-and-outputs.mdx
You can access to RemoteState by id of the Output which is `random-pet` in this case.
=> fix: Update Remote State Outputs documentation

packages/cdktf/lib/terraform-variable.ts, packages/cdktf/test/__snapshots__/variable.test.ts.snap, packages/cdktf/test/variable.test.ts
Fixes #1432
Adds the `nullable` field to `TerraformVariable` in order to handle usage of the field in HCL files from Terraform v1.1.0 and later.
=> feat(lib): Add nullable field to terraform variables

CHANGELOG.md, package.json
- fix(provider-generator): remove .html suffix for doc links [\#1438](https://github.com/hashicorp/terraform-cdk/pull/1438)
- fix: Update Remote State Outputs documentation [\#1436](https://github.com/hashicorp/terraform-cdk/pull/1436)
- feat(lib): Add nullable field to terraform variables [\#1435](https://github.com/hashicorp/terraform-cdk/pull/1435)
- chore: update constructs to 10.0.20 [\#1444](https://github.com/hashicorp/terraform-cdk/pull/1444)
- chore: store website nav files (main) [\#1434](https://github.com/hashicorp/terraform-cdk/pull/1434)
- chore: add make website command to preview docs website [\#1426](https://github.com/hashicorp/terraform-cdk/pull/1426)
=> chore: release 0.8.4

packages/@cdktf/provider-generator/lib/get/generator/resource-parser.ts, test/java/synth-app/Main.java, test/java/synth-app/__snapshots__/test.ts.snap, test/java/synth-app/cdktf.json
The random provider has a resource named String, the conflict with the native class causes the java build to fail.
Closes #1376
=> fix(provider-generator): rename String resource

CHANGELOG.md, package.json
- fix(provider-generator): rename String resource [\#1455](https://github.com/hashicorp/terraform-cdk/pull/1455)
- chore(hcl2cdk): update readme [\#1452](https://github.com/hashicorp/terraform-cdk/pull/1452)
- chore(examples): Upgrade aws provider version for Go example [\#1450](https://github.com/hashicorp/terraform-cdk/pull/1450)
- chore: update maven config for publishing [\#1457](https://github.com/hashicorp/terraform-cdk/pull/1457)
- chore: update constructs to 10.0.25 [\#1453](https://github.com/hashicorp/terraform-cdk/pull/1453)
=> chore: release 0.8.5

test/csharp/edge/test.ts
=> chore: fix constructs error

examples/typescript/azure-app-service/package.json, examples/typescript/azure-service-bus-queue-trigger/package.json, examples/typescript/azure/package.json, examples/typescript/backends/azurerm/package.json, examples/typescript/backends/gcs/package.json, examples/typescript/backends/remote/package.json, examples/typescript/backends/s3/package.json, examples/typescript/google-cloudrun/package.json, examples/typescript/google/package.json, examples/typescript/kubernetes/package.json, examples/typescript/ucloud/package.json, examples/typescript/vault/package.json, packages/@cdktf/hcl2cdk/test/convertProject.test.ts, packages/cdktf-cli/templates/typescript/package.json
Node 12 has been required for quite some time already, the examples (and our template) only weren't updated yet.
For example see this check which already exists: https://github.com/hashicorp/terraform-cdk/blob/c4222503c4571b4b368fea8c4921ed1d5ab8b899/packages/cdktf-cli/bin/cmds/helper/check-environment.ts#L55
=> fix: update specified nodejs version to >=12.16 to reflect our actual requirements

CHANGELOG.md, package.json
- fix(lib): don't treat strings as maps [\#1467](https://github.com/hashicorp/terraform-cdk/pull/1467)
- fix: update specified nodejs version to >=12.16 to reflect our actual requirements [\#1466](https://github.com/hashicorp/terraform-cdk/pull/1466)
- chore: fix constructs error [\#1460](https://github.com/hashicorp/terraform-cdk/pull/1460)
=> chore: release 0.8.6

packages/cdktf-cli/bin/cmds/helper/synth-stack.ts, packages/cdktf-cli/bin/cmds/ui/models/terraform-cloud.ts, packages/cdktf/lib/terraform-asset.ts
I believe this is a Node16 depreciation message:
``` shell
(node:22795) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)
```
I encountered it today when `cdktf` deleted an old stack that was unused. It performed fine, but threw out this error.
=> chore: remove depreciation warning for `fs.rmdir`

CHANGELOG.md, packages/@cdktf/provider-generator/lib/__tests__/__snapshots__/edge-provider-schema.test.ts.snap, packages/@cdktf/provider-generator/lib/__tests__/edge-provider-schema/builder.ts, packages/@cdktf/provider-generator/lib/__tests__/edge-provider-schema/index.ts, packages/@cdktf/provider-generator/lib/get/__tests__/generator/__snapshots__/resource-types.test.ts.snap, packages/@cdktf/provider-generator/lib/get/__tests__/generator/__snapshots__/types.test.ts.snap, packages/@cdktf/provider-generator/lib/get/generator/emitter/attributes-emitter.ts, packages/@cdktf/provider-generator/lib/get/generator/models/attribute-type-model.ts, packages/cdktf/lib/complex-computed-list.ts, packages/cdktf/lib/terraform-data-source.ts, packages/cdktf/lib/terraform-functions.ts, packages/cdktf/lib/terraform-output.ts, packages/cdktf/lib/terraform-resource.ts, packages/cdktf/lib/tokens/private/encoding.ts, packages/cdktf/lib/tokens/private/resolve.ts, packages/cdktf/lib/tokens/private/token-map.ts, packages/cdktf/lib/tokens/resolvable.ts, packages/cdktf/lib/tokens/token.ts, packages/cdktf/test/__snapshots__/resource.test.ts.snap, packages/cdktf/test/helper/resource.ts, packages/cdktf/test/resource.test.ts, test/csharp/edge/Main.cs, test/csharp/edge/test.ts, test/go/edge/main.go, test/java/edge/Main.java, test/java/edge/test.ts, test/python/edge/main.py, test/python/edge/test.ts, test/typescript/edge/main.ts, test/typescript/edge/test.ts
Dividing up #1299, adding token support for `number[]`.
Combines the concepts from `number` and `string[]` tokens by using a single element array using a subset of the available bits as a marker for the token.
=> feat(lib): number[] Tokens

packages/@cdktf/provider-generator/lib/__tests__/__snapshots__/edge-provider-schema.test.ts.snap, packages/@cdktf/provider-generator/lib/__tests__/edge-provider-schema/index.ts, packages/@cdktf/provider-generator/lib/get/__tests__/generator/__snapshots__/complex-computed-types.test.ts.snap, packages/@cdktf/provider-generator/lib/get/__tests__/generator/__snapshots__/resource-types.test.ts.snap, packages/@cdktf/provider-generator/lib/get/__tests__/generator/__snapshots__/types.test.ts.snap, packages/@cdktf/provider-generator/lib/get/generator/emitter/attributes-emitter.ts, packages/@cdktf/provider-generator/lib/get/generator/models/attribute-model.ts, packages/@cdktf/provider-generator/lib/get/generator/models/attribute-type-model.ts, packages/@cdktf/provider-generator/lib/get/generator/module-generator.ts, packages/@cdktf/provider-generator/lib/get/generator/resource-parser.ts, packages/cdktf/lib/complex-computed-list.ts, packages/cdktf/lib/tokens/private/resolve.ts, test/python/providers/__snapshots__/test.ts.snap, test/typescript/edge/main.ts, test/typescript/edge/test.ts
Before this PR the CDK for Terraform treated sets as arrays. While this works when setting data (e.g. passing `["something"]` to a resource argument of the type `set(string)`) accessing that data can have unexpected consequences. For example using `Fn.element(list, index)` does not work on set types. This was not visible from the API we generated (as we exposed all sets as "array of something"). This PR tries to improve the current state by explicitly wrapping references to set type attributes with `Fn.tolist()` which enables `Fn.element()` to work. This is only a first intermediate step until JSII has supports for sets ([issue](https://github.com/aws/jsii/issues/1)) so that we can model them properly in all target languages.
Resolves #992.
=> feat(lib): Initial improvements for set support

packages/cdktf-cli/bin/cmds/convert.ts, packages/cdktf-cli/bin/cmds/deploy.ts, packages/cdktf-cli/bin/cmds/destroy.ts, packages/cdktf-cli/bin/cmds/diff.ts, packages/cdktf-cli/bin/cmds/get.ts, packages/cdktf-cli/bin/cmds/handlers.ts, packages/cdktf-cli/bin/cmds/helper/init-templates.ts, packages/cdktf-cli/bin/cmds/helper/init.ts, packages/cdktf-cli/bin/cmds/helper/utilities.ts, packages/cdktf-cli/bin/cmds/init.ts, packages/cdktf-cli/bin/cmds/list.ts, packages/cdktf-cli/bin/cmds/login.ts, packages/cdktf-cli/bin/cmds/synth.ts, packages/cdktf-cli/bin/cmds/watch.ts, packages/cdktf-cli/build.ts, packages/cdktf-cli/lib/server/index.ts, packages/cdktf-cli/lib/util.ts, packages/cdktf-cli/package.json
Speed up shell autocompletions by pulling actual handler code into
a separate entrypoint which is only required when it is going to be
invoked. When testing this sped up shell completions by 6x (from
1.2s to 0.2s [locally on OS X]). The main reason seemed to be e.g.
the React package required by e.g. ink which is deffered into a
separate bundle / entrypoint now. Also `inquirer` seems to have been
quite a burden (used in `init`).
Closes #1039
=> fix(cli): speed up shell autocompletions

test/typescript/modules/__snapshots__/test.ts.snap, test/typescript/modules/local-module/main.tf, test/typescript/modules/main.ts
#1415 already enabled support for `set` types in modules (by treating them as arrays, which works as Terraform represents sets as arrays as well).
This test confirms that we render set types as arrays and thereby closes #928
=> feat(tests): add test which confirms that modules now support sets

packages/cdktf/lib/terraform-data-source.ts, packages/cdktf/lib/terraform-local.ts, packages/cdktf/lib/terraform-module.ts, packages/cdktf/lib/terraform-output.ts, packages/cdktf/lib/terraform-remote-state.ts, packages/cdktf/lib/terraform-resource.ts, packages/cdktf/lib/terraform-variable.ts, packages/cdktf/lib/tfExpression.ts, packages/cdktf/test/app.test.ts, packages/cdktf/test/helper/resource.ts, packages/cdktf/test/resource.test.ts
=> fix(lib): resolve objects correctly in cross stack references

packages/cdktf/lib/terraform-functions.ts, packages/cdktf/test/functions.test.ts
Hey there, 👋
we had problems regarding the double quote escape check when giving a windows-like path to `Fn.templatefile()`. Interestingly, there wasn't even a double quote in the string: `C:\\Users\\someuser\\somepath`
I'm not sure I completely understand the logic behind hasUnescapedDoubleQuotes, but I created a different attempt at the regex:
* takes escaped backslashes into consideration (infinitely)
* Takes begin-of-file into consideration
I also added a few more tests regarding this. My tests are more dynamic and since I tried to stick with your current testing layout, I had to use some replaces to modify the expected value.
=> fix: stringValue rated valid strings as unescaped double quotes

CHANGELOG.md, package.json
- feat(cli): show help when no command is passed [\#1540](https://github.com/hashicorp/terraform-cdk/pull/1540)
- fix(tests): run package before running unit tests in release pipelines [\#1563](https://github.com/hashicorp/terraform-cdk/pull/1563)
- fix(hcl2cdk): handle no providers passed and add cdktf import for remote state data sources [\#1561](https://github.com/hashicorp/terraform-cdk/pull/1561)
- fix(cli): Fix template for Go not adding jsii import when using Terraform Cloud [\#1556](https://github.com/hashicorp/terraform-cdk/pull/1556)
- fix(lib): Add missing regex Function [\#1531](https://github.com/hashicorp/terraform-cdk/pull/1531)
- fix(cli): add better messaging on inint [\#1524](https://github.com/hashicorp/terraform-cdk/pull/1524)
- fix(docs): fix a typo in …
=> chore: release 0.9.1

CHANGELOG.md
- fix: cross-stack references in terraform cloud remote execution mode [\#1574](https://github.com/hashicorp/terraform-cdk/pull/1574)
- chore: npm-check-updates && yarn upgrade [\#1579](https://github.com/hashicorp/terraform-cdk/pull/1579)
- chore: npm-check-updates && yarn upgrade [\#1565](https://github.com/hashicorp/terraform-cdk/pull/1565)
=> chore: release 0.9.2

CHANGELOG.md, package.json
- feat(examples): Add Scaleway Golang example [\#1576](https://github.com/hashicorp/terraform-cdk/pull/1576)
- fix(cli): convert failed with a single provider passed [\#1588](https://github.com/hashicorp/terraform-cdk/pull/1588)
- fix(tests): Windows needs special docker host override to work [\#1567](https://github.com/hashicorp/terraform-cdk/pull/1567)
=> chore: release 0.9.3

packages/cdktf-cli/test/cmds/convert.test.ts
The output is `The following providers are missing schema information and might need manual adjustments to synthesize correctly: null.`. The dot in the end made they assertion not matched.
=> chore(cli): fix typo in test assertion

packages/cdktf/lib/tfExpression.ts, packages/cdktf/lib/tokens/token.ts, packages/cdktf/test/functions.test.ts
in JS typeof null === 'object' => true so we need an explicit check for null
also adds a testcase for this fix
=> fix(lib): check for null objects and don't try to reverse undefined or null

packages/cdktf-cli/bin/cdktf, packages/cdktf-cli/bin/cmds/helper/check-environment.ts, packages/cdktf-cli/bin/cmds/helper/terraform-check.ts, packages/cdktf-cli/bin/cmds/ui/hooks/cdktf-project.ts, packages/cdktf-cli/lib/ambient.d.ts, packages/cdktf-cli/lib/index.ts, packages/cdktf-cli/lib/models/terraform-cli.ts, packages/cdktf-cli/lib/models/terraform-cloud.ts, packages/cdktf-cli/lib/project-execution.ts, packages/cdktf-cli/lib/server/WatchClient.ts, packages/cdktf-cli/lib/synth-stack.ts, packages/cdktf-cli/package.json, packages/cdktf-cli/test/lib/project-execution.test.ts, yarn.lock
This PR ensures that when we receive a termination signal we stop all corresponding node processes. I'd consider it out of scope to stop / delete terraform cloud runs. I'm not even sure if stopping requests for TFC is worth it.
Closes #771
You can see in the watch tab below how the terraform apply command is aborted
Created https://github.com/hashicorp/terraform-cdk/issues/1607 as follow up to abort TFC runs
=> feat(cli): properly shutdown subprocesses on abort

packages/cdktf-cli/bin/cmds/handlers.ts, packages/cdktf-cli/bin/cmds/output.ts, packages/cdktf-cli/bin/cmds/ui/output.tsx, packages/cdktf-cli/lib/cdktf-project.ts, packages/cdktf-cli/lib/cdktf-stack.ts, website/docs/cdktf/cli-reference/commands.mdx
This should help users getting outputs on their stacks quicker. As outputs fetch the last state from the Terraform State there is no special order to take
=> feat(cli): allow multiple stacks in the output command

packages/cdktf-cli/lib/cdktf-stack.ts, packages/cdktf-cli/lib/stack-execution.ts
Originally I wanted to make the cdktf-project class functional, but it was harder than anticipated with not enough benefit in readability. This PR now only removes a status object we had in place for compatibility while moving to the streaming log view.
=> chore(cli): remove deploying resource overview

packages/cdktf-cli/bin/cmds/handlers.ts
=> feat(cli): throw clearer error if --from-terraform-project misses an arg

packages/cdktf-cli/bin/cmds/helper/init.ts, packages/cdktf-cli/lib/cdktf-stack.ts, packages/cdktf-cli/lib/models/schema.ts, packages/cdktf-cli/lib/models/terraform-cli.ts, packages/cdktf-cli/lib/models/terraform-cloud.ts, packages/cdktf-cli/lib/models/terraform.ts, packages/cdktf-cli/lib/output.ts, packages/cdktf-cli/lib/server/terraform-logs.ts, packages/cdktf-cli/lib/stack-execution.ts, packages/cdktf-cli/test/lib/stack-execution.test.ts, packages/cdktf-cli/test/lib/terraform-logs.test.ts
This PR makes sure we clean up what we leave behind in TFC when we run apply / destroy.
Closes #1607 and #482
=> feat(cli): stop TFC plans when we discard / stop / ctrl-c

packages/@cdktf/provider-generator/lib/__tests__/__snapshots__/edge-provider-schema.test.ts.snap, packages/@cdktf/provider-generator/lib/get/__tests__/__snapshots__/read-schema.test.ts.snap, packages/@cdktf/provider-generator/lib/get/__tests__/generator/__snapshots__/provider.test.ts.snap, packages/@cdktf/provider-generator/lib/get/generator/emitter/resource-emitter.ts, packages/@cdktf/provider-generator/lib/get/generator/models/resource-model.ts, packages/@cdktf/provider-generator/lib/get/generator/provider-generator.ts, packages/@cdktf/provider-generator/lib/get/generator/provider-schema.ts, packages/cdktf/lib/terraform-provider.ts, packages/cdktf/lib/terraform-resource.ts, test/csharp/synth-app/__snapshots__/test.ts.snap, test/go/synth-app/__snapshots__/test.ts.snap, test/java/synth-app/__snapshots__/test.ts.snap, test/python/asset/__snapshots__/test.ts.snap, test/python/multiple-stacks/__snapshots__/test.ts.snap, test/python/providers/__snapshots__/test.ts.snap, test/python/synth-app/__snapshots__/test.ts.snap, test/python/terraform-functions/__snapshots__/test.ts.snap, test/typescript/feature-flags/__snapshots__/test.ts.snap, test/typescript/multiple-stacks/__snapshots__/test.ts.snap, test/typescript/synth-app/__snapshots__/test.ts.snap
Fixes #684
Fixes #228
Fixes #318
Fixes #43
The exact version of the resolved provider is now recorded as metadata for the generated provider and resources. For the provider, this exact version is used in `required_providers` block to ensure a consistent experience and give users more control over the provider version used.
Also omitting version constraints when either is undefined.
=> chore(provider-generator): Include Provider Version in Generated Bindings

CHANGELOG.md, package.json, tools/create-changelog.sh
**Breaking Changes**
If you are using `cdktf synth --json <stack-name>` to get the synthesized JSON configuration for your Stack, you will now need to run `cdktf synth && cat ./cdktf.out/stacks/<stack-name>/cdk.tf.json` instead. The `./cdktf.out` part is your output directory (set by `cdktf.json` or via the `--output` flag).
In an effort to streamline the interfaces of resources, computed attributes of the type list and set are now modeled as a separate `ComplexList` type instead of being a method that directly takes an index and returns an item. This change also did change the type of the index from `string` to `number`.
```ts
// previously
const firstItemId = resource.listAttribute("0").id;
// new
const firstItemId = resource.listAttribute.get(0).id;
const firstItem = …
```
=> chore(release): 0.10.0

CHANGELOG.md, package.json
- fix(cli): fix convert single blocks as array bug [\#1680](https://github.com/hashicorp/terraform-cdk/pull/1680)
- fix(cli): Only print error that's thrown [\#1678](https://github.com/hashicorp/terraform-cdk/pull/1678)
- refactor(tests): move from table driven tests to functional way [\#1679](https://github.com/hashicorp/terraform-cdk/pull/1679)
- refactor(cli): remove xstate as state machine [\#1670](https://github.com/hashicorp/terraform-cdk/pull/1670)
- chore(docs): update project maturity statement [\#1676](https://github.com/hashicorp/terraform-cdk/pull/1676)
- chore(docs): add sidebar link [\#1674](https://github.com/hashicorp/terraform-cdk/pull/1674)
- chore: add extra column for PRs outside our main repo [\#1673](https://github.com/hashicorp/terraform-cdk/pull/1673)
- feat(cli): …
=> chore(release): 0.10.1

packages/cdktf-cli/bin/cdktf.ts, packages/cdktf-cli/bin/cmds/convert.ts, packages/cdktf-cli/bin/cmds/deploy.ts, packages/cdktf-cli/bin/cmds/destroy.ts, packages/cdktf-cli/bin/cmds/diff.ts, packages/cdktf-cli/bin/cmds/get.ts, packages/cdktf-cli/bin/cmds/handlers.ts, packages/cdktf-cli/bin/cmds/helper/base-command.ts, packages/cdktf-cli/bin/cmds/init.ts, packages/cdktf-cli/bin/cmds/list.ts, packages/cdktf-cli/bin/cmds/login.ts, packages/cdktf-cli/bin/cmds/output.ts, packages/cdktf-cli/bin/cmds/synth.ts, packages/cdktf-cli/bin/cmds/watch.ts, packages/cdktf-cli/lib/errors.ts, packages/cdktf-cli/package.json, yarn.lock
- chore(deps): update yargs type defs
- fix(cli): be explicit about yargs not exiting the process on failure
- fix(cli): make stack positional argument optional
- fix(cli): exit the process on uncaught errors from yargs handlers
- fix(cli): throw Usage error instead of local process.exit()
- refactor(cli): Don't catch errors locally in command handlers as they are now caught properly on a global level in .fail()
=> fix(cli): improve cli error handling

packages/cdktf-cli/lib/models/terraform-cloud.ts
previously this always tried to delete e.g. `cdktf.out/stacks/a/cdk.tf.json/.terraform` which probably always failed.
Related to #1470.
=> fix(cli): fix path for `.terraform` directory

.github/workflows/integration.yml, packages/cdktf-cli/lib/init.ts
Aligning the versions to the current cdktf version misleads pypi to verify the published sha of the package is the same as the one we install locally. Using an unpublished version (by adding a suffix) will ensure this check can never find a version to compare against.
=> chore: align versions to an unpublished version

packages/cdktf-cli/bin/cmds/handlers.ts, packages/cdktf-cli/bin/cmds/helper/check-environment.ts
This often a point of confiusion, especially if one accidentally updates the CLI and wonders why the previously working cdktf program does not work anymore
=> feat(cli): warn users about misaligned CLI and library versions

CHANGELOG.md, package.json
- fix(tests): pin awscc version [\#1727](https://github.com/hashicorp/terraform-cdk/pull/1727)
- fix(cli): return non-zero exit code in case of error when using cdktf diff [\#1726](https://github.com/hashicorp/terraform-cdk/pull/1726)
- fix(cli): allow init command to run in a directory containing a README.md [\#1722](https://github.com/hashicorp/terraform-cdk/pull/1722)
- fix(provider-generator): Include "arn" when assignable [\#1716](https://github.com/hashicorp/terraform-cdk/pull/1716)
- fix(hcl2cdk): detect list extensions in strings and wrap them in an array [\#1707](https://github.com/hashicorp/terraform-cdk/pull/1707)
- fix(lib): override values containing intrinsic tokens caused an infinite loop [\#1702](https://github.com/hashicorp/terraform-cdk/pull/1702)
- fix(lib): …
=> chore: release 0.10.2

packages/cdktf-cli/templates/csharp/.hooks.sscaff.js, packages/cdktf-cli/templates/java/.hooks.sscaff.js
- fix(cli): fix indentation of RemoteBackend in CSharp template
- fix(cli): fix indentation of RemoteBackend in Java template
Closes #1494
=> fix(cli): Fix indentation of RemoteBackend in CSharp and Java template

packages/cdktf-cli/lib/cdktf-project.ts
When deploying stacks and we wait for approvals, if there have been stacks in a waiting for approval state we need to clear them out of our buffer if we stop all stacks, otherwise users need to click through them individually and might even allow individual stacks to be deployed by approving them.
=> fix(cli): we should not send wait for approval if a stop has been issued

packages/@cdktf/provider-generator/lib/get/generator/custom-defaults.ts
**Fixes**: [cdktf_cdktf_provider_aws.vpc.RouteTableRoute requires core_network_arn](https://github.com/hashicorp/terraform-cdk/issues/1748)
Followed the logic used to address a similar issue in this PR:
https://github.com/hashicorp/terraform-cdk/pull/821/files
=> fix(lib): Add new optional AWS route attributes

CHANGELOG.md, package.json
- feat(provider-generator): emit a versions.json file to the output directory, containing the used provider versions [\#1749](https://github.com/hashicorp/terraform-cdk/pull/1749)
- feat(cli): debug command [\#1731](https://github.com/hashicorp/terraform-cdk/pull/1731)
- chore(cli): add environment variable to disable version checks [\#1757](https://github.com/hashicorp/terraform-cdk/pull/1757)
- chore: drop Terraform v0.15.7 from Docker image and replace with v1.1.9 for running tests [\#1747](https://github.com/hashicorp/terraform-cdk/pull/1747)
- chore: add Terraform v1.1.9 to Docker image [\#1743](https://github.com/hashicorp/terraform-cdk/pull/1743)
- chore(docs): update env var usage [\#1693](https://github.com/hashicorp/terraform-cdk/pull/1693)
- fix(lib): Add new optional AWS route …
=> feat(release): Release 0.10.3

.github/workflows/release.yml, .github/workflows/release_next.yml
aligns with ci that runs on PR (and already does this)
=> fix(release): Use non default terraform versions as specified in test matrix for Release and Release Next workflows

website/docs/cdktf/cli-reference/commands.mdx
The examples for the `convert` command included an extra "\`", and one of the examples is a duplicate.
=> chore(docs): remove extra punctuation and duplicate example

packages/cdktf-cli/templates/typescript/.hooks.sscaff.js
upstream issue has been resolved by now and the fixed version currently fails initializing a cdktf project as ts-node requires a newer version
Related to #1766
=> fix(cli): Stop pinning jest in TS init template

packages/cdktf/lib/backends/s3-backend.ts
Have added doc-string to s3 backend. 
Working on issue -[https://github.com/hashicorp/terraform-cdk/issues/1268]( https://github.com/hashicorp/terraform-cdk/issues/1268)
=> feat(lib): add docstrings to S3 backend resource

packages/cdktf/lib/terraform-data-source.ts, packages/cdktf/lib/terraform-element.ts, packages/cdktf/lib/terraform-local.ts, packages/cdktf/lib/terraform-module.ts, packages/cdktf/lib/terraform-remote-state.ts, packages/cdktf/lib/terraform-resource.ts, packages/cdktf/lib/terraform-variable.ts, packages/cdktf/test/resource.test.ts
Hi,
when using `dependsOn` to depend on a resource with overwritten logical id, the fqn does not fit the resource anymore, as it is generated within the constructor. I took an approach to stabilizing the fqn and also avoiding potential problems when using the fqn before changing the id.
This change might be a breaking change.
Let me know if you need any more infos!
=> fix: Avoid unstable fqn for TerraformElements

packages/cdktf/lib/backends/artifactory-backend.ts, packages/cdktf/lib/backends/azurerm-backend.ts, packages/cdktf/lib/backends/consul-backend.ts
Have added doc-string to artifactory,azurerm and consul backend resources
Working on issue - [https://github.com/hashicorp/terraform-cdk/issues/1268](https://github.com/hashicorp/terraform-cdk/issues/1268)
=> feat(lib): add docstrings to artifactory/azurerm/consul backend resources

packages/@cdktf/provider-generator/lib/get/__tests__/generator/__snapshots__/complex-computed-types.test.ts.snap, packages/@cdktf/provider-generator/lib/get/__tests__/generator/__snapshots__/resource-types.test.ts.snap, packages/@cdktf/provider-generator/lib/get/__tests__/generator/__snapshots__/types.test.ts.snap, packages/@cdktf/provider-generator/lib/get/generator/emitter/struct-emitter.ts, packages/@cdktf/provider-generator/lib/get/generator/models/attribute-model.ts, packages/@cdktf/provider-generator/lib/get/generator/models/struct.ts
We ignored fields in the past to not expose fields incorrectly, which has been a good approach with the provider generator being work in progress
Now that it's more stable we can leave these guards behind and if issues arise we can try to fix them upstream in the respective providers
Closes #1602
=> fix(provider-generator): strictly adhere to the provider schema

packages/cdktf/lib/util.ts, packages/cdktf/test/runtime.test.ts
Closes #1788
Closes #910 
Closes #835
=> test(lib): ensure list mapper does not fail when passed IResolvables

packages/cdktf/lib/backends/gcs-backend.ts, packages/cdktf/lib/backends/http-backend.ts, packages/cdktf/lib/backends/local-backend.ts
Have added doc-string to gcs,http,local backend resources.
Working on issue - https://github.com/hashicorp/terraform-cdk/issues/1268
=> feat(lib): add docstrings to gcs/http/local backend resources

packages/cdktf/lib/complex-computed-list.ts, test/typescript/providers/cdktf.json
Closes #1656
#1779 introduced changes to fix #1656; however, #1725 made those fixes no longer work in all cases. This fixes that by applying a similar technique as the original fix.
=> fix(lib): Delay complex object fqn so that override id can still be used

.github/workflows/release.yml, .github/workflows/release_next.yml, packages/@cdktf/hcl2cdk/test/hcl2cdk.test.ts, packages/cdktf-cli/bin/cdktf.ts, packages/cdktf-cli/bin/cmds/handlers.ts, packages/cdktf-cli/bin/cmds/helper/init.ts, packages/cdktf-cli/bin/cmds/init.ts, packages/cdktf-cli/build.ts, packages/cdktf-cli/lib/checkpoint.ts, packages/cdktf-cli/lib/debug.ts, packages/cdktf-cli/lib/error-reporting.ts, packages/cdktf-cli/lib/errors.ts, packages/cdktf-cli/lib/init.ts, packages/cdktf-cli/lib/logging.ts, packages/cdktf-cli/package.json, packages/cdktf-cli/templates/csharp/cdktf.json, packages/cdktf-cli/templates/go/cdktf.json, packages/cdktf-cli/templates/java/cdktf.json, packages/cdktf-cli/templates/python-pip/cdktf.json, packages/cdktf-cli/templates/python/cdktf.json, packages/cdktf-cli/templates/typescript/cdktf.json, packages/cdktf-cli/test/lib/cdktf-project.test.ts, test/test-helper.ts, website/docs/cdktf/cli-reference/commands.mdx, website/docs/cdktf/create-and-deploy/configuration-file.mdx, website/docs/cdktf/telemetry.mdx, yarn.lock
Adding crash reporting will help us improve the product faster 🎉
=> chore(cli): add sentry error reporting

website/docs/cdktf/create-and-deploy/best-practices.mdx
This PR fixes code blocks in the `Create and Deploy > Best Practices > Read Secrets with Terraform Variables` [documentation](https://www.terraform.io/cdktf/create-and-deploy/best-practices#read-secrets-with-terraform-variables). Below is an image of the current documentation.
=> fix(docs): fix code blocks in "create and deploy" documentation

packages/cdktf-cli/lib/debug.ts, packages/cdktf-cli/lib/dependencies/dependency-manager.ts, test/csharp/provider-add-command/test.ts, test/go/edge/test.ts, test/go/provider-add-command/cdktf.json, test/go/provider-add-command/main.go, test/go/provider-add-command/test.ts, test/java/provider-add-command/test.ts, test/python/provider-add-command/test.ts, test/test-helper.ts, test/typescript/provider-add-command/test.ts
For at least c#, the package version lookup is failing on Windows due to line endings. I went ahead and change the other languages as well.
I believe this is at least partially contributing to #1816.
=> fix(cli): Fix package version check on Windows

website/docs/cdktf/create-and-deploy/best-practices.mdx, website/docs/cdktf/create-and-deploy/environment-variables.mdx
- Put environment variables in a table and revise language
=> chore(docs): Fix Environment Variables and Best Practices 

packages/cdktf-cli/bin/cmds/handlers.ts, packages/cdktf-cli/bin/cmds/helper/init.ts, packages/cdktf-cli/bin/cmds/helper/terraform-cloud-client.ts, packages/cdktf-cli/bin/cmds/helper/terraform-login.ts, packages/cdktf-cli/bin/cmds/helper/utilities.ts, packages/cdktf-cli/bin/cmds/login.ts, packages/cdktf-cli/lib/models/terraform-cloud.ts, packages/cdktf-cli/package.json, website/docs/cdktf/cli-reference/commands.mdx, yarn.lock
This PR also ships support for logging into terraform enterprise instances as well as logging in by passing a token through stdin.
Closes #1854
=> feat(cli): support custom Terraform Enterprise instances

packages/cdktf/lib/terraform-resource.ts
ignoreChanges can be "all" ignoring all changes. This has to be reflected by the type (if that's true for all resources?).
Closes #1425
=> fix: Allow "all" as ignoreChanges lifecycle value

CONTRIBUTING.md, README.md
Update prerequisites (go version 1.18 is not working)
=> chore: update prerequisites

packages/@cdktf/provider-generator/lib/get/__tests__/constructs-maker.test.ts, packages/@cdktf/provider-generator/lib/get/constructs-maker.ts
=> fix(provider-generator): replace dashes with underscores in module names for Go when generating bindings for Terraform modules

CONTRIBUTING.md, website/README.md
Adjusts the website README in preparation for the versioning rollout. Also adds a link to the website README in the `CONTRIBUTING.md` file.
=> feat(docs): update website README for versioning

packages/@cdktf/provider-generator/lib/get/generator/emitter/struct-emitter.ts, packages/@cdktf/provider-generator/lib/get/generator/loop-detection.ts, packages/@cdktf/provider-generator/lib/get/generator/models/resource-model.ts, packages/@cdktf/provider-generator/lib/get/generator/resource-parser.ts
The provider schema can have a logical recursion that is due to JSONs staticness
transcribed by repeating the recursive struct n times. This blows up our generated provider
bindings to a degree where we can no longer built go in github action runners.
To fix this we now detect the recursion and use recursive references in Typescript.
=> fix(provider-generator): remove "recursion" from generated code

.github/ISSUE_TEMPLATE/config.yml
One of the issues I triaged earlier made me think that we can make it a little easier for users to find a place to ask usage questions other than by posting to GitHub. I looked to see how TF-Core does this and it looks like this YAML config file allows you to add these extra links: https://github.com/hashicorp/terraform/blob/main/.github/ISSUE_TEMPLATE/config.yml
I also copied over the TFC/E support option now that we're gearing up to provide full commercial support.
Open question: are we okay with disabling blank issues? (Seems like a good thing to me, but let me know if y'all disagree.)
=> chore: add redirects to forum & support in GitHub

website/docs/cdktf/concepts/aspects.mdx
=> fix(docs): fix aspects example not being valid TypeScript

packages/cdktf-cli/lib/cdktf-project.ts, packages/cdktf-cli/lib/util.ts, packages/cdktf-cli/test/lib/cdktf-project.test.ts, packages/cdktf-cli/test/lib/fixtures/parallel-error/main.ts.fixture
- chore: replicate deployment bug
- fix(cli): fix test as planning steps have no ensured order
- fix(cli): Wait for other work promises to complete even if one of them failed, which causes .race and .all to short circuit
Closes #1836
=> fix(cli): Wait for other stacks to complete if one of them failed

packages/cdktf/lib/testing/matchers.ts
The test matcher `toPlanSuccessfully` executes a full Terraform plan which needs to look at potentially locked remote state.
This locks the state and interferes with tests running in parallel etc.
On the other hand, disabling the locking in tests should have no negative affect.
Hence the PR.
=> fix: don't lock state in tests

packages/cdktf-cli/lib/debug.ts, packages/cdktf-cli/templates/typescript/tsconfig.json
=> fix(cli): fix version detection for Java being a bit too optimistic about the package name

packages/cdktf-cli/lib/debug.ts, packages/cdktf-cli/lib/dependencies/package-manager.ts, test/go/provider-add-command/test.ts, test/test-helper.ts
=> fix(cli): add major versions greater 1 to package name when installing pre-built providers for go

.github/workflows/docker.yml, .github/workflows/examples.yml, .github/workflows/integration.yml, .github/workflows/release.yml, .github/workflows/release_next.yml, .github/workflows/unit.yml, cdk.tf/README.md, cdk.tf/vercel.json
Migrates the configuration of cdk.tf redirects into our main repository (into a new root level dir called `cdk.tf` which we could e.g. use for a landing page in the future as well).
Example link: https://terraform-cdk-redirects.vercel.app/docs
=> chore: add vercel config for cdk.tf redirects page

packages/cdktf-cli/templates/java/cdktf.json
=> fix(cli): get in java should not create an empty .gen folder

CONTRIBUTING.md
Useful if c# examples don't use the latest locally built cdktf package
=> chore: add notes for how to clean the local dotnet cache

packages/@cdktf/hcl2json/package.json
Currently, fs-extra is not defined in the `dependencies` block of `hcl2json`: https://github.com/hashicorp/terraform-cdk/blob/ae0d4901e0260d88752e364f246a82ce70af4e8f/packages/%40cdktf/hcl2json/package.json#L31-L42
This causes a runtime error with the default `yarn` berry PnP linker:
```
/tmp  mkdir tfcdk-demo
/tmp  cd tfcdk-demo
/tmp/tfcdk-demo  yarn set version berry
➤ YN0000: Retrieving https://repo.yarnpkg.com/3.2.2/packages/yarnpkg-cli/bin/yarn.js
➤ YN0000: Saving the new release in .yarn/releases/yarn-3.2.2.cjs
➤ YN0000: Done in 0s 357ms
/tmp/tfcdk-demo  yarn init
{
name: 'tfcdk-demo',
packageManager: 'yarn@3.2.2'
}
/tmp/tfcdk-demo   main  yarn add -D cdktf-cli@next
➤ YN0000: ┌ Resolution step
➤ YN0060: │ @cdktf/hcl2cdk@npm:0.13.0-pre.19 provides graphology-types (pb9009) …
```
=> fix(hcl2json): add fs-extra to dependencies

packages/cdktf-cli/lib/dependencies/prebuilt-providers.ts
fixes 'datadog/datadog' not working (only 'DataDog/datadog' worked previously)
=> fix(cli): Make provider add command case insensitive for provider names

examples/python/provisioner/Pipfile.lock, packages/cdktf-cli/lib/synth-stack.ts, website/docs/cdktf/api-reference/csharp.mdx, website/docs/cdktf/api-reference/go.mdx, website/docs/cdktf/api-reference/java.mdx, website/docs/cdktf/api-reference/python.mdx, website/docs/cdktf/api-reference/typescript.mdx, website/docs/cdktf/cli-reference/commands.mdx, website/docs/cdktf/concepts/aspects.mdx, website/docs/cdktf/concepts/assets.mdx, website/docs/cdktf/concepts/cdktf-architecture.mdx, website/docs/cdktf/concepts/constructs.mdx, website/docs/cdktf/concepts/data-sources.mdx, website/docs/cdktf/concepts/functions.mdx, website/docs/cdktf/concepts/hcl-interoperability.mdx, website/docs/cdktf/concepts/iterators.mdx, website/docs/cdktf/concepts/modules.mdx, website/docs/cdktf/concepts/providers.mdx, website/docs/cdktf/concepts/remote-backends.mdx, website/docs/cdktf/concepts/resources.mdx, website/docs/cdktf/concepts/stacks.mdx, website/docs/cdktf/concepts/variables-and-outputs.mdx, website/docs/cdktf/create-and-deploy/aws-adapter.mdx, website/docs/cdktf/create-and-deploy/configuration-file.mdx, website/docs/cdktf/create-and-deploy/project-setup.mdx, website/docs/cdktf/create-and-deploy/remote-templates.mdx, website/docs/cdktf/examples.mdx, website/docs/cdktf/release/upgrade-guide-v0-10.mdx, website/docs/cdktf/test/unit-tests.mdx
We should not use positional language (above, below, etc.) in our documentation. This is something we did frequently early on, but that we should fix now for consistency with other documentation. This PR removes positional language and fixes a few other tiny style nits (like passive voice) that I found along the way.
The preferred way to introduce code examples is:
"The following example..."
This is good as long as the code immediately follows this explanatory sentence. We should do this in the future instead of saying "the example below."
=> chore(docs): Remove positional language + fix style nits

packages/cdktf/lib/backends/s3-backend.ts
=> fix(lib): Add missing config options for S3Backend: skipRegionValidation, assumeRolePolicyArns, assumeRoleTags, and assumeRoleTransitiveTagKeys

cdk.tf/vercel.json, packages/cdktf-cli/bin/cmds/init.ts, website/docs/cdktf/cli-reference/commands.mdx, website/docs/cdktf/concepts/assets.mdx, website/docs/cdktf/concepts/constructs.mdx, website/docs/cdktf/concepts/stacks.mdx, website/docs/cdktf/create-and-deploy/project-setup.mdx, website/docs/cdktf/examples.mdx, website/docs/cdktf/index.mdx
Docs changes to support migration to devdot. Updated with the following goals:
- Remove "Learn" and "Collection" as a term from docs
- Remove references to docs nav itself
- Remove user-facing URLs that contain the learn or docs domain ([learn.hashicorp.com](https://learn.hashicorp.com/) or [terraform.io](https://terraform.io/)/docs)
-----
**TODO** - [init command help output](https://www.terraform.io/cdktf/cli-reference/commands#init) has a direct link to terraform.io, which will be inaccurate in the future. Laura to get the actual URl so it can be changed in the docs and in the actual code
=> chore(docs): Update Docs for DevDot Migration

CHANGELOG.md, package.json, website/docs/cdktf/api-reference/csharp.mdx, website/docs/cdktf/api-reference/go.mdx, website/docs/cdktf/api-reference/java.mdx, website/docs/cdktf/api-reference/python.mdx, website/docs/cdktf/api-reference/typescript.mdx
**Breaking Changes**
A very minor change in the interface names for provisioners occured [to support them in JSII languages](https://github.com/hashicorp/terraform-cdk/pull/2042), renaming the following interfaces:
- `ISSHProvisionerConnection` to `SSHProvisionerConnection`
- `IWinrmProvisionerConnection` to `WinrmProvisionerConnection`
- `IFileProvisioner` to `FileProvisioner`
- `ILocalExecProvisioner` to `LocalExecProvisioner`
- `IRemoteExecProvisioner` to `RemoteExecProvisioner`
Another very minor change is that we now use the `CloudBackend` by default when running cdktf init. This requires Terraform >=1.1, therefore an error is thrown on `cdktf init` if you want to use Terraform Cloud and are on an older version. Already existing projects are not affected and you can use `cdktf init …
=> chore: release 0.12.2

packages/cdktf-cli/lib/server/terraform-logs.ts, packages/cdktf-cli/test/lib/terraform-logs.test.ts
Previously, the output of Terraform was flattened, removing indentation of non-json output.
Before: 
with:
- I was not able to try out a proper structured output run, as speculative runs on TF Cloud also are non-json. Maybe I can get some help with testing?
=> chore(cli): Don't trim output for unstructured logs

packages/cdktf-cli/package.json, yarn.lock
updates the TFC API client which had this limit increased in https://github.com/skorfmann/terraform-cloud/pull/10
Closes #2106
I tested this locally using the dev build of the CLI with a project deploying three lambda functions that are resulting in a large archive that is uploaded to TFC for remote execution (it "failed successfully" without the change 😁).
I don't think it makes sense to add a test that uploads large files to TFC.
=> fix(cli): support using remote execution in Terraform Cloud with up to 500 MB (instead of 10MB)

packages/cdktf-cli/templates/python/.hooks.sscaff.js
Hello
Currently, following message are shown if `pipenv` is not install, to use python
```
$ cdktf init --template python --local
Note: By supplying '--local' option you have chosen local storage mode for storing the state of your stack.
This means that your Terraform state file will be stored locally on disk in a file 'terraform.<STACK NAME>.tfstate' in the root of your project.
...
Unable to find "pipenv". Install from https://pipenv.kennethreitz.org
```
But I couldn't access to `https://pipenv.kennethreitz.org`(is there someone who can?). I think `https://pipenv.pypa.io/` is the correct one. Could you check?
=> fix: Change url of `pipenv` in log

cdk.tf/vercel.json, packages/cdktf-cli/bin/cmds/init.ts, website/docs/cdktf/cli-reference/commands.mdx, website/docs/cdktf/concepts/assets.mdx, website/docs/cdktf/concepts/constructs.mdx, website/docs/cdktf/concepts/stacks.mdx, website/docs/cdktf/create-and-deploy/project-setup.mdx, website/docs/cdktf/examples.mdx, website/docs/cdktf/index.mdx
We need to migrate the links to exclude the terraform.io part --> that will no longer exist with the devdot migration. This PR is where we can test to make sure the new links we merged into the `dev-portal` branch will work!
=> chore(docs): Check whether links work :) 

packages/cdktf-cli/templates/python-pip/.hooks.sscaff.js
Hello,
When we generate `python-pip` project via template, requirements.txt only includes `pytest` though it also needs `cdktf` package. Looks like this is being overwritten.
Please take a look for this change 🙏
=> fix(cli): Update require package in template

packages/cdktf/lib/backends/azurerm-backend.ts, website/docs/cdktf/api-reference/csharp.mdx, website/docs/cdktf/api-reference/go.mdx, website/docs/cdktf/api-reference/java.mdx, website/docs/cdktf/api-reference/python.mdx, website/docs/cdktf/api-reference/typescript.mdx
Newly added: snapshot, clientCertificatePassword, clientCertificatePath, useMicrosoftGraph, oidcRequestUrl, oidcRequestToken, useOidc, useAzureadAuth
Resolves #2126
=> fix(lib): Add missing config options for AzurermBackend

packages/cdktf-cli/lib/dependencies/dependency-manager.ts, packages/cdktf-cli/lib/dependencies/prebuilt-providers.ts, packages/cdktf-cli/test/lib/dependencies/prebuilt-providers.test.ts
Related to the move of our pre-built providers to the `cdktf` github organization.
Also fixes https://github.com/hashicorp/terraform-cdk/issues/1815
The core intention of the PR is to use some of the information published by projen on the pre-built provider's package.json, especially the 'repository' field, to generate the package module path for Go. This will prevent `cdktf provider add` to be broken as we move the providers to the `cdktf` organization.
=> chore(cli): Use the npm package's repository field for generating go package name

packages/cdktf-cli/bin/cmds/deploy.ts, packages/cdktf-cli/bin/cmds/destroy.ts, packages/cdktf-cli/bin/cmds/diff.ts, packages/cdktf-cli/bin/cmds/handlers.ts, packages/cdktf-cli/bin/cmds/ui/deploy.tsx, packages/cdktf-cli/bin/cmds/ui/destroy.tsx, packages/cdktf-cli/bin/cmds/ui/diff.tsx, packages/cdktf-cli/bin/cmds/ui/watch.tsx, packages/cdktf-cli/bin/cmds/watch.ts, packages/cdktf-cli/lib/cdktf-project.ts, packages/cdktf-cli/lib/cdktf-stack.ts, packages/cdktf-cli/lib/models/terraform-cli.ts, packages/cdktf-cli/lib/models/terraform-cloud.ts, packages/cdktf-cli/lib/models/terraform.ts, packages/cdktf-cli/lib/watch.ts, packages/cdktf-cli/test/lib/cdktf-project.test.ts, packages/cdktf-cli/test/lib/terraform-parallelism.test.ts, website/docs/cdktf/cli-reference/commands.mdx
Fixes #1715 
This PR adds the `-terraform-parallelism` flag to the CLI. This flag is only available for `deploy` and `destroy`. One note here is that due the nature of `deploy`, the parallelism flag will be used for both `plan` and `apply` within the Terraform CLI during the `deploy` operation.
One thing to note: The `parallelism` flag is not supported by Terraform Cloud, so setting that for remote backends will be ignored.
Also, now now have two `parallelism` flags. One is `--parallelism` and the other is `--terraform-parallelism`. The former only affects how `cdktf` processes multiple stacks, while the latter is passed on to the Terraform CLI and changes how many concurrent operations Terraform starts as it walks the graph.
=> feat(cli): Add support for terraform's parallelism flag 

packages/cdktf-cli/lib/dependencies/dependency-manager.ts, packages/cdktf-cli/lib/dependencies/package-manager.ts, packages/cdktf-cli/lib/dependencies/prebuilt-providers.ts, packages/cdktf-cli/test/lib/dependencies/prebuilt-providers.test.ts, test/csharp/provider-add-command/test.ts
The previous implementation assumes that for every released npm version
there is an matching release on the other package managers. This sometimes
is not true, mostly by errors in the publishing process. To hide this and make
the UX of provider add nicer we will deploy the latest compatible matching version.
Closes #2065
=> fix(cli): handle missing package versions for non-npm packages

packages/@cdktf/provider-generator/lib/get/__tests__/__snapshots__/read-schema.test.ts.snap, packages/@cdktf/provider-generator/lib/get/__tests__/fixtures/local-json-module/module.tf.json, packages/@cdktf/provider-generator/lib/get/__tests__/fixtures/local-module/module.tf, packages/@cdktf/provider-generator/lib/get/__tests__/read-schema.test.ts, packages/@cdktf/provider-generator/lib/get/generator/provider-schema.ts
While terraform gives us this format, a hand-written or generated .tf.json file might not have
extra arrays around the values of variables and outputs. This leads to errors when parsing, so
when cdktf get is invoked.
=> fix(provider-generator): don't require arrays wrapping variable / output declarations

website/docs/cdktf/cli-reference/commands.mdx, website/docs/cdktf/concepts/data-sources.mdx, website/docs/cdktf/concepts/remote-backends.mdx, website/docs/cdktf/concepts/resources.mdx, website/docs/cdktf/concepts/variables-and-outputs.mdx, website/docs/cdktf/create-and-deploy/best-practices.mdx, website/docs/cdktf/create-and-deploy/deployment-patterns.mdx, website/docs/cdktf/create-and-deploy/terraform-cloud.mdx, website/docs/cdktf/examples.mdx, website/docs/cdktf/index.mdx, website/docs/cdktf/release/upgrade-guide-v0-11.mdx
This rewrites some markdown links to be their final redirect destinations.
This is in support of the GA Rollout to developer.hashicorp.com
=> chore(docs): rewrite internal redirects

Dockerfile
The old `node14` docker image tag is [now deprecated](https://hub.docker.com/r/jsii/superchain). This PR replaces it with the new recommended docker image tag.
We're seeing errors like the following image in our PRs:
From [this issue](https://github.com/golang/go/issues/51436) it seems like it's related to Go 1.16, which our `hashicorp/jsii-terraform` image was using. Since `jsii/superchain` was already on Go 1.18 already, we realized something's wrong with our docker image, leading us to the discontinued tags.
=> chore(deps): Update docker image to use new jsii/superchain tag

Dockerfile
After #2214, we found out that JSII Superchain image [moved from using Amazon Linux 2 to Debian](https://github.com/aws/jsii/pull/2949). This caused our docker image [build process to fail](https://github.com/hashicorp/terraform-cdk/actions/runs/3296963070/jobs/5437224948#step:7:629). This PR updates to use the package manager `apt` used in Debian instead of `yum`.
=> fix(deps): Use apt instead of yum, since base image is debian based now

.github/workflows/integration.yml, .github/workflows/update-snapshots.yml
Follow up of: https://github.com/hashicorp/terraform-cdk/pull/2214
Upgrades the version of Go in the windows platform integration tests.
=> chore: Update Go to version 1.18 on windows workflows

cdk.tf/vercel.json
Apparently not having a `permanent` property defaults to `true`. So currently all of our redirects do a permanent redirect (308).
```
> curl https://www.cdk.tf
Redirecting to https://github.com/hashicorp/terraform-cdk (308)
```
```
> curl curl https://terraform-cdk-redirects-1gul8nt9t-hashicorp.vercel.app/
Redirecting to https://github.com/hashicorp/terraform-cdk (307)
```
=> fix: correctly denote all of our redirects as temporary because they might change

packages/cdktf-cli/templates/csharp/.gitignore
Some C# plugin in my VSCode setup started building the template project which resulted in an obj directory being created 😅 This PR adds a Gitignore to ignore this untracked directory for good
=> fix(cli): Ignore local obj/ dir in C# template

.github/CODEOWNERS
We use this for automatic PR review assignment within Github.
We don't intent to gatekeep certain parts of the codebase and won't use it in branch protection rules.
If individual users are specified in this file, this is mainly to inform them of certain PRs and we don't require a review from them to be able to merge PRs.
=> feat: add CODEOWNERS file for automatic PR review assignment

packages/cdktf-cli/templates/python-pip/main.py, packages/cdktf-cli/templates/python/main.py, packages/cdktf-cli/templates/typescript/main.ts, test/typescript/init-from-tf/__snapshots__/test.ts.snap
previously `name` and `ns` were used a swell.
Using `id` as that is the name of that attribute in the parent Construct class as well and that is also used in templates of the AWS CDK.
=> fix(cli): Use 'id' as argument name for all templates

CHANGELOG.md, package.json
- fix(provider-generator): don't require arrays wrapping variable / output declarations [\#2199](https://github.com/hashicorp/terraform-cdk/pull/2199)
- fix(cli): Use 'id' as argument name for all templates [\#2119](https://github.com/hashicorp/terraform-cdk/pull/2119)
- fix(cli): use a custom user-agent when talking to TFC [\#2210](https://github.com/hashicorp/terraform-cdk/pull/2210)
- fix(cli): Ignore local obj/ dir in C# template [\#2217](https://github.com/hashicorp/terraform-cdk/pull/2217)
- fix(deps): Use apt instead of yum, since base image is debian based now [\#2216](https://github.com/hashicorp/terraform-cdk/pull/2216)
- fix: correctly denote all of our redirects as temporary because they might change [\#2218](https://github.com/hashicorp/terraform-cdk/pull/2218)
- chore: …
=> chore(release): Update CHANGELOG.md and version to 0.13.2

packages/cdktf/lib/app.ts, packages/cdktf/lib/terraform-data-source.ts, packages/cdktf/lib/terraform-element.ts, packages/cdktf/lib/terraform-module.ts, packages/cdktf/lib/terraform-provider.ts, packages/cdktf/lib/terraform-resource.ts, packages/cdktf/lib/terraform-stack.ts, packages/cdktf/lib/testing/index.ts, packages/cdktf/lib/tokens/private/resolve.ts, packages/cdktf/lib/validations/validate-provider-presence.ts, packages/cdktf/package.json, test/typescript/feature-flags/__snapshots__/test.ts.snap, website/docs/cdktf/api-reference/csharp.mdx, website/docs/cdktf/api-reference/go.mdx, website/docs/cdktf/api-reference/java.mdx, website/docs/cdktf/api-reference/python.mdx, website/docs/cdktf/api-reference/typescript.mdx, yarn.lock
**BREAKING CHANGE** - as we learned the hard way in 0.12.2 this is a breaking change, as JSII bindings for Python are affected by changes to methods of parent classes and this could be the case for static methods as well. This is not a breaking change for users but it is internally as such that pre-built provider bindings need to be generated against this version to work.
Related to #1132
=> chore(lib)!: Replace all instanceof checks with Symbols and add lint rule against accidentally adding new ones

packages/cdktf/lib/backends/cloud-backend.ts, packages/cdktf/lib/backends/remote-backend.ts, packages/cdktf/lib/terraform-stack.ts, website/docs/cdktf/api-reference/csharp.mdx, website/docs/cdktf/api-reference/go.mdx, website/docs/cdktf/api-reference/java.mdx, website/docs/cdktf/api-reference/python.mdx, website/docs/cdktf/api-reference/typescript.mdx
- chore(lib): add cloud = tfc | tfe to synth telemetry events to track usage of either
BREAKING CHANGE: This changes the signatures of some exported methods and thus is probably a breaking change (at least for Python)
- chore(docs): update docs
Resolves #2206
=> chore(lib): telemetry track tfc usage

.github/workflows/docker.yml, .github/workflows/examples.yml, .github/workflows/integration.yml, .github/workflows/provider-integration.yml, .github/workflows/unit.yml, .github/workflows/update-snapshots.yml, .github/workflows/website.yml, .github/workflows/yarn-upgrade.yml
Using caches always and also for terraform plugins should improve stability and reduces the test runtime of the unit tests by 7 minutes
=> chore: cache examples and terraform plugins

packages/cdktf-cli/src/lib/dependencies/package-manager.ts, test/typescript/provider-upgrade-command/test.ts
Closes #2205
Updated the NodeJS package manager to always use the `-E` flag. This flag translates into `--save-exact` for npm, and `--exact` on yarn.
=> chore: install pre-built provider with exact version

packages/cdktf-cli/src/bin/cmds/helper/version-check.ts
Without it, "npm view cdktf-cli version" is invoked.
=> fix(cli): do not check for version when DISABLE_VERSION_CHECK

packages/cdktf/lib/testing/__tests__/matchers.test.ts, packages/cdktf/lib/testing/matchers.ts
This commit appends the process output to the error message of test matchers such as `.toPlanSuccessfully()` or `.toBeValidTerraform()` if available. 
Prior to this commit the developer faced a more generic error message and had to manually execute `terraform validate -json` in the output directory of CDKTF to receive more details on why the test failed.
-> **Nevermind: Did not saw that there is an PR already open to tackle this issue... This PR can be closed if preferred!**
Closes #1953
=> feat(lib): adds failed process output to test matcher APIs #1953

website/docs/cdktf/concepts/providers.mdx, website/docs/cdktf/create-and-deploy/best-practices.mdx
just stumbled upon this.. 😅
Related to #2146
=> fix(docs): fix links to pre-built provider repositories

packages/cdktf-cli/build.ts
We don't need to minify sources when we're watching as it's only used during development.
This is useful to get better stack traces and console logging.
=> chore(cli): Prevent minification when watching cdktf-cli

packages/cdktf/lib/backends/artifactory-backend.ts, packages/cdktf/lib/backends/etcd-backend.ts, packages/cdktf/lib/backends/etcdv3-backend.ts, packages/cdktf/lib/backends/manta-backend.ts, packages/cdktf/lib/backends/swift-backend.ts, website/docs/cdktf/api-reference/csharp.mdx, website/docs/cdktf/api-reference/go.mdx, website/docs/cdktf/api-reference/java.mdx, website/docs/cdktf/api-reference/python.mdx, website/docs/cdktf/api-reference/typescript.mdx, website/docs/cdktf/concepts/remote-backends.mdx
Marks our backend constructs and their options as deprecated.
Closes #2244
=> chore(lib): Add deprecation notices to backends that were deprecated in Terraform v1.2.3 and removed in TF 1.3

CONTRIBUTING.md
We could also add them [here](https://developer.hashicorp.com/terraform/cdktf/create-and-deploy/environment-variables), but I thought that this wouldn't be helpful without knowledge about CDKTF internals.
=> chore: document JSII debug flags in contribution guide

tools/documentation-code-snippets/update-documentation-code-snippets.ts
this enables us to replace multiple codeblocks of the same language in a single markdown file 😅 This was broken previously
=> fix: set global flag to be able to start search for code blocks at an index

website/docs/cdktf/cli-reference/cli-configuration.mdx, website/docs/cdktf/cli-reference/commands.mdx, website/docs/cdktf/community.mdx, website/docs/cdktf/concepts/aspects.mdx, website/docs/cdktf/concepts/assets.mdx, website/docs/cdktf/concepts/cdktf-architecture.mdx, website/docs/cdktf/concepts/constructs.mdx, website/docs/cdktf/concepts/data-sources.mdx, website/docs/cdktf/concepts/functions.mdx, website/docs/cdktf/concepts/hcl-interoperability.mdx, website/docs/cdktf/concepts/iterators.mdx, website/docs/cdktf/concepts/modules.mdx, website/docs/cdktf/concepts/providers.mdx, website/docs/cdktf/concepts/remote-backends.mdx, website/docs/cdktf/concepts/resources.mdx, website/docs/cdktf/concepts/stacks.mdx, website/docs/cdktf/concepts/tokens.mdx, website/docs/cdktf/concepts/variables-and-outputs.mdx, website/docs/cdktf/create-and-deploy/aws-adapter.mdx, website/docs/cdktf/create-and-deploy/best-practices.mdx, website/docs/cdktf/create-and-deploy/configuration-file.mdx, website/docs/cdktf/create-and-deploy/deployment-patterns.mdx, website/docs/cdktf/create-and-deploy/environment-variables.mdx, website/docs/cdktf/create-and-deploy/project-setup.mdx, website/docs/cdktf/create-and-deploy/remote-templates.mdx, website/docs/cdktf/create-and-deploy/terraform-cloud.mdx, website/docs/cdktf/examples.mdx, website/docs/cdktf/telemetry.mdx, website/docs/cdktf/test/debugging.mdx, website/docs/cdktf/test/unit-tests.mdx
Currently when folks google CDK for Terraform Concepts, it's impossible to tell whether some of the results are for regular Terraform or CDK for Terraform. This is because our content has a lot of similar concepts to Terraform (like providers) and every page is automatically appended with "- Terraform | HashiCorp Developer"
This makes it more difficult for users to be sure that they are getting the right content when they click on a page. This PR adds "CDK for Terraform" to every page title to make it clear which content relates to CDKTF specifically.
A provider page - this is for CDK for Terraform, but the title makes it look like it's for regular Terraform only.
Terraform Content uses "-Configuration Language" so we modeled the "- CDK for Terraform" after this for consistency.
Search …
=> chore(docs): Add CDK for Terraform to page titles

packages/@cdktf/provider-generator/lib/__tests__/provider.test.ts, packages/@cdktf/provider-generator/lib/get/__tests__/generator/module-generator.test.ts, packages/@cdktf/provider-generator/lib/get/__tests__/generator/versions-file.test.ts, packages/@cdktf/provider-generator/lib/get/__tests__/util.ts, packages/@cdktf/provider-generator/lib/get/constructs-maker.ts, packages/@cdktf/provider-generator/lib/index.ts, packages/cdktf-cli/src/bin/cmds/get.ts, packages/cdktf-cli/src/bin/cmds/handlers.ts, packages/cdktf-cli/src/bin/cmds/helper/init.ts, packages/cdktf-cli/src/bin/cmds/provider-upgrade.ts, packages/cdktf-cli/src/bin/cmds/ui/get.tsx, packages/cdktf-cli/src/lib/get.ts, website/docs/cdktf/cli-reference/commands.mdx
I also try to clean up old providers when possible (only in TS to my knowledge 😢). I introduced a new file so that we can change the interface of this functionality later again.
=> feat(cli): only re-generate provider bindings on get if necessary

packages/cdktf-cli/src/lib/cdktf-stack.ts, packages/cdktf-cli/src/lib/models/terraform-cli.ts, packages/cdktf-cli/src/lib/models/terraform-cloud.ts, packages/cdktf-cli/src/lib/models/terraform.ts, test/typescript/provider-upgrade/cdktf.json, test/typescript/provider-upgrade/main.ts, test/typescript/provider-upgrade/test.ts
Fixes #1863
When [locked providers](https://www.terraform.io/language/files/dependency-lock) aren't compatible with currently specified providers, automatically update the locked version.
Users are likely to run into this situation when updating a pre-built provider package.
Still todo:
* Possibly exposing behavior as an option
=> feat(cli): Automatically Update Locked Providers

CHANGELOG.md, package.json
Note: https://github.com/hashicorp/terraform-cdk/pull/2302 needs to be merged first!
=> chore(release): Update CHANGELOG.md and version to 0.14.1

packages/cdktf-cli/src/lib/models/terraform-cloud.ts, test/typescript/feature-flags/__snapshots__/test.ts.snap
Closes: #2236
I'm still not really comfortable with the big-picture understanding of how we use `json-output`. While this PR works well enough, please let me know if there are certain scenarios that are broken because of this. Especially around cross-stack references and so on.
=> fix: Graceful failures when using `cdktf` with non-admin tokens

packages/@cdktf/hcl2json/wasm/bridge_wasm_exec.js
Node 19 comes with [a stable crypto API that is exposed on globalThis](https://nodejs.org/en/blog/announcements/v19-release-announce/#stable-webcrypto), so we can only selectively overwrite the crypto object. I did not change our testing t include node 19 since some of our dev dependencies don't support node 19 yet.
Closes #2211
=> fix(hcl2json): don't overwrite crypto if it's set already

.github/workflows/examples.yml, .github/workflows/integration.yml, .github/workflows/linting.yml, .github/workflows/release.yml, .github/workflows/release_next.yml, .github/workflows/unit.yml
For this I had to pull out linting from the unit workflow. I would love to reduce the examples down to only the changed example, but this does not seem to be trivial so I decoupled it from this change.
=> chore: run CI more selectively

website/docs/cdktf/concepts/aspects.mdx, website/docs/cdktf/concepts/assets.mdx, website/docs/cdktf/concepts/constructs.mdx, website/docs/cdktf/concepts/data-sources.mdx, website/docs/cdktf/concepts/functions.mdx, website/docs/cdktf/concepts/hcl-interoperability.mdx, website/docs/cdktf/concepts/modules.mdx, website/docs/cdktf/concepts/providers.mdx, website/docs/cdktf/concepts/remote-backends.mdx, website/docs/cdktf/concepts/resources.mdx, website/docs/cdktf/concepts/variables-and-outputs.mdx, website/docs/cdktf/create-and-deploy/project-setup.mdx, website/docs/cdktf/create-and-deploy/remote-templates.mdx
I happened to look at the docs today and noticed that even in the places where we already have CodeTabs set up with code samples in multiple languages, our docs consistently have the text:
> The following TypeScript example ...
Since we are actively working on translating all the code samples to multiple languages and are hoping to start merging those changes very soon, I think it's okay to do away with the "TypeScript" qualifier now.
This PR is just a result of running the following on the command line:
```
grep -RlI 'The following TypeScript example' ./website | xargs sed -i "" 's/The following TypeScript example/The following example/g'
```
I did not do a manual check for other phrasings.
(re: #1929)
=> chore(docs): prepare for code samples in multiple languages

.github/workflows/pr-size.yml
I took the defaults of the action, let's revisit them after a time to adjust to our needs
=> chore: add GH Action that labels PRs

.github/workflows/release.yml, .github/workflows/release_next.yml
Consists of these parts, trying to solve the problem where the unit tests won't get started
- chore: use paths instead of paths ignore
- chore: these tests don't rely on the release setup
- chore: add new packages
=> chore: improve release pipelines

.github/workflows/release.yml, CONTRIBUTING.md
This updates the `release` workflow, to:
- Short-circuit the workflow is no new release needs to be made
- Enable publishing version to homebrew when new release is made
=> fix: Prevent any release jobs from triggering if no release is required

.github/workflows/lock.yml, .github/workflows/stale.yml
When I was adding the `bug/has-workaround` label to tickets yesterday, I noticed there are a handful of issues labeled `waiting-on-answer` where we haven't heard back from the user in months. I figured we should automate posting a "warning" and then closing the issue after a set amount of time. I also added a workflow that locks threads after 30 days to encourage folks to create new issues rather than replying to old closed issues forever. Kudos to the Editor Experience team for giving me a template to work from!
Closes #683
=> chore: add workflows to auto-close and lock stale issues and PRs

.github/workflows/stale.yml
I originally purposely tried to avoid adding another label to stale comments (since we already have the "waiting-on-answer" label) but I guess that doesn't work; it has to have a label. So let's just reuse the "stale" label for issues too.
=> chore: fix stale workflow

packages/@cdktf/cli-core/package.json
The release currently fails due to this: https://github.com/hashicorp/terraform-cdk/actions/runs/3542799009/jobs/5949276900
=> fix: scoped packages need a publish config to be published to npm

packages/@cdktf/cli-core/src/lib/dependencies/dependency-manager.ts
Closes #2345
Note: I opted against just catching the UsageError because we report usage errors, so not throwing it in the first place was the cleaner way
=> fix(cli): don't fail with UsageError when determining whether a provider is installed as a pre-built provider

test/python/edge/test.ts
The issue causing this problem will be released in the next days, but we have
other problems in the release pipeline that should be fixed beforehand.
Therefore I'll disable these tests for now and re-add them when updating JSII.
The fix we are waiting for to be released is https://github.com/aws/jsii/pull/3866
=> chore: disable python edge test

.github/workflows/release.yml, .github/workflows/release_next.yml
By piping to `/dev/null` we can get rid of this Sentry output:
`| (unreleased) | cdktf-cli-0.14.1        | 7          | 7 hours ago    |`
which was part of `status` previously (and required the newline replacement).
By grepping for `unreleased` and inverting the expression, we catch the
expected unreleased release which is the right condition to be able to
finalize the release (the previous one was wrong, as at this time, there
should always have been a release as it is created by an earlier workflow step).
=> chore: fix finalizing the Sentry release

CHANGELOG.md, package.json
**Breaking changes**
We split up our `cdktf-cli` package into `cdktf-cli` for the UI parts, utilizing `@cdktf/cli-core` for the functionality. If you previously relied on the internal `cdktf-cli/lib` entrypoint you should switch to `@cdktf/cli-core`. This was never an official API, but we want to mention it here in case it breaks for anyone.
- chore: skip hcl2cdk tests for now [\#2384](https://github.com/hashicorp/terraform-cdk/pull/2384)
- chore: Update Digital Team Files [\#2383](https://github.com/hashicorp/terraform-cdk/pull/2383)
- chore: move from pr target to pr [\#2381](https://github.com/hashicorp/terraform-cdk/pull/2381)
- chore: fix finalizing the Sentry release [\#2379](https://github.com/hashicorp/terraform-cdk/pull/2379)
- chore: update workflows for new workflow endpoint …
=> chore: release 0.14.2

packages/cdktf-cli/src/bin/cmds/helper/init.ts
Closes: #2280
If user has TFC credentials present (`~/.terraform.d/credentials.tfrc.json` exists) they are prompted to confirm the usage of TFC in `cdktf init`.
[Link to gist demonstrating](https://gist.github.com/Maed223/65b9159c58af2ae456919e72e76de045)
=> feat(cli): prompt added in init - asks to use TFC when credentials are present 

packages/@cdktf/cli-core/src/lib/terraform-json.ts
https://github.com/hashicorp/terraform-cdk/commit/8b069eb7db3b536b7de8fd7a189afd8ed3c549eb added validation on the `cdk.tf.json` file. However, the schema is missing [required_version](https://developer.hashicorp.com/terraform/language/settings#specifying-a-required-terraform-version) in the `terraform` block
hence when running `cdktf [deploy|plan|destroy]` will result in the following error
```
0 Stacks deploying     0 Stacks done     0 Stacks waiting
1 validation issue(s)
Issue #0: unrecognized_keys at terraform
Unrecognized key(s) in object: 'required_version'
```
There is another terraform json schema at https://sourcegraph.com/github.com/daniel-laszlo/terraform-cdk/-/blob/packages/@cdktf/hcl2cdk/lib/schema.ts?L22
I do not have any historical context on this project, but should there …
=> fix: add `required_version` to json schema

packages/@cdktf/cli-core/src/lib/models/terraform-cloud.ts
related issues & pr:
- https://github.com/hashicorp/terraform-cdk/issues/2232
- https://github.com/hashicorp/terraform-cdk/pull/1955
While https://github.com/hashicorp/terraform-cdk/pull/1955 is currently being worked on, this is the workaround for various causes of the issue described in https://github.com/hashicorp/terraform-cdk/issues/2232
When a workspace has auto-apply enabled, `cdktf deploy` will error out with the following error message at the `confirm` stage. This PR added a check on `run` and skip confirming the plan if `auto-apply` is enabled.
```
default - Error in Deploy: {"message":"Request failed with status code 409","name":"Error","stack":"Error: Request failed with status code 409\n    at WGe.exports (/home/runner/work/cloud/cloud/terraform-cdk/packages/cdktf-cli/bundle/b …
```
=> fix: skip confirming on auto-apply enabled tfc workspaces

packages/@cdktf/cli-core/src/lib/models/terraform-cloud.ts
related issues & pr:
- https://github.com/hashicorp/terraform-cdk/issues/2232
- https://github.com/hashicorp/terraform-cdk/pull/1955
- https://github.com/hashicorp/terraform-cdk/pull/2243
- https://github.com/hashicorp/terraform-cdk/pull/2360
While https://github.com/hashicorp/terraform-cdk/pull/1955 is currently being worked on, this is the workaround for various causes of the issue described in https://github.com/hashicorp/terraform-cdk/issues/2232
https://github.com/hashicorp/terraform-cdk/pull/2243 & https://github.com/hashicorp/terraform-cdk/pull/2360 are missing a few more pending states from TFC API
This is tested internally across our TFC workspaces with and without auto-apply enabled. I can confirm no more `409` error from TFC and all stacks are deployed in one go.
=> fix: add completed tfc pending states

CHANGELOG.md, package.json, website/docs/cdktf/concepts/tokens.mdx
- fix: add completed tfc pending states [\#2398](https://github.com/hashicorp/terraform-cdk/pull/2398)
- fix: skip confirming on auto-apply enabled tfc workspaces [\#2397](https://github.com/hashicorp/terraform-cdk/pull/2397)
- fix(hcl2cdk): snapshot generated code instead of snapshotting that the function returns a promise [\#2392](https://github.com/hashicorp/terraform-cdk/pull/2392)
- fix: add `required_version` to json schema [\#2355](https://github.com/hashicorp/terraform-cdk/pull/2355)
- chore: add provider-integration tests conditionally for PRs and to releases [\#2371](https://github.com/hashicorp/terraform-cdk/pull/2371)
- chore: increase operations per run of stale workflow [\#2363](https://github.com/hashicorp/terraform-cdk/pull/2363)
- chore: update github workflow actions …
=> chore: release 0.14.3

.github/workflows/gh-action-upgrade.yml
HashiCorp is in the process of rolling out a new security policy that requires us to pin the SHA hashes of any (external) GitHub Actions that we want to use in our workflows. I was very happy to see that `github-actions-version-updater` already has support for this built-in, thankfully!
Further reading (inside HashiCorp): https://docs.google.com/document/d/10TCefPVlhFuh5cKn75rMqNFKZyP8qUK-BWPaaSEO01Q/edit?usp=sharing
=> chore: switch to SHA-based workflow pins

packages/cdktf/lib/tfExpression.ts, packages/cdktf/lib/tokens/private/encoding.ts, packages/cdktf/lib/tokens/private/resolve.ts, packages/cdktf/lib/tokens/private/token-map.ts, packages/cdktf/lib/tokens/resolvable.ts, packages/cdktf/lib/tokens/string-fragments.ts, packages/cdktf/test/encoding.test.ts, packages/cdktf/test/fqn.test.ts, tools/documentation-generation/yarn.lock, website/docs/cdktf/api-reference/csharp.mdx, website/docs/cdktf/api-reference/go.mdx, website/docs/cdktf/api-reference/java.mdx, website/docs/cdktf/api-reference/python.mdx, website/docs/cdktf/api-reference/typescript.mdx, website/docs/cdktf/concepts/functions.mdx
Relates to: https://github.com/hashicorp/terraform-cdk/issues/1641
This PR proposes to use the HCL syntax for string interpolation (`${}`) to alter how CDKTF outputs [Tokens](https://developer.hashicorp.com/terraform/cdktf/concepts/tokens). What I'm looking for right now is some feedback around what kinds of potential problems this introduces that I may not have thought about and the relative usefulness of such things pertaining to its ease of use with [escape hatches](https://developer.hashicorp.com/terraform/cdktf/concepts/resources#escape-hatch) and overrides.
As the above issue mentions, working with FQN is hard currently, and the root cause seems to be the resolution of tokens. The easiest example is from the above issue, where a user tried the following:
```typescript …
```
=> feat: [Proposal] Enable non-escaping mode for tokens

packages/cdktf/lib/testing/adapters/jest.ts, test/jest.config.js, test/typescript/testing-matchers/__tests__/main-test.ts, test/typescript/testing-matchers/cdktf.json, test/typescript/testing-matchers/main.ts, test/typescript/testing-matchers/test.ts
=> fix: Expose provider matcher to jest

packages/@cdktf/cli-core/src/lib/init.ts, packages/cdktf-cli/src/bin/cmds/helper/init.ts, packages/cdktf-cli/src/bin/cmds/helper/terraform-cloud-client.ts, packages/cdktf-cli/src/bin/cmds/init.ts, packages/cdktf-cli/templates/csharp/.hooks.sscaff.js, packages/cdktf-cli/templates/go/.hooks.sscaff.js, packages/cdktf-cli/templates/java/.hooks.sscaff.js, packages/cdktf-cli/templates/python-pip/.hooks.sscaff.js, packages/cdktf-cli/templates/python/.hooks.sscaff.js, packages/cdktf-cli/templates/typescript/.hooks.sscaff.js, website/docs/cdktf/cli-reference/commands.mdx
Since we're moving to using TF CLI for Terraform Cloud, this PR removes the additional API call we make to TFC/TFE to create a workspace. Instead, it relies on the first `cdktf diff` or `cdktf deploy` by the developer to create a workspace on TFC.
The reason for this change is that by default workspaces created by the TFC API are set to use 'local execution', but when using the TF CLI and the `CloudBackend`, the created workspace uses 'remote execution'.
- The CLI checks the user's selected organisation if the selected workspace name already exists, and if so, allows the user to select a new name.
- Adding a `tfe-hostname` to the `init` command (Maybe I missed something, but I didn't see how TFE customers could use CDKTF before without going from local to remote?)
- Updating templates to …
=> chore: create TFC/TFE workspace using the Terraform CLI

.github/workflows/build.yml, .github/workflows/examples.yml, .github/workflows/integration.yml, .github/workflows/provider-integration.yml, .github/workflows/release.yml, .github/workflows/release_next.yml, .github/workflows/unit.yml, .github/workflows/update-snapshots.yml, packages/@cdktf/hcl2json/build-go.sh
Go 1.18+ started to embed repo information into builds which failed
without the safe.directory being set in Github Actions.
Husky (our Git hook tool) also printed a warning about safe.directory
being not set, but didn't fail.
=> fix: fix go build in pipeline

packages/cdktf/lib/util.ts
Adds `environment` to keys to preserve case.  When using `local-exec`, the environment would get lower cased.  This is unintuitive with how environment variables generally work.
=> fix: Adds `environment` to keys to preserve case

packages/@cdktf/cli-core/src/lib/models/deploy-machine.ts, packages/cdktf-cli/src/bin/cmds/ui/hooks/cdktf-project.ts
- fix(cli): force-stop the UI process on execution completion
- fix(cli): send addition \r to fix windows approval
- fix(cli): remove colors before extracting variable names
=> fix(cli): windows fixes

packages/cdktf/lib/app.ts, website/docs/cdktf/api-reference/csharp.mdx, website/docs/cdktf/api-reference/go.mdx, website/docs/cdktf/api-reference/java.mdx, website/docs/cdktf/api-reference/python.mdx, website/docs/cdktf/api-reference/typescript.mdx, website/docs/cdktf/concepts/modules.mdx
- refactor(lib): rename AppConfig parameter from options to config to reflect its new typename
- chore(docs): Update snippet containing Options that now are named Config
Another small follow-up for #2471
=> chore(docs): fix some docs

.github/workflows/integration.yml
10 turned out to be a bit too low, so I'm raising that one a bit
=> chore: increase parallel limit (10->30) to speed up integration tests

packages/@cdktf/cli-core/src/lib/models/deploy-machine.ts, packages/@cdktf/cli-core/src/lib/models/terraform-cli.ts, test/test-helper.ts, test/typescript/variables/test.ts
- fix(cli): don't enquote args as they will be escaped and end up in the calls to Terraform
- feat(tests): add test for passing args to diff as well
=> fix(cli): don't enquote args as they will be escaped and end up in the calls to Terraform

.github/workflows/gh-action-upgrade.yml
This workflow can get a bit noisy if we don't stay on top of merging the PRs because it could potentially open a new PR every week even though there might be no changes. This closes any open old ones before opening a new PR.
=> chore: autoclose older GHA updater PRs

packages/@cdktf/cli-core/src/lib/cdktf-project.ts, packages/@cdktf/cli-core/src/lib/cdktf-stack.ts, packages/@cdktf/cli-core/src/lib/models/terraform-cli.ts, packages/@cdktf/cli-core/src/lib/models/terraform.ts
Reverts `8eb985b3ca1398e85c538b745dc32a250c918781` which was accidentally pushed to `main`
=> fix: Revert 8eb985b3ca1398e85c538b745dc32a250c918781

CHANGELOG.md, package.json
- fix(provider-generator): fix resources named 'provider' breaking the code generation [\#2504](https://github.com/hashicorp/terraform-cdk/pull/2504)
- chore: autoclose older GHA updater PRs [\#2505](https://github.com/hashicorp/terraform-cdk/pull/2505)
=> chore: release 0.15.1

packages/@cdktf/cli-core/src/lib/models/terraform-cli.ts, packages/@cdktf/cli-core/src/lib/synth-stack.ts
Closes #2506
**Note**: This will only add a plan file to non-tfc runs since there is no reliable way to determine if TFC is used as a state backend or with remote execution
=> feat: create a plan file for non-TFC runs

CHANGELOG.md, package.json
- feat: create a plan file for non-TFC runs [\#2531](https://github.com/hashicorp/terraform-cdk/pull/2531)
- fix: cdktf login issues [\#2543](https://github.com/hashicorp/terraform-cdk/pull/2543)
- fix(lib): don't use Fn.set on tagged cloud backend [\#2536](https://github.com/hashicorp/terraform-cdk/pull/2536)
- fix(provider-generator): use class based map abstractions [\#2530](https://github.com/hashicorp/terraform-cdk/pull/2530)
- chore: actually autoclose older GHA updater PRs [\#2542](https://github.com/hashicorp/terraform-cdk/pull/2542)
- chore: fill out homebrew pr body [\#2537](https://github.com/hashicorp/terraform-cdk/pull/2537)
- chore: support soft sentinel overrides [\#2485](https://github.com/hashicorp/terraform-cdk/pull/2485)
=> chore: release 0.15.2

package.json
Uses `--cache` options to speed up prettier runs through `yarn run format`
> yarn format
> ✨  Done in 43.27s.
> yarn format
> ✨  Done in 6.24s.
=> feat: add cache flag for prettier to speed up subsequent runs

examples/csharp/documentation/FunctionsRawStack.cs, examples/csharp/documentation/Main.cs, examples/csharp/documentation/OperatorStack.cs, examples/csharp/documentation/OutputVariableStack.cs, examples/csharp/documentation/OutputsUsageStack.cs, examples/csharp/documentation/RemoteStateStack.cs, examples/csharp/documentation/VariablesStack.cs, website/docs/cdktf/concepts/functions.mdx, website/docs/cdktf/concepts/stacks.mdx, website/docs/cdktf/concepts/variables-and-outputs.mdx
The Operators example does not work in C# I added a bug into our issues and linked it, so we are transparent to users. Right below is a workaround using plain strings so I don't feel like this is a big problem in this case
=> chore: translate rest of the docs to C#

examples/csharp/documentation/ResourcesStack.cs, examples/java/documentation/src/main/java/com/mycompany/app/resources/MainResources.java, examples/python/documentation/resources.py, examples/typescript/documentation/resources.ts, website/docs/cdktf/concepts/resources.mdx
=> fix(docs): camel -> snake case in resource escape hatches

tools/documentation-code-snippets/update-documentation-code-snippets.ts
previously the script would only use git ls-files in a way that listed all files known to git (to skip going through e.g. node_modules). However, this had the quirk, that files that hadn't been added to git yet, would not be detected which was annoying when writing documentation examples. This change fixes that.
=> feat: also go through files not yet added to git

Dockerfile
Closes #2586
Docker build worked locally after changing this:
```
➜  terraform-cdk git:(main) docker build .                                                                                    13:11:33
[+] Building 477.1s (9/9) FINISHED
=> [internal] load build definition from Dockerfile                                                                              0.1s
=> => transferring dockerfile: 1.19kB                                                                                            0.0s
=> [internal] load .dockerignore                                                                                                 0.0s
=> => transferring context: 35B                                                                                                  0.0s
=> [internal] load metadata …
```
=> fix: switch back to offical image to fix issue with stale signature files

packages/@cdktf/cli-core/src/lib/cdktf-stack.ts, packages/@cdktf/cli-core/src/lib/terraform-provider-lock.ts, packages/@cdktf/cli-core/src/test/lib/terraform-provider-lock.test.ts
This PR will prevent us from running `terraform init` when there isn't a change between what's present within provider lock, and the generated required providers. This makes cdktf plan/apply/destroy during development much faster.
depends on #2570
=> chore: Don't run `terraform init` when not required

packages/@cdktf/cli-core/src/lib/models/terraform-cli.ts
This PR reduces the OS platforms we update the terraform provider lock on to make cdktf plan/apply/destroy operations faster.
We're currently being too careful with provider locking, but after some basic testing, the following seems to be true:
- `terraform init` generates the provider lock for the current platform `cdktf` is running on
- Workflows will fail on TFC/E if we don't do an additional `terraform providers lock` command for linux
- Terraform `providers lock` command appends hashes, and doesn't override older hashes, so it's additive.
- We don't have insight into whether we're running locally or remotely at this level, so we need to assume that all workflows are remote execution.
=> chore: additionally lock providers for linux only

CHANGELOG.md, package.json
- chore: Don't run `terraform init` when not required [\#2572](https://github.com/hashicorp/terraform-cdk/pull/2572)
- chore: additionally lock providers for linux only [\#2593](https://github.com/hashicorp/terraform-cdk/pull/2593)
- chore: refactor 'needs upgrade' [\#2570](https://github.com/hashicorp/terraform-cdk/pull/2570)
- chore: Update remaining Typescript documentation snippets [\#2564](https://github.com/hashicorp/terraform-cdk/pull/2564)
- chore: translate more csharp docs [\#2433](https://github.com/hashicorp/terraform-cdk/pull/2433)
- chore: translate rest of the docs to C# [\#2558](https://github.com/hashicorp/terraform-cdk/pull/2558)
- chore: run dotnet format [\#2559](https://github.com/hashicorp/terraform-cdk/pull/2559)
- chore: Update contributing …
=> chore(release): Update CHANGELOG.md and version to 0.15.3

packages/cdktf/lib/app.ts, packages/cdktf/test/app.test.ts
Validations are a feature of the constructs lib. Previously we only ran validations added to Stacks (and below). This change also runs them on the root App
This is in preparation for adding a validation that confirms that no stacks are reusing the same backend configuration
=> feat(lib): Support adding Validations on App

package.json, packages/@cdktf/hcl2json/package.json, packages/@cdktf/provider-generator/package.json, yarn.lock
- fix(cli): Remove @types/node-fetch from dependencies as those take precence over direct devDependencies on @node/types
- fix: use override for @types/node in yarn monorepo
If this one works, prefer it over #2621
=> fix(cli): Remove @types/node-fetch from dependencies as those take precedence over direct devDependencies on @node/types

CHANGELOG.md, package.json
- fix(cli): Remove @types/node-fetch from dependencies as those take precedence over direct devDependencies on @node/types [\#2623](https://github.com/hashicorp/terraform-cdk/pull/2623)
=> chore: release 0.15.4

packages/@cdktf/cli-core/src/lib/cdktf-project.ts, packages/@cdktf/cli-core/src/lib/cdktf-stack.ts, packages/@cdktf/cli-core/src/lib/models/deploy-machine.ts, packages/@cdktf/cli-core/src/lib/models/pty-process.ts, packages/@cdktf/cli-core/src/lib/models/terraform-cli.ts, packages/@cdktf/cli-core/src/lib/models/terraform.ts, packages/@cdktf/cli-core/src/test/lib/cdktf-project.test.ts, packages/@cdktf/cli-core/src/test/models/deploy-machine.test.ts, packages/cdktf-cli/src/bin/cmds/deploy.ts, packages/cdktf-cli/src/bin/cmds/destroy.ts, packages/cdktf-cli/src/bin/cmds/diff.ts, packages/cdktf-cli/src/bin/cmds/handlers.ts, packages/cdktf-cli/src/bin/cmds/ui/deploy.tsx, packages/cdktf-cli/src/bin/cmds/ui/destroy.tsx, packages/cdktf-cli/src/bin/cmds/ui/diff.tsx, test/typescript/terraform-cloud/test.ts, website/docs/cdktf/cli-reference/commands.mdx, website/docs/cdktf/concepts/remote-backends.mdx
After this change a --migrate-state flag can be passed to diff, deploy, destroy
that will migrate the state from the previous backend to the current one.
Please not that Terraform CLI does not support migrating from the cloud configuration
to other backends, as a result this is not supported in cdktf either.
Closes #490
Closes #489
=> feat(cli): support migrating state between backends

website/docs/cdktf/index.mdx
I was reading through some conversations by the Field team today and found one of them link to this section of our docs when I realized this line has been inaccurate since our GA release, since we do offer commercial support now. Oops!
Replaced it in a hurry with this other line -- @robin-norwood I'm open to suggestions re: how to phrase this better.
=> chore(docs): remove inaccurate line about commercial support

packages/cdktf/lib/terraform-functions.ts
when trying to use `Fn.zipmap` getting `Error: zipmap takes 1 arguments, but 2 were provided`
after this fix it works
=> fix(lib): zipmap arg validators

.copywrite.hcl, .github/ISSUE_TEMPLATE/documentation.yml
As we're starting to get more bug reports about our docs, I figured it might be helpful to have a separate issue template. I used the template that JSII uses as inspiration, as it is simple but effective.
=> chore: add docs issue template

CHANGELOG.md, package.json
- fix(cli): Remove @types/node-fetch from dependencies as those take precedence over direct devDependencies on @node/types [\#2623](https://github.com/hashicorp/terraform-cdk/pull/2623)
=> chore: release 0.15.5

packages/cdktf/go-copyright-header.sh, packages/cdktf/package.json
Added script that appends copyright headings to files in `cdktf` go package for compliance.
Unsure if there's a better way of including the script in the packaging process.
=> chore: Automate go package copyright/license inculsion

website/docs/cdktf/release/upgrade-guide-v0-10.mdx, website/docs/cdktf/release/upgrade-guide-v0-11.mdx, website/docs/cdktf/release/upgrade-guide-v0-9.mdx
Requested on internal Slack
Removing nested links within headers from our documentation pages, as links in headings can cause issues with anchor link generation and accessibility.
=> chore: Remove links within headers of documentation pages

packages/@cdktf/provider-generator/lib/__tests__/__snapshots__/edge-provider-schema.test.ts.snap, packages/@cdktf/provider-generator/lib/__tests__/edge-provider-schema/index.ts, packages/@cdktf/provider-generator/lib/get/__tests__/generator/__snapshots__/resource-types.test.ts.snap, packages/@cdktf/provider-generator/lib/get/__tests__/generator/__snapshots__/types.test.ts.snap, packages/@cdktf/provider-generator/lib/get/__tests__/generator/deep-nested-attributes.test.ts, packages/@cdktf/provider-generator/lib/get/__tests__/generator/fixtures/boolean-list.test.fixture.json, packages/@cdktf/provider-generator/lib/get/__tests__/generator/fixtures/deep-attributes.test.fixture.json, packages/@cdktf/provider-generator/lib/get/__tests__/generator/fixtures/list-list-object.test.fixture.json, packages/@cdktf/provider-generator/lib/get/__tests__/generator/fixtures/map-of-string-list.test.fixture.json, packages/@cdktf/provider-generator/lib/get/__tests__/generator/fixtures/string-map.test.fixture.json, packages/@cdktf/provider-generator/lib/get/__tests__/generator/fixtures/stripe-schema.test.fixture.json, packages/@cdktf/provider-generator/lib/get/__tests__/generator/types.test.ts, packages/@cdktf/provider-generator/lib/get/generator/emitter/attributes-emitter.ts, packages/@cdktf/provider-generator/lib/get/generator/emitter/struct-emitter.ts, packages/@cdktf/provider-generator/lib/get/generator/loop-detection.ts, packages/@cdktf/provider-generator/lib/get/generator/models/attribute-model.ts, packages/@cdktf/provider-generator/lib/get/generator/models/attribute-type-model.ts, packages/@cdktf/provider-generator/lib/get/generator/models/struct.ts, packages/@cdktf/provider-generator/lib/get/generator/resource-parser.ts, packages/cdktf/lib/complex-computed-list.ts
Fixes #2310
Fixes #2333
Use a recursive type definition rather than simple flags so that more complex types can be handled. Also lean into object orientated notions to hopefully make attribute emitting more clear.
This is in conjunction with #2372 and one will likely be merged into the other before merging to main.
=> refactor(provider-generator): Refactor AttributeTypeModel to handle more complex types

.github/workflows/pr-labels.yml
This will enable that workflow to run on forks (aka PRs by contributors), too
=> fix: change trigger for adding PR labels to pull_request_target

.github/workflows/pr-labels.yml
We already ignore that comment anyway :sweat_smile:
=> fix: don't post about large PRs since this currently happens repeatedly and spams the timeline of PRs

.github/workflows/update-snapshots.yml, packages/cdktf/lib/tfExpression.ts, packages/cdktf/test/functions.test.ts, packages/cdktf/test/tfExpression.test.ts, test/python/terraform-functions/__snapshots__/test.ts.snap, test/typescript/iterators/test.ts
We will just always wrap all keys in quotes
Closes #1795
=> fix(lib): support objects with keys that need escaping like e.g. colons

.github/workflows/pr-copyright.yml
Use `pull_request_target` so that this can run successfully for outside contributors as well.
=> chore: fix copyright headers automation

packages/@cdktf/hcl2cdk/README.md, packages/@cdktf/hcl2cdk/test/helpers/convert.ts
None
This removes the synths from the local test invocations by default, but not during CI
=> chore: improve development performance by excluding synth

packages/@cdktf/hcl2json/lib/index.ts, packages/@cdktf/hcl2json/main.go, packages/@cdktf/hcl2json/test/__snapshots__/hcl2json.test.ts.snap, packages/@cdktf/hcl2json/test/hcl2json.test.ts
This PR prepares the library for the convert work that's going to happen to support e.g. replacing functions and operations.
- fix(hcl2json): correctly check for empty array
- refactor(hcl2json): rename wasm method to match its implementation and expose it more direct aswell
=> refactor(hcl2json): rename wasm method to match its implementation and expose it more direct aswell

packages/@cdktf/provider-generator/lib/get/__tests__/generator/__snapshots__/provider.test.ts.snap, packages/@cdktf/provider-generator/lib/get/__tests__/generator/fixtures/elasticstack-provider.test.fixture.json, packages/@cdktf/provider-generator/lib/get/__tests__/generator/provider.test.ts, packages/@cdktf/provider-generator/lib/get/generator/resource-parser.ts
=> fix(provider-generator): Fix generating bindings for providers that have only block types in their schema

packages/cdktf/lib/terraform-data-source.ts, packages/cdktf/lib/terraform-module.ts, packages/cdktf/lib/terraform-resource.ts, packages/cdktf/test/helper/data-source.ts, packages/cdktf/test/iterator.test.ts
This won't solve the mismatch between programming language types and internal type of the reference (e.g. accessing a string property on an object using for_each will be a string in from the type systems of the programming languages, but a list of strings for terraform). This is not worse than what we currently have (an invalid Terraform reference), therefore I think we can go forward with this.
Relates to #2024
=> feat(lib): TerraformIterators allow chaining

packages/@cdktf/hcl2cdk/lib/expressions.ts, packages/@cdktf/hcl2cdk/test/expressionToTs.test.ts
Fixes https://github.com/hashicorp/terraform-cdk/issues/2753
For string based expressions, we were wrapping them in quotes, and not checking if the expression was a [here document](https://en.wikipedia.org/wiki/Here_document). This PR fixes that oversight. Additionally, HCL expects a newline at the end of the HEREDOC trailing marker, so the code also force-adds a new line if it doesn't exist.
=> fix(hcl2cdk): Heredocs expression parsing

Dockerfile
This has to be done separately from #2768 as our CI always uses the latest available Docker image
=> chore: upgrade our Docker image to be based on Node 0.16

Dockerfile
Reverts hashicorp/terraform-cdk#2770
This caused a lot more trouble, which I'll have to investigate first 😅
=> fix: Revert "chore: upgrade our Docker image to be based on Node 0.16"

packages/@cdktf/hcl2cdk/lib/__tests__/expressions.test.ts, packages/@cdktf/hcl2cdk/test/expressionToTs.test.ts, packages/@cdktf/hcl2json/test/expressions.test.ts
Fixes CI issues on release
As per the following article on jest, we need to return all `resolves` or `rejects` expects, and that's what caused the test to be flaky. The test itself was failing, which was correct, but only failed when it accidentally ran the full thing:
=> fix(hcl2cdk): flaky tests on hcl2cdk expressions

packages/@cdktf/cli-core/src/lib/models/deploy-machine.ts
Fixes #2749
Currently, the terraform output is send after the approval dialog. This hides the diff until an option was selected. Sending the output first makes the diff visible before the dialog.
It's  a very small change, so no new tests or documentation.
=> fix(cli): send terraform output before approval

packages/cdktf/lib/terraform-local.ts, packages/cdktf/lib/terraform-variable.ts, packages/cdktf/test/__snapshots__/local.test.ts.snap, packages/cdktf/test/__snapshots__/variable.test.ts.snap, packages/cdktf/test/local.test.ts, packages/cdktf/test/variable.test.ts
Usage in template strings will implicitly call .toString() on these which previously returned the address of the construct (as implemented in Construct#toString). With this change converting a variable or local instance to a string will just work
=> feat(lib): fix using variables and locals directly in template strings

packages/cdktf/lib/terraform-dynamic-expression.ts, packages/cdktf/test/dynamic-expression.test.ts, packages/cdktf/test/helper/resource.ts
- fix(lib): fix Symbol for Terraform dynamic expression causing crashes when using Iterator.dynamic() on blocks
- test(lib): Add a test case that would've caught the error that the previous commit fixed
=> fix(lib): fix Symbol for Terraform dynamic expression causing crashes when using Iterator.dynamic() on blocks

examples/csharp/documentation/ProviderClassesStack.cs, examples/csharp/documentation/cdktf.json, examples/go/documentation/cdktf.json, examples/go/documentation/providers.go, examples/java/documentation/cdktf.json, examples/java/documentation/src/main/java/com/mycompany/app/providers/MainImportClasses.java, examples/python/documentation/cdktf.json, examples/python/documentation/providers.py, website/docs/cdktf/concepts/providers.mdx, website/docs/cdktf/concepts/stacks.mdx
This should fix the documentation examples.
=> chore: pin provider versions in documentation examples

packages/@cdktf/hcl2cdk/lib/expressions.ts, packages/@cdktf/hcl2cdk/test/__snapshots__/tfExpressions.test.ts.snap, packages/@cdktf/hcl2cdk/test/resources.test.ts, packages/@cdktf/hcl2cdk/test/tfExpressions.test.ts, packages/@cdktf/hcl2json/lib/bridge.ts, packages/@cdktf/hcl2json/lib/index.ts, packages/@cdktf/hcl2json/lib/util.ts
Fixes https://github.com/orgs/hashicorp/projects/207/views/12?pane=issue&itemId=25824022
This is a pretty hacky PR, and I'm not really comfortable with the solution. That being said, I think this does resolve our immediate woes around heredocs. 
The problem is as such: By the time the heredoc string comes in for parsing by the expression parser, (I suspect) the hcl2json parser has already converted it into a quote containing newlines. Quote with newlines are not accepted within HCL and thus breaks our expression. 
This PR tries to detect newlines within string literals and wraps them back into a heredoc literal, making the expression parseable. As you can see from the PRs, this requires a lot of tweaks to existing logic to ensure it works ok, and even then, I'm not 100% sure this will not …
=> fix(hcl2cdk): Handle multi-line strings better

packages/cdktf-cli/src/bin/cmds/convert.ts, website/docs/cdktf/cli-reference/commands.mdx
Tiny typo in convert command documentation
Fixes # 
=> fix(docs): Fix typo in commands.mdx

packages/@cdktf/hcl2cdk/lib/expressions.ts, packages/@cdktf/hcl2cdk/test/expressionToTs.test.ts, packages/@cdktf/hcl2json/lib/util.ts, packages/@cdktf/hcl2json/test/util.test.ts
Fixes https://github.com/orgs/hashicorp/projects/207/views/12?pane=issue&itemId=25824299
If strings to be converted have quotes nested within them, we throw an error here. I don't know where we should solve this problem, but it requires more than just a few regexs. I went for a really complex solution but it just doesn't work without parsing. Maybe I missed something, but I'd like to get the core fix out before we find a complete solution to strings with nested quotes and nested templates.
=> fix: Accept nested quotes within strings

packages/@cdktf/provider-generator/lib/get/__tests__/generator/__snapshots__/types.test.ts.snap, packages/@cdktf/provider-generator/lib/get/__tests__/generator/fixtures/incompatible-resource-names.test.fixture.json, packages/@cdktf/provider-generator/lib/get/__tests__/generator/types.test.ts, packages/@cdktf/provider-generator/lib/get/generator/resource-parser.ts
Resolves #2627
I'm unsure whether releasing this as part of a patch is okay – it changes the `License` resource to `LicenseResource` which is a breaking change for folks that currently generate bindings for `consul`, so I'd rather merge this after our last patch release for the current version is out – what do you think?
=> fix(provider-generator): fix resources named 'license' causing collisions with LICENSE file on case-insensitive filesystems for Go packages

website/docs/cdktf/test/unit-tests.mdx
Fixes #2755
The document shows an example using `synthScope` that can test the `Construct` type. But this document is for most beginners, so we want to test the `Stack`, because followed docs were showing examples of `Stack`.
=> chore(docs): change to `synth` from `synthScope` for #2755

packages/@cdktf/cli-core/src/test/lib/terraform-parallelism.test.ts
Fixes issue with CI failures
The terraform parallelism test suite was the single most problematic test suite that blocked the 0.16 release and I had to retry a few times for that. It still causes a lot of problems on every release, so this is an attempt to try and resolve the issue.
=> chore: Mock synth to make parallelism test fail less

packages/@cdktf/cli-core/src/lib/models/deploy-machine.ts, packages/@cdktf/cli-core/src/test/models/deploy-machine.test.ts
=> fix(cli): buffer the output from the Terraform CLI and only forward output that has been terminated by a newline

packages/@cdktf/hcl2json/.npmignore
none
There can be some more files excluded from the npm package.
=> fix(lib): add more excludes to .npmignore

.github/workflows/pr-copyright.yml
Fix according to security advisory
=> fix: github action shouldn't use untrusted input

packages/@cdktf/commons/package.json
Fixes #2862
As mentioned in #2862 there are multiple non-required dependencies added to `@cdktf/commons`, this moves them to `devDependnecies` which makes it consistent with all other packages in the project.
- `typescript`
- `ts-jest`
- `jest`
No version changes or anything, just moved to be classified as development dependencies. With this these packages will not be required by others and should save on ~225 needless package installs, plus the disk space 🎉
=> fix(deps): make `jest` and `typescript` development dependencies

.github/workflows/integration.yml
Follow up on our github actions pinning PR. This removes the one instance that we're using the deprecated `set-output` mechanism.
=> chore: Clean up github actions containing deprecated parts

packages/@cdktf/cli-core/templates/typescript/tsconfig.json, packages/@cdktf/cli-core/tsconfig.json, packages/@cdktf/commons/tsconfig.json, packages/@cdktf/hcl2cdk/tsconfig.json, packages/@cdktf/hcl2json/tsconfig.json
Implements #2881
Enable the TS compiler feature `declarationMap`. This enables you to quickly navigate to the original sources, when you currently have a corresponding .d.ts file open and want to see its implementation.
=> feat(lib): Enable declarationMap feature in TS compiler

.github/ISSUE_TEMPLATE/bug-report-prebuilt-providers.yml, .github/ISSUE_TEMPLATE/bug-report.yml, .github/ISSUE_TEMPLATE/documentation.yml, .github/ISSUE_TEMPLATE/feature-request.yml
Annoying that there's no way to preview these before merging...
=> chore: nitpick GitHub issue templates

.gitignore, packages/@cdktf/provider-generator/lib/get/__tests__/generator/__snapshots__/types.test.ts.snap, packages/@cdktf/provider-generator/lib/get/generator/resource-parser.ts
Fixes #2879 
If an attribute is called "list" and it's parent class is accessible via a list both the interface for the attribute and the class for the accessor on the parents parent have the same name. This clash causes JSII to fail
=> fix(provider-generator): remove duplicates between wrapper classes and interfaces generated from provider schemas

CHANGELOG.md, package.json
- fix(provider-generator): remove duplicates between wrapper classes and interfaces generated from provider schemas [\#2895](https://github.com/hashicorp/terraform-cdk/pull/2895)
- fix(cli): run terraform init in serial so no text file is busy in the cache [\#2843](https://github.com/hashicorp/terraform-cdk/pull/2843)
- fix(cli): buffer the output from the Terraform CLI and only forward output that has been terminated by a newline [\#2844](https://github.com/hashicorp/terraform-cdk/pull/2844)
- fix(cli): fix no-color flag passing [\#2845](https://github.com/hashicorp/terraform-cdk/pull/2845)
- fix(hcl2cdk): Support conversion of functions that have variate arguments at the end [\#2833](https://github.com/hashicorp/terraform-cdk/pull/2833)
- chore: Mock synth to make parallelism test fail …
=> chore: release 0.16.2

.github/workflows/release.yml, .github/workflows/release_next.yml
We are running into [this bug](https://issues.sonatype.org/browse/OSSRH-66257) in a maven plugin. While we will update the version used in the corresponding publib files this fix should unblock us in the mean time, see this [SO post](https://stackoverflow.com/questions/70153962/nexus-staging-maven-plugin-maven-deploy-failed-an-api-incompatibility-was-enco)
=> chore: fix maven release

.github/workflows/pr-copyright.yml
Minor nitpick but we don't need to pass the token anymore with the newer version.
=> chore: remove unused input from copywrite

CHANGELOG.md, package.json
In `0.16.2` the release to maven failed, we fixed the issue and release this version so that maven is included in the release.
=> chore: release 0.16.3

.github/workflows/update-snapshots.yml
While auditing our GitHub Actions for TSCCR, I realized that we'd likely have to fight an uphill battle to get `ad-m/github-push-action` approved; it's sensitive to supply chain attacks, hasn't been updated in over 3 years/doesn't appear to be maintained, and is easily replaced by regular command line calls.
=> chore: remove ad-m/github-push-action

packages/@cdktf/hcl2cdk/test/helpers/convert.ts
This is only enabled if `Synth.yes_all_languages` is set for the test case. The test cases are skipped since the tests don't pass (the implementation is not there yet), but I think having this infrastructure in place is valuable.
=> chore(hcl2cdk): add testing infrastructure for convert in Python & CSharp

packages/@cdktf/cli-core/src/lib/synth-stack.ts
There was a recent case where someone on the CDK Dev Slack got this error and it took them a while to figure out that they were missing the `app.synth()` call which is probably the most common mistake leading to this error.
The current error message is not really helpful in that regard:
So this PR adds a hint.
=> fix(cli): Give hint when cdktf synth failed to create config

.github/workflows/gh-action-upgrade.yml
This adds a step to the automated GitHub Action update job to pin all the workflows. If a new version hasn't been added to TSCCR yet, this effectively undoes the upgrade, the idea being the auto-update script will run again in a week, and hopefully in the meantime the new version will have been added to TSCCR.
Note: hasn't been tested, as with all my GitHub Actions work, this will probably fail on first try. 😅
=> chore: pin all workflows after update

packages/@cdktf/cli-core/src/lib/cdktf-stack.ts, packages/@cdktf/cli-core/src/lib/models/terraform-cli.ts, packages/@cdktf/cli-core/src/lib/models/terraform.ts, test/typescript/init-repeatedly/cdktf.json, test/typescript/init-repeatedly/local-module/main.tf, test/typescript/init-repeatedly/main.ts, test/typescript/init-repeatedly/test.ts
=> fix(cli): Always run init, but selectively skip locking providers

examples/typescript/aws-kubernetes/cdktf.json, packages/@cdktf/provider-generator/lib/get/__tests__/generator/__snapshots__/skipped-attributes.test.ts.snap, packages/@cdktf/provider-generator/lib/get/__tests__/generator/skipped-attributes.test.ts, packages/@cdktf/provider-generator/lib/get/generator/models/attribute-type-model.ts, packages/@cdktf/provider-generator/lib/get/generator/models/scope.ts, packages/@cdktf/provider-generator/lib/get/generator/resource-parser.ts, packages/@cdktf/provider-generator/lib/get/generator/skipped-attributes.ts, website/docs/cdktf/concepts/resources.mdx
This change allows us to keep a disallow list of provider attributes that generate an insane amount of classes (in this case over 25.000) in our bindings. I decided to not automatically detect these instances to not prematurely optimise this. For a similar reasoning and since it's not automatically detected I also skipped the implementation of attribute skipping (since it's also very uncertain that attributes will ever be the problem).
=> feat(provider-generator): allow removing big, cost intensive structures

packages/@cdktf/hcl2json/wasm/bridge_wasm_exec.js
new node version already have a performance global, see https://nodejs.org/api/globals.html#performance
it contains many methods, see https://nodejs.org/api/perf_hooks.html
when always overwriting it, other modules like `undici` which use the performance object won't work any more. in genera using the performance object become unusable as soon as the `@cdktf/hcl2json` package is required.
discussion/bug: https://github.com/renovatebot/renovate/discussions/22615
Fixes # 
=> fix: do not always overwrite global.performance

packages/cdktf-cli/src/bin/cmds/helper/terraform-login.ts, packages/cdktf-cli/src/test/cmds/convert.test.ts
Resolves #2936
Tested it locally by setting a `PATH` that didn't contain `open` (which reproduced the failure and confirmed the fix)
=> fix(cli): catch possible errors when trying to open a url

packages/cdktf-cli/package.json, yarn.lock
Fixes #2952 
I'm still unsure why @inquirer/confirm version 2.0.1 has the bug where it takes all input as 'yes', but it does. From my local testing, changing the version to almost any other version resolves the issue. The library's code also doesn't give a hint about this, so I'm going to stop digging the 'why' and use the easy way forward with upgrading the library.
=> fix: Upgrade @inquirer/prompts to resolve #2952

README.md
Fixes # 
The **Documentation** section in the README contains outdated links and redirect to the new home of the CDKTF documentation, with the exception of the link to **Examples**, which is broken. This PR replaces the links with the new URLs for those pages.
=> chore(docs): update doc links to new URLs

.github/workflows/project-board.yml, .github/workflows/update-project-board-issue.yml
While we do have an hourly cron in place, this workflow will be even better if issue creation and updates triggers an update on the project board. We can trigger the script in the other repo with this workflow. (The `workflow_dispatch` is just a nice-to-have for testing.) I've confirmed it works at https://github.com/hashicorp/terraform-cdk-team/actions/runs/5402845986
Should be merged alongside #2970
=> chore: trigger project board update when issues modified

packages/@cdktf/commons/src/debug.ts
Fixes #2903 
`pnpm` uses a lock file called `pnpm-lock.yaml`, which can be used as a strong signal about which package manager is in use. There is an upcoming `packageManager` element in `package.json` that could also be used, but in practice this is not yet widespread.
Given the presence of this file, the updated logic switches to use `pnpm list` instead of `npm list`, and adapts to the updated file structure. I think it is fairly unlikely that a `pnpm-lock.yaml` file will exist if `pnpm` is not in use, so I've kept this very simple.
Further, I haven't made DRY efforts between the two methods, as I wasn't certain how useful that would be. I'm very happy to go further if the reviewers would like me to.
**Notes on tests:**
* no new unit tests are added -- there does not seem to be any …
=> fix(cli): Support PNPM when retrieving package dependency information

packages/@cdktf/provider-generator/lib/get/__tests__/generator/__snapshots__/complex-computed-types.test.ts.snap, packages/@cdktf/provider-generator/lib/get/__tests__/generator/__snapshots__/description-escaping.test.ts.snap, packages/@cdktf/provider-generator/lib/get/__tests__/generator/__snapshots__/module-generator.test.ts.snap, packages/@cdktf/provider-generator/lib/get/__tests__/generator/__snapshots__/nested-types.test.ts.snap, packages/@cdktf/provider-generator/lib/get/__tests__/generator/__snapshots__/provider.test.ts.snap, packages/@cdktf/provider-generator/lib/get/__tests__/generator/__snapshots__/resource-types.test.ts.snap, packages/@cdktf/provider-generator/lib/get/__tests__/generator/__snapshots__/skipped-attributes.test.ts.snap, packages/@cdktf/provider-generator/lib/get/__tests__/generator/__snapshots__/types.test.ts.snap, packages/@cdktf/provider-generator/lib/get/generator/emitter/resource-emitter.ts, packages/@cdktf/provider-generator/lib/get/generator/emitter/struct-emitter.ts, packages/@cdktf/provider-generator/lib/get/generator/module-generator.ts, packages/@cdktf/provider-generator/lib/get/generator/sanitized-comments.ts, test/provider-tests/test-provider.sh, test/provider-tests/update-all-provider-tests.sh
This should fix the issues we see in Java for the google beta provider
=> fix(provider-generator): sanitize all comments

lerna.json
Fixes integration examples not running in CI currently, example: https://github.com/hashicorp/terraform-cdk/actions/runs/5529364286/jobs/10087325820?pr=3003#step:3:9
=> fix: remove old lerna option causing it to fail when building a matrix in CI runs

packages/@cdktf/hcl2cdk/lib/__tests__/expressionToTs.test.ts, packages/@cdktf/hcl2cdk/lib/__tests__/findExpressionType.test.ts, packages/@cdktf/hcl2cdk/lib/expressions.ts, packages/@cdktf/hcl2cdk/lib/generation.ts, packages/@cdktf/hcl2cdk/lib/variables.ts
Resolves #2643 – more specifically the case in this comment: https://github.com/hashicorp/terraform-cdk/issues/2643\#issuecomment-1505215265
=> fix(provider-generator): wrap dynamic block iterator .key and .value in Token.asString as simply concatenating it won't work in non-TS languages

cdk.tf/vercel.json
I noticed today that the /bug and /feature links were broken/not pointing to the right forms anymore since we switched to issue templates, and then discovered a few other links that were outdated or could be removed.
=> chore: update cdk.tf links

examples/python/documentation/aspects.py, website/docs/cdktf/concepts/aspects.mdx
Fixes # 
I noticed that the documentation for Aspects in Python is not so easily understood. The reason is that it should call the Aspect class with the stack instance.
=> fix(docs): python docs for aspect

.copywrite.hcl, packages/cdktf-cli/.npmignore, test/.gitignore, test/local-registry.sh, test/run-against-dist, test/test-helper.ts, test/verdaccio.yaml
This ensures we install the cdktf-cli in the same way it is installed on user machines
=> fix: use local NPM registry for running integration tests on unix systems

examples/python/documentation/aspects.py
This also removes the need for another Aspect instance to test that it does work with the pet resource, as adding it to the stack will also invoke it for the pet resource
This change helps users that read the source of this example as adding an Aspect to a single resource serves not much purpose
=> fix(examples): Properly set the Aspect on the stack instead of on the S3Bucket only

packages/@cdktf/provider-generator/lib/get/__tests__/generator/__snapshots__/module-generator.test.ts.snap, packages/@cdktf/provider-generator/lib/get/__tests__/generator/fixtures/module-get-x.test.fixture.tf, packages/@cdktf/provider-generator/lib/get/generator/module-generator.ts
Fixes https://github.com/hashicorp/terraform-cdk/issues/1618
Allow `tuple` for variable type
=> feat(provider-generator): handle 'tuple' type for variable

.github/workflows/remove-waiting-on-answer.yml, .github/workflows/stale.yml
This currently happens automagically if the 'stale' label has already been applied by the bot but not if the user replies before the 'stale' label gets added.
=> chore: remove waiting-on-answer label on comments

packages/@cdktf/cli-core/src/lib/dependencies/package-manager.ts, packages/@cdktf/commons/src/debug.ts, packages/@cdktf/commons/src/gradle.ts, packages/@cdktf/commons/src/index.ts
Fixes integration issues in release pipeline
Due to the move to Gradle, we need to be able to read gradle dependencies in `cdktf debug` instead of using Maven.
=> fix(cli): cdktf debug to read gradle package versions

packages/@cdktf/cli-core/src/lib/dependencies/package-manager.ts, packages/@cdktf/commons/src/debug.ts, packages/@cdktf/commons/src/gradle.ts
Fixes CI integration test failures related to provider subcommands
=> fix: Gradle related provider add/list/upgrade

packages/@cdktf/cli-core/src/lib/dependencies/package-manager.ts, packages/@cdktf/commons/src/gradle.ts, packages/cdktf-cli/src/bin/cdktf.ts, test/java/provider-add-command/test.ts, test/java/provider-upgrade-command/test.ts, test/java/synth-app/__snapshots__/test.ts.snap, test/java/synth-app/test.ts, test/java/testing-matchers/test.ts
Fixes CI issues
The tests were failing due to a snapshot difference as well as the `gradle dependencies` file being unable to resolve the cdktf jar file with our test driver setup. This PR adds a fallback to using `build.gradle` for that situation. It shouldn't be used otherwise as `gradle dependencies` should be the source of truth.
=> fix: provider add java integration test failures due to test setup

website/docs/cdktf/create-and-deploy/performance.mdx
Since we work for an American company, I think we should standardize on American rather than British spelling - so `z` instead of `s` (e.g. `synthesize`, `optimize`, etc).
=> chore(docs): fix grammar and spelling on Performance page

.github/workflows/remove-waiting-on-answer.yml
It took until today for a comment to finally trigger only for this script to fail. 😅 I always forget that you have to do a checkout anytime that you want to use the `gh` CLI...
=> chore: fix remove-waiting-on-answer workflow

website/docs/cdktf/create-and-deploy/best-practices.mdx
Minor: Changing TF_VAR_adminPasword to TF_VAR_adminPassword to match the text in the block above and resolve typo.
Fixes: NA
Noticed a typo in the Read Secrets with Terraform Variables on https://developer.hashicorp.com/terraform/cdktf/create-and-deploy/best-practices#read-secrets-with-terraform-variables
In particular the example code says `TF_VAR_adminPasword='<your password>'` and missing the second s in password, which is correctly spelled in the preceding code block.
This is a one character change to documentation. If you feel the need to run the checklist please let me know.
=> fix(docs): Fix typo in example of using TF_VAR_ to set TerraformVariable

.github/workflows/unit.yml, packages/@cdktf/cli-core/src/lib/init.ts
This fixes the hcl2cdk test issues we have been seeing in CI and it's generally okay to install from wheels
=> fix: use whl to install local python

.github/workflows/pr-copyright.yml
A manual run was successful: https://github.com/hashicorp/terraform-cdk/actions/runs/6339657436/job/17219272138
However, this has to be merged to main first to fix the PR check (due to the `pull_request_target` trigger).
=> fix: set specific copywrite tool version to fix CI

packages/@cdktf/cli-core/src/lib/cdktf-project.ts, packages/@cdktf/cli-core/src/lib/models/terraform-cli.ts, packages/@cdktf/cli-core/src/lib/synth-stack.ts, packages/@cdktf/cli-core/src/test/lib/terraform-parallelism.test.ts, packages/@cdktf/commons/package.json, packages/@cdktf/commons/src/debug.ts, packages/@cdktf/commons/src/logging.ts, packages/@cdktf/commons/src/util.ts, packages/@cdktf/provider-generator/lib/__tests__/edge-provider-schema.test.ts, packages/@cdktf/provider-generator/lib/__tests__/provider.test.ts, packages/@cdktf/provider-generator/lib/get/__tests__/util.ts, packages/@cdktf/provider-generator/lib/get/constructs-maker.ts, packages/@cdktf/provider-generator/lib/get/generator/provider-generator.ts, packages/@cdktf/provider-generator/lib/util.ts, packages/@cdktf/provider-schema/src/provider-schema.ts, test/csharp/no-color-command-option-test/test.ts, test/go/no-color-command-option-test/test.ts, test/java/no-color-command-option-test/test.ts, test/python/no-color-command-option-test/test.ts, test/typescript/no-color-command-option-test/test.ts, yarn.lock
CI run
Makes sure no process can add color to output if noColor option is set
=> fix: make sure noColor option is honored

.github/workflows/pr-copyright.yml
`0.16.6` has been released which fixes the problem why we pinned this version in #3150
Fixes # 
=> fix: unpin version of copywrite

.github/workflows/build.yml, .github/workflows/examples.yml, .github/workflows/integration.yml, .github/workflows/provider-integration.yml, .github/workflows/unit.yml, .github/workflows/yarn-upgrade.yml
This PR
* Stops using random temporary directories for caches, as these make cache hits impossible (the cached paths are part of the "cache version" which needs to match in order for caches to be restored)
* Starts using the same cache directories for caches of the same type (e.g. `/usr/local/share/.cache/go` for the Go cache). This allows us to get cache hits between different jobs as a fallback
* Starts using distinct cache directories for all caches of the same type (types being `terraform`, `go`, `yarn` and `providerSchema`).
* Re-names the cache keys to allow cache hits using a hierarchical restore-keys definition
* Defines `restore-keys` for caches of the same type. This allows us to restore e.g. a yarn cache from a different job if there's no cache already for the current job …
=> fix: fix Github workflow caches to restore successfully more often

packages/@cdktf/cli-core/package.json, packages/@cdktf/cli-core/src/lib/error-reporting.ts, packages/cdktf-cli/package.json, yarn.lock
=> fix: Fix partial dependency update for Sentry

CHANGELOG.md, package.json
Fixes a bug in 0.18.1 that broke crash reporting due to a partial dependency upgrade.
- fix: Fix partial dependency update for Sentry [\#3172](https://github.com/hashicorp/terraform-cdk/pull/3172)
=> chore(release): Update CHANGELOG.md and version to 0.18.2

examples/typescript/google/main.ts
Changed image from debian-cloud/debian-9 to debian-cloud/debian-12 because debian-cloud/debian-9 image is not available.
```zsh
➜  terraform-cdk git:(fix/machine_image) gcloud compute images list | grep debian
debian-10-buster-v20231010                            debian-cloud         debian-10                                      READY
debian-11-bullseye-arm64-v20231010                    debian-cloud         debian-11-arm64                                READY
debian-11-bullseye-v20231010                          debian-cloud         debian-11                                      READY
debian-12-bookworm-arm64-v20231010                    debian-cloud         debian-12-arm64                                READY
debian-12-bookworm-v20231010                          debian-cloud …
```
=> chore(examples): change debian image version in gcp example

CHANGELOG.md, packages/@cdktf/provider-generator/lib/get/generator/models/attribute-model.ts
Previously had the name `move` in our list of escaped attributes, fixed it to be `moveTo` which is the current naming.
=> fix(lib): correct escaped attribute for moveTo

CHANGELOG.md, package.json, website/docs/cdktf/release/upgrade-guide-v0-19.mdx
**Breaking changes**
Since the long-term support for Node.js 16 ended on 2023-09-11, we updated our minimum compatible Node.js version to 18.12.
We have added support for resource refactoring and renaming with the addition of the instance function `moveTo` on 
`TerraformResource`. We forsee the potential for naming collision with providers using `moveTo` as an attribute. In instances where provider bindings fail to compile due to the collision, regenerate your provider bindings and replace the provider related usage of `moveTo` to `moveToAttribute` in your configuration if applicable.
We did not honor the `codeMakerOutput` setting in the `cdktf.json` previously, this is fixed now. To have no changes in the generated code you can set `codeMakerOutput: "imports"`.
If you like, you can now …
=> chore(release): Update CHANGELOG.md and version to 0.19.0

packages/cdktf-cli/src/bin/cmds/handlers.ts, website/docs/cdktf/cli-reference/commands.mdx
Fixes #2190
Includes provider info (local and prebuilt) into `cdktf debug`.
=> feat(cli): Include provider info in cdktf debug 

.github/workflows/docker.yml
This will allow us to roll back or test against specific versions. It will add two more tags beside the latest, one with the current release and one with the current release and a git sha
=> chore: add tags to jsii-terraform image

examples/csharp/documentation/IteratorStack.cs, examples/csharp/documentation/MyTerraformStack.csproj, examples/java/documentation/src/main/java/com/mycompany/app/MainIterator.java, examples/java/gradle-shared-module/gradle/wrapper/gradle-wrapper.properties, examples/python/documentation/Pipfile, examples/python/documentation/Pipfile.lock, examples/python/documentation/iterators.py, examples/typescript/documentation/iterators.ts, website/docs/cdktf/concepts/iterators.mdx
fixes #2452
Terraform only [supports a set of strings, and maps](https://developer.hashicorp.com/terraform/language/meta-arguments/for_each) with the `for_each` meta-argument.
The way for CDKTF to support complex list iterators would be to implement a kind of [for expression](https://developer.hashicorp.com/terraform/language/expressions/for) when synthesising the iterator with `for_each`, however that isn't currently supported. 
For now, this PR updates the example code to use maps instead of a complex list, until we implement the above.
=> fix: iterator examples

packages/@cdktf/commons/src/checkpoint.ts
=> fix(cli): Don't send telemetry events if request body is larger than 8KB

CHANGELOG.md, package.json
- feat(cli): Include provider info in cdktf debug [\#3190](https://github.com/hashicorp/terraform-cdk/pull/3190)
- fix(cli): Don't send telemetry events if request body is larger than 8KB [\#3255](https://github.com/hashicorp/terraform-cdk/pull/3255)
- chore: disable provider schema tests [\#3257](https://github.com/hashicorp/terraform-cdk/pull/3257)
- chore: update cdktf version being used in documentation tool [\#3256](https://github.com/hashicorp/terraform-cdk/pull/3256)
- chore: fix provider-schema tests [\#3254](https://github.com/hashicorp/terraform-cdk/pull/3254)
- chore: update registry docs version [\#3249](https://github.com/hashicorp/terraform-cdk/pull/3249)
- chore: Upgrade dependencies for @cdktf/hcl2json [\#3248](https://github.com/hashicorp/terraform-cdk/pull/3248)
- chore: …
=> chore: release 0.19.1

.github/workflows/pr-depcheck.yml, packages/@cdktf/provider-generator/package.json, packages/@cdktf/provider-schema/package.json
Splitting up  #3202 to integrate it step by step
=> chore: fix dependencies for provider packages

.github/workflows/examples-pr.yml, .github/workflows/pr-integration.yml, .github/workflows/pr-lint.yml, .github/workflows/pr-provider-integration.yml, .github/workflows/pr-unit.yml
Enable PR checks to be run for all PRs, since we now have the merge queue. This prevents us from merging things that break the release pipeline.
=> chore: Run all tests per PR unless skipped

examples/typescript/aws-move/main.ts, packages/cdktf/lib/index.ts, packages/cdktf/lib/synthesize/synthesizer.ts, packages/cdktf/lib/terraform-resource.ts, packages/cdktf/lib/terraform-stack.ts, packages/cdktf/lib/upgrade-id-aspect.ts, packages/cdktf/test/resource.test.ts, website/docs/cdktf/examples-and-guides/refactoring.mdx, website/docs/cdktf/release/upgrade-guide-v0-17.mdx
Adds a alternative workflow for performing resource moves by specifying resource ids directly. 
The original workflow for resource moves didn't have (as of writing this) any bugs per say, yet some of the tradeoffs made in it's design made certain use cases quite difficult. As such, I made resource instance functions where the id to move to/from can be directly specified. Provides a better experience compared to using escape hatches, while avoiding potentially unhelpful abstraction in the targeting system.
In particular we saw in [migrating the repository manager to use our new id generation](https://github.com/cdktf/cdktf-repository-manager/pull/233) that using the target system was incredibly cumbersome. In response to this use case, I've created an Aspect that will automatically perform …
=> feat(lib): add move workflows for specifying ids directly

CHANGELOG.md, packages/@cdktf/provider-generator/lib/get/generator/resource-parser.ts
Backport of https://github.com/hashicorp/terraform-cdk/pull/3285
=> fix(provider-generator): fix oci provider by skipping attributes that conflict after being camel cased (backport)

packages/cdktf/lib/terraform-data-source.ts, packages/cdktf/lib/terraform-resource.ts, packages/cdktf/test/__snapshots__/resource.test.ts.snap, packages/cdktf/test/resource.test.ts
=> fix(lib): Fix handling of replaceTriggeredBy lifecycle attribute

packages/@cdktf/commons/src/provider-schema.ts, packages/@cdktf/provider-generator/lib/get/__tests__/generator/__snapshots__/nested-types.test.ts.snap, packages/@cdktf/provider-generator/lib/get/__tests__/generator/fixtures/nested-type-without-attributes.test.fixture.json, packages/@cdktf/provider-generator/lib/get/__tests__/generator/nested-types.test.ts, packages/@cdktf/provider-generator/lib/get/generator/resource-parser.ts
Fixes #3144
Don't require `nested_type` to have `attributes` defined.  Relevant for certain use cases where just the presence of an attribute is used to define the resource. 
Such as...
```json
"predictor_bot_detection": {
"nested_type": {
"nesting_mode": "single"
},
"description": "A single nested object that specifies options for the Bot Detection predictor.  At least one of the following must be defined: `predictor_anonymous_network`, `predictor_bot_detection`, `predictor_composite`, `predictor_custom_map`, `predictor_device`, `predictor_geovelocity`, `predictor_ip_reputation`, `predictor_user_location_anomaly`, `predictor_user_risk_behavior`, `predictor_velocity`.",
"description_kind": "markdown",
"optional": true
},
```
Where just the presence of predictor_bot_detection = {} in  HCL …
=> fix(provider-generator): don't require attributes to be set on nested_type

CHANGELOG.md, examples/python/aws-eks/cdktf.json, examples/python/aws/main.py, packages/@cdktf/commons/src/config.ts, packages/@cdktf/commons/src/construct-maker-target.test.ts, packages/@cdktf/commons/src/construct-maker-target.ts
Closes #3026
We use the fqn in a sanitized version now instead of the namespace, leading to less likely collissions in python, c#, and java. For go and typescript we leave the same logic.
Let's assume the `cdktf.json`
```jsonc
{
// ...
"terraformModules": [
{
"name": "eks",
"source": "terraform-aws-modules/eks/aws",
"version": "~> 16.0"
},
"terraform-aws-modules/vpc/aws@5.0.0",
"terraform-aws-modules/rds/aws@5.0.0",
"cloudposse/label/null",
"terraform-google-modules/project-factory/google",
"terraform-aws-modules/eks/aws//modules/self-managed-node-group"
]
}
```
```
.gen/modules/
├── cloudposse
│   └── null
│       └── label.ts
├── terraform-aws-modules
│   └── aws
│       ├── eks
│       │   └── modules
│       │       └── self-managed-node-group.ts
│       ├── rds.ts
│       └── vpc.ts …
```
=> fix(provider-generator): use module name that does not collide commonly

packages/@cdktf/hcl2cdk/lib/index.ts, packages/@cdktf/hcl2cdk/lib/provider.ts, packages/@cdktf/hcl2cdk/lib/variables.ts, packages/@cdktf/hcl2cdk/test/__snapshots__/resources.test.ts.snap, packages/@cdktf/hcl2cdk/test/resources.test.ts, packages/cdktf/lib/index.ts, packages/cdktf/lib/terraform-data-resource.ts, packages/cdktf/lib/validations/validate-provider-presence.ts, packages/cdktf/test/terraform-data-resource.test.ts, website/docs/cdktf/concepts/resources.mdx
The code is based on the output of our provider-generation as that requires only a simple (import related) special handling in convert
Closes #3142
=> feat(lib): Add support for the built-in Terraform data resource

.github/workflows/registry-docs-pr-based.yml
The provider repos are spammed with our branches, so we now preventively clean them up
=> chore: delete old branches before docs rollout

packages/@cdktf/cli-core/src/lib/execution-logs.ts, packages/@cdktf/cli-core/src/test/lib/execution-logs.test.ts
Fixes #2331
Fixes the issue where our augmented logs match to the wrong resource when there are resource ids that overlap. Such as two resources named `null_resource` and `null_resource2` respectively. This was occurring previously since we just checked if a line included the resource id, which led to situation where `null_resource` would be mapped to `null_resource2`.
Introduced stricter matching where we check each line for the presence of the whole resource id rather than just a subset.
=> fix(cli): Handle overlapping resource names in augmented logs

Dockerfile
Docker build had a problem: https://github.com/hashicorp/terraform-cdk/actions/runs/7387708978/job/20096990663
```
#7 [4/7] RUN pip install pipenv
#7 0.338 error: externally-managed-environment
#7 0.338 
#7 0.338 × This environment is externally managed
#7 0.338 ╰─> To install Python packages system-wide, try apt install
#7 0.338     python3-xyz, where xyz is the package you are trying to
#7 0.338     install.
#7 0.338     
#7 0.338     If you wish to install a non-Debian-packaged Python package,
#7 0.338     create a virtual environment using python3 -m venv path/to/venv.
#7 0.338     Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
#7 0.338     sure you have python3-full installed.
#7 0.338     
#7 0.338     If you wish to install a non-Debian packaged Python application, …
```
=> fix pipenv build

Dockerfile
the main python installation is marked as system-wide and causes installs to fail
=> chore: use activated virtual env in docker

website/docs/cdktf/concepts/stacks.mdx
Since CDKTF has a primitive called stacks and we also have an upcoming (now announced) feature that is also called "stacks" or "Terraform stacks" - I wrote a sentence with a link to point out the differences.
=> feat(docs): Add note to address having the same name as new Terraform stacks feature

packages/@cdktf/provider-generator/lib/__tests__/provider.test.ts, packages/@cdktf/provider-generator/lib/get/__tests__/generator/provider.test.ts, packages/@cdktf/provider-generator/lib/get/generator/provider-generator.ts, packages/@cdktf/provider-generator/lib/get/generator/resource-parser.ts
Fixes #2730
Allows for a provided name in a provider constraint (i.e. within`terraformProviders` of`cdktf.json`) to differ from the name found in source. The provided name is then used as the namespace for the folder containing the provider in `.gen`.
In `cdktf.json`
```json
...
"terraformProviders": [
{
"name": "dockerr",
"source": "registry.terraform.io/kreuzwerker/docker"
}
],
...
```
Generated provider in `.gen`
=> fix(provider-generator): provided name does not need to match name in source

examples/typescript/documentation/cdktf.json, examples/typescript/documentation/providers.ts, website/docs/cdktf/concepts/providers.mdx
Fixes #2575
Typescript example in `providers.mdx` now uses locally build bindings in it's imports to align with documentation wording.
=> chore: Use locally built bindings for ts provider doc example

.vscode/settings.json, packages/@cdktf/cli-core/src/lib/synth-stack.ts, packages/@cdktf/commons/src/config.test.ts, packages/@cdktf/commons/src/config.ts, packages/@cdktf/provider-schema/src/provider-schema.ts, packages/cdktf/lib/terraform-element.ts, packages/cdktf/lib/terraform-module-asset.ts, packages/cdktf/lib/terraform-module.ts, packages/cdktf/lib/testing/index.ts, packages/cdktf/lib/tfExpression.ts, packages/cdktf/test/__snapshots__/module.test.ts.snap, packages/cdktf/test/__snapshots__/terraform-hcl-module.test.ts.snap, packages/cdktf/test/assets.test.ts, packages/cdktf/test/module.test.ts, packages/cdktf/test/terraform-hcl-module.test.ts, packages/cdktf/test/terraform-module-asset.test.ts, test/test-helper.ts, test/typescript/modules-relative-paths/README.md, test/typescript/modules-relative-paths/cdktf-project/cdktf.json, test/typescript/modules-relative-paths/cdktf-project/main.ts, test/typescript/modules-relative-paths/terraform-modules/constants/main.tf, test/typescript/modules-relative-paths/terraform-modules/register/main.tf, test/typescript/modules-relative-paths/test.ts, test/typescript/modules/test.ts, website/docs/cdktf/concepts/modules.mdx
When multiple local terraform modules are mentioned in the `cdktf.json` and they rely on one-another locally with relative paths the previous implementation destroyed the structure of their relative paths. This implementation uses a single asset for all terraform modules, leading to correct relative paths.
Closes #2460
=> fix: Terraform Modules relatively referencing each other with generated bindings

.github/workflows/release.yml, .github/workflows/release_next.yml
We temporarily inline the publib script until we can make the necessary upstream change
that respects virtual environments
=> chore: fix python publishing

.github/workflows/release.yml, .github/workflows/release_next.yml
We use twine directly for publishing instead of publib-pypi. Publib-pypi does the same twine command (https://github.com/cdklabs/publib/blob/main/bin/publib-pypi) but also tries to install twine which is already globally available in the docker image we use. It upgrades twine, introducing risks of breaking changes. (Though not likely, twine is ancient).
We can not keep the install since the update to python 3.11 in the docker image forbids global installs since the global pip is system managed.
Running this install in a virtualenv would be possible but would require changes for the publib-pypi script. This is the easiest solution for now.
=> chore: simplify python release

packages/cdktf/lib/functions/terraform-functions.generated.ts, tools/generate-function-bindings/scripts/fetch-metadata.ts, tools/generate-function-bindings/scripts/functions.json, website/docs/cdktf/api-reference/csharp.mdx, website/docs/cdktf/api-reference/go.mdx, website/docs/cdktf/api-reference/java.mdx, website/docs/cdktf/api-reference/python.mdx, website/docs/cdktf/api-reference/typescript.mdx
Closes #2816
- fix(docs): Add override to ensure function bindings docs don't have relative links without the terraform product prefix in them
- fix(docs): update API docs
=> fix(docs): product relative links

packages/@cdktf/cli-core/src/lib/dependencies/version-constraints.ts, packages/@cdktf/cli-core/src/test/lib/dependencies/version-constraints.test.ts
Versions below `1.0` are treated a bit differently in NPM than in Terraform meaning that NPMs `^0.4` doesn't allow `0.55` while TFs `~>0.4` allows `0.55`.
This PR ensures that `~>0.4` matches `0.55`.
=> fix(cli): Fix version range matching for 0.x version ranges with the ~> operator

examples/typescript/aws-cloudfront-proxy/main.ts, packages/@cdktf/provider-generator/lib/get/__tests__/generator/export-sharding.test.ts, packages/@cdktf/provider-generator/lib/get/__tests__/generator/fixtures/aws_wafv2_web_acl.test.fixture.json, packages/@cdktf/provider-generator/lib/get/generator/skipped-attributes.ts, test/typescript/synth-app/__snapshots__/test.ts.snap, test/typescript/synth-app/main.ts
This is a breaking change for users of these properties in these resources. It is necessary to bring down the size of the generated Go code though and also has an effect on all other languages.
For Go it shrinks the size of the generated code for the AWS provider from 648MB to 357MB. Previously the two resources accounted for 187MB (web acl) and 103MB (rule group) of the total size
Our resource docs already state that some attributes are skipped which includes mentions of the web acl resources (even though they weren't affected in the past)
Resolves #3358
=> fix(provider-generator): Skip `statement` block for `rule` block in `aws_wafv2_web_acl` and `aws_wafv2_rule_group` resources

CHANGELOG.md, package.json
**AWS Provider changes (breaking)**
The AWS pre-built provider for Go is currently too large to be installed due to a hard limit in Go. This release adds skipping the `statement` block in the `rule` block of the `aws_wafv2_web_acl` and `aws_wafv2_rule_group` resources. Our [resource docs page](https://developer.hashicorp.com/terraform/cdktf/concepts/resources#special-cases) previously already mentioned that these resources have skipped attributes but they weren't actually skipped. This almost doubled AWS provider bindings in size due to the recursive nature of the `statement` block.  
If you are using any of these two resources, the `statement` now has to be passed as a plain object instead and its keys have to be snake-cased (e.g. `and_statement` or `regex_match_statement`).
- …
=> chore(release): Update CHANGELOG.md and version to 0.20.1

.github/workflows/yarn-upgrade.yml
On an empty diff it is an empty file which gets commited otherwise, see https://github.com/hashicorp/terraform-cdk/pull/3395
=> chore: fix updating script

packages/cdktf/lib/upgrade-id-aspect.ts, packages/cdktf/test/upgrade-id-aspect.test.ts, website/docs/cdktf/examples-and-guides/refactoring.mdx
CDKTF does not support moved blocks for modules at this point, hence it requires manual work
=> fix(lib): Print a warning with manual steps to move a module when UpgradeIds aspect encounters modules

packages/cdktf-cli/src/bin/cmds/handlers.ts, packages/cdktf-cli/src/bin/cmds/helper/init.ts, packages/cdktf-cli/src/bin/cmds/helper/terraform-login.ts, packages/cdktf-cli/src/bin/cmds/helper/utilities.ts
=> fix(cli): don't prompt for providers during convert

website/docs/cdktf/create-and-deploy/remote-templates.mdx
The [remote templates](https://developer.hashicorp.com/terraform/cdktf/create-and-deploy/remote-templates) docs page has a [built-in templates](https://github.com/hashicorp/terraform-cdk/tree/main/packages/cdktf-cli/templates) link that's currently 404; the templates were moved in ef76955222231305d74bd9f7b3c6b79aa0e35f74. This PR updates the link to the new location of the templates.
=> chore(docs): fix currently-404 link to built-in templates

packages/@cdktf/provider-generator/lib/__tests__/provider.test.ts, packages/@cdktf/provider-generator/lib/get/generator/models/resource-model.ts, packages/@cdktf/provider-generator/lib/get/generator/provider-generator.ts, test/typescript/renamed-providers/cdktf.json, test/typescript/renamed-providers/main.ts, test/typescript/renamed-providers/test.ts
Adds support for the Terraform feature described here: https://developer.hashicorp.com/terraform/language/providers/requirements#handling-local-name-conflicts
Resolves #1258
=> feat(provider-generator): support renaming provider names in order to allow using two providers sharing the same name at the same time

website/docs/cdktf/concepts/iterators.mdx
=> chore: add CodeTabs component

CHANGELOG.md, package.json
- feat(provider-generator): support renaming provider names in order to allow using two providers sharing the same name at the same time [\#3442](https://github.com/hashicorp/terraform-cdk/pull/3442)
- feat(provider-generator): Ensure we have unique names for modules [\#3439](https://github.com/hashicorp/terraform-cdk/pull/3439)
- feat(docs): Mention Maven examples in note on project setup page [\#3437](https://github.com/hashicorp/terraform-cdk/pull/3437)
- fix(docs): Run prettier [\#3445](https://github.com/hashicorp/terraform-cdk/pull/3445)
- fix(lib): support dot-seperated nested accessors [\#3444](https://github.com/hashicorp/terraform-cdk/pull/3444)
- fix(docs): Update CLI docs to refer to Gradle instead of Maven [\#3434](https://github.com/hashicorp/terraform-cdk/pull/3434)
- …
=> chore: release 0.20.2

packages/cdktf/lib/app.ts, website/docs/cdktf/api-reference/csharp.mdx, website/docs/cdktf/api-reference/go.mdx, website/docs/cdktf/api-reference/java.mdx, website/docs/cdktf/api-reference/python.mdx, website/docs/cdktf/api-reference/typescript.mdx
=> feat(docs): Document how outdir works when passed to App and while using CDKTF CLI

packages/cdktf/lib/hcl/render.ts, packages/cdktf/lib/terraform-stack.ts, packages/cdktf/test/json-to-hcl.test.ts
The existing HCL output converted each Terraform local in a separate `locals` block, which is not ideal. While this is a purely cosmetic change that doesn't really impact the HCL synth correctness, it makes the synthed output easier to read, and closer to how practitioners would expect it to be.
=> chore: Improve locals output - Group all locals into one locals block

packages/cdktf/lib/hcl/render.ts, packages/cdktf/test/json-to-hcl.test.ts
Fixes #3459
Terraform expects keys of maps to be [valid identifiers](https://developer.hashicorp.com/terraform/language/syntax/configuration#identifiers), and the HCL synth was not ensuring that before. This PR tries to detect areas where quoting is required to ensure valid HCL is output.
=> fix: Map keys not being quoted when they are not valid identifiers

website/docs/cdktf/concepts/hcl-interoperability.mdx
Update HCL interoperability docs to include information about synthesizing to Terraform HCL.
=> chore: Update HCL Interoperability docs to include HCL synthesis

CHANGELOG.md, package.json
- feat(cli): add console logs to better surface correct workflow for creating go projects [\#3466](https://github.com/hashicorp/terraform-cdk/pull/3466)
- feat(docs): Document how outdir works when passed to App and while using CDKTF CLI [\#3463](https://github.com/hashicorp/terraform-cdk/pull/3463)
- fix: corrected formating for java provider dependencies [\#3468](https://github.com/hashicorp/terraform-cdk/pull/3468)
- fix: Map keys not being quoted when they are not valid identifiers [\#3464](https://github.com/hashicorp/terraform-cdk/pull/3464)
- chore: Improve locals output - Group all locals into one locals block [\#3465](https://github.com/hashicorp/terraform-cdk/pull/3465)
- chore: Update HCL Interoperability docs to include HCL synthesis …
=> chore: release 0.20.3

packages/cdktf-cli/src/bin/cmds/helper/terraform-login.ts, packages/cdktf-cli/src/test/cmds/init.test.ts
=> fix(cli): opening browser using CLI hangs the shell process forever

packages/cdktf-cli/src/bin/cdktf.ts, website/docs/cdktf/cli-reference/commands.mdx
Fixes #3489 
We were using `CDKTF_LOG_FILE_DIRECTORY` within our logger, but we never made it into a supported CLI flag. CDKTF configures [yargs](https://yargs.js.org/) in a way that all environment variables with the `CDKTF_` prefix are treated as CLI flags. For commands that had [`strict`](https://yargs.js.org/docs/#api-reference-strictenabledtrue) enabled, that means that setting any non-supported flag with the `CDKTF_` prefix would cause the command to fail. This PR now adds support for this flag and it should work across all commands.
=> fix: Make `CDKTF_LOG_FILE_DIRECTORY` a common flag available on all commands

CHANGELOG.md, package.json
- fix: Make `CDKTF_LOG_FILE_DIRECTORY` a common flag available on all commands [\#3495](https://github.com/hashicorp/terraform-cdk/pull/3495)
- fix(cli): opening browser using CLI hangs the shell process forever [\#3480](https://github.com/hashicorp/terraform-cdk/pull/3480)
- chore: Upgrade dependencies for util [\#3518](https://github.com/hashicorp/terraform-cdk/pull/3518)
- chore: npm-check-updates && yarn upgrade [\#3511](https://github.com/hashicorp/terraform-cdk/pull/3511)
- chore: Upgrade dependencies for cli [\#3510](https://github.com/hashicorp/terraform-cdk/pull/3510)
- chore: Upgrade dependencies for lib [\#3509](https://github.com/hashicorp/terraform-cdk/pull/3509)
- chore: change schedule time to be before our week starts …
=> chore(release): Update CHANGELOG.md and version to 0.20.4

.github/workflows/update-project-board-issue.yml
Late last year I decided that the `update-project-board` script is better off living in its own repo after all, and I got it all set up except I kept forgetting to actually update this script to point to the new place.
Feel free to wait to merge this until Monday, no rush.
=> chore: update-project-board-issue calls different repo

website/docs/cdktf/concepts/stacks.mdx
The italics on this 'Note:' at the beginning of the page is broken.
=> fix(docs): Italics broken

CHANGELOG.md, package.json
- fix(lib): Correctly render string tokens that contain plain objects [\#3545](https://github.com/hashicorp/terraform-cdk/pull/3545)
- fix: hcl rendering nested maps [\#3536](https://github.com/hashicorp/terraform-cdk/pull/3536)
- fix(docs): Italics broken [\#3490](https://github.com/hashicorp/terraform-cdk/pull/3490)
- chore: fix typo [\#3553](https://github.com/hashicorp/terraform-cdk/pull/3553)
- chore: add separate workflow for JSII upgrades [\#3552](https://github.com/hashicorp/terraform-cdk/pull/3552)
- chore(deps): pin trusted workflows based on HashiCorp TSCCR [\#3549](https://github.com/hashicorp/terraform-cdk/pull/3549)
- chore: Upgrade dependencies for util [\#3548](https://github.com/hashicorp/terraform-cdk/pull/3548)
- chore: Upgrade dependencies for util …
=> chore(release): Update CHANGELOG.md and version to 0.20.5

packages/@cdktf/provider-schema/src/__tests__/__snapshots__/provider-schema.test.ts.snap, packages/@cdktf/provider-schema/src/__tests__/provider-schema.test.ts, packages/@cdktf/provider-schema/src/provider-schema.ts, yarn.lock
Some providers sporadically return them double leading to errors in cdktf convert and get
Fixes #3526
Fixes #3170
=> fix(cli): sanitize type arrays

CHANGELOG.md, package.json
- fix(cli): sanitize type arrays [\#3578](https://github.com/hashicorp/terraform-cdk/pull/3578)
- fix(lib): Correctly render string tokens that contain plain objects [\#3545](https://github.com/hashicorp/terraform-cdk/pull/3545)
- fix: hcl rendering nested maps [\#3536](https://github.com/hashicorp/terraform-cdk/pull/3536)
- fix(docs): Italics broken [\#3490](https://github.com/hashicorp/terraform-cdk/pull/3490)
- chore: fix typo [\#3553](https://github.com/hashicorp/terraform-cdk/pull/3553)
- chore: add separate workflow for JSII upgrades [\#3552](https://github.com/hashicorp/terraform-cdk/pull/3552)
- chore(deps): pin trusted workflows based on HashiCorp TSCCR [\#3549](https://github.com/hashicorp/terraform-cdk/pull/3549)
- chore: Upgrade dependencies for util …
=> chore: release 0.20.6

CHANGELOG.md, package.json
- fix(provider-generator): refactor logic to determine if a block is optional or required [\#3580](https://github.com/hashicorp/terraform-cdk/pull/3580)
- chore(deps): pin trusted workflows based on HashiCorp TSCCR [\#3583](https://github.com/hashicorp/terraform-cdk/pull/3583)
- chore: Upgrade dependencies for cli [\#3588](https://github.com/hashicorp/terraform-cdk/pull/3588)
- chore: Upgrade dependencies for cli [\#3574](https://github.com/hashicorp/terraform-cdk/pull/3574)
- chore: Upgrade dependencies for util [\#3573](https://github.com/hashicorp/terraform-cdk/pull/3573)
- chore: Upgrade dependencies for lib [\#3572](https://github.com/hashicorp/terraform-cdk/pull/3572)
=> chore(release): Update CHANGELOG.md and version to 0.20.7

.github/workflows/release.yml, README.md
When/if hashicorp/homebrew-tap#273 gets addressed we should look for where is the appropriate place in our README/docs to instruct users on how to use the HashiCorp tap to install `cdktf`.
=> chore: remove Homebrew link and publishing step

website/docs/cdktf/test/debugging.mdx
This threw me for about five seconds when I was reading the documentation. I'm pretty sure this is what was meant.
I went over the checklist and I don't think any of it applies since this is not a code change.
=> chore: Fix a small documentation typo

.github/workflows/registry-docs-pr-based.yml
when a revert is using a part of the branch name it leads to problems in the cleanup
since the matched part is what we assume is the branch name and that one does not exist.
The origin/ should make sure that there can be no prefix, technically we should also guard against suffixes bug we'll cross that bridge when we get there
=> chore: fix branch cleanup

test/verdaccio.yaml
Configure Verdaccio to explicitly listen on IPv4 as there's some problem in the latest Github Runner Image with `localhost` and IPv4 / IPv6.
=> fix: explicitly listen on ipv4 address for verdaccio due to Github runner image regression

packages/@cdktf/cli-core/src/test/lib/cdktf-project.test.ts, packages/cdktf/lib/manifest.ts, packages/cdktf/test/manifest.test.ts, test/python/cross-stack-references/test.ts, test/typescript/cross-stack-references/test.ts
Ensure that the `manifest.json` file has stable output. Removes instances where test snapshots fail when no content has changed, but `JSON.stringify` shuffles object attribute order. Suggested by #3561
=> chore: manifest.json should have stable json

packages/cdktf/lib/backends/s3-backend.ts
No related issue as it is only a simple 2-line change. Can create one if required.
When providing these fields as a string rather than a list of strings, Terraform throws an error. This PR updates the types to be a list of strings, to allow specifying the format that Terraform requires (similar to the other S3BackendConfig keys such as sharedConfigFiles, sharedCredentialsFiles etc).
=> fix(lib): Correct types for allowedAccountIds & forbiddenAccountIds in S3Backend

website/data/cdktf-nav-data.json, website/docs/cdktf/api-reference/csharp/index.mdx, website/docs/cdktf/api-reference/go/index.mdx, website/docs/cdktf/api-reference/index.mdx, website/docs/cdktf/api-reference/java/index.mdx, website/docs/cdktf/api-reference/python/index.mdx, website/docs/cdktf/api-reference/typescript/index.mdx
This PR is a fast follow up to PR-3668. 
This PR adds index.mdx files to each language folder in the API reference. Adding the index pages eliminates the need to add redirects as well as enforces a pattern for creating new folders.
=> chore: added index pages for each library to the docs

.mise.toml, packages/cdktf/lib/hcl/render.ts, packages/cdktf/test/json-to-hcl.test.ts
Also added a [mise](https://mise.jdx.dev/) config for my development environment
=> fix(lib): render empty string as quotes

.github/workflows/pr-lint.yml
This usually fails for commits by tools that don't adhere to our requirements as the commit message is concerned. For example PRs like this one: https://github.com/hashicorp/terraform-cdk/pull/3714 As our changelog generation script only uses PR titles to begin with, we don't need this safeguard to lint single commit PRs on their commits as well.
=> fix(release): Don't validate single commit for semanticity

.github/workflows/cdktf-provider-docs-rollout.yml, .github/workflows/registry-docs-pr-based.yml
I noticed the other day that the Registry docs were being built off of CDKTF 0.20.1 when 0.20.8 is out. When trying to figure out why there's such a discrepancy, I realized it's because of this.
I don't know if we've fixed or changed anything about `convert` that would change the actual docs output, but it's worth keeping this updated in case there have been improvements.
=> chore: increase version of cdktf-registry-docs used

.github/CODEOWNERS
I'm trying to standardize who can approve PRs to docs across all our code repos. Please let me know if you have any feedback! 
Fixes # 
=> chore: Add web presence ability to approve PRs to website files

packages/@cdktf/commons/package.json, packages/@cdktf/commons/src/terraform-module.test.ts, packages/@cdktf/commons/src/terraform-module.ts, yarn.lock
#3787 failed to trigger CI, resubmitting this so that we can get this merged.
Closes #3787
Fixes # 
=> fix: punycode deprecation warning

.github/workflows/cdktf-provider-docs-rollout.yml, .github/workflows/release.yml, .github/workflows/release_next.yml
The parent [PR](https://github.com/hashicorp/terraform-cdk/pull/3795) updates the Slack Github Action to v2 which has a few breaking changes that affect us. Information on breaking changes are [here](https://github.com/slackapi/slack-github-action/releases/tag/v2.0.0). 
The actions pertain to failure reports in our [#feed-terraform-cdk](https://hashicorp.enterprise.slack.com/archives/C03N81HHDUP) channel. From investigating the integration settings, it seems like all are webhooks are of the 'workflow builder' type. For those, we have to set the `webhook-type` to `webhook-trigger`. **NOTE:** If any of our webhooks are not of that type and I was mistaken, please let me know so I can update the PR accordingly.
This PR is based on top of the parent PR's branch, so should be merged right after …
=> fix: Update slack action usage for slack action v2

package.json, packages/@cdktf/cli-core/package.json, packages/cdktf-cli/package.json, yarn.lock
Fixes https://github.com/hashicorp/terraform-cdk/security/dependabot/100
=> fix: Upgrade version of esbuild without security vuln

packages/cdktf/lib/tokens/string-fragments.ts, packages/cdktf/test/tokens/string-fragments.test.ts
The `concat` method was not properly updating `this.fragments` because `Array.prototype.concat` returns a new array and does not modify the original array in place. Changed the implementation to use `this.fragments.push(...other.fragments);` to correctly merge the fragments into `this.fragments`.
I thought `concat` method in `TokenizedStringFragments` was intended to merge fragments from another instance into `this.fragments`. However, it was not functioning correctly because `Array.prototype.concat` returns a new array and does not modify the original array in place.
To fix this issue, I updated the `concat` method to use `this.fragments.push(...other.fragments);`. This modifies `this.fragments` in place and ensures that all fragments are correctly merged.
=> fix(lib): correct the concat method in TokenizedStringFragments

.github/workflows/pr-depcheck.yml, packages/@cdktf/hcl-tools/jest.config.js, packages/@cdktf/hcl-tools/package.json
Fixes https://github.com/hashicorp/terraform-cdk/issues/3852
Added the missing `fs-extra` dependency to `package.json` that is used here:
https://github.com/hashicorp/terraform-cdk/blob/41c1ccdbf9c9f140161d643bda424ee8595a7e48/packages/%40cdktf/hcl-tools/src/bridge.ts#L5
=> chore: add missing dependency on `fs-extra` to `@cdktf/hcl-tools`

packages/cdktf/lib/private/fs.ts
Fixes #3858 
I'm not sure why this only showed up once we upgraded the version of `archiver` in the last release, but intuitively this should've always been a problem. Was led to this by @DarkAtra's comment ❤️ .
=> fix: issue where archive was being closed before the file finished writing causing corrupt TerraformAssets
